- scheduler/CHANGELOG.md
- scheduler/project.clj
- Release cook. 
Revert a change that added extra logging to jobs being considered for scheduling, this was slowing down matching offers.
> Release Cook 1.36.1

- integration/tests/cook/test_basic.py
- using up to 2 pools, instead of all active pools
We've seen this test time out in the initial `for` loop over pools, and it's not really necessary to run this for every single active pool under test.
> Makes test_list_jobs_by_pool complete faster

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- don't require the job to complete for the test to complete
In the wild, we sometimes see jobs take a long time to complete, and this test shouldn't rely on the test completing, only on the progress being posted to the instance.
> Makes test_progress_update_submit more reliable

- executor/cook/_version.py
- executor/cook/executor.py
- executor/cook/util.py
- Log stack traces in the executor when we kill a task
Try to trace down why the cook executor sometimes blocks when sending a framework message.
> log stacktraces when executor is asked to kill task

- executor/bin/check-version.sh
- integration/bin/run-integration.sh
- scheduler/bin/submit-docker.sh
- Remove python:3.5 docker image references. Migrate everything to python:3.5.9-stretch.
Avoids having to bring down python:3.5 at all, saving a gig of docker space.
> Move other python:3.5 docker image references to python:3.5.9-stretch

- integration/tests/cook/test_multi_user.py
- making sure to grab the successful instances
There can be failed instances on the jobs, and we specifically are interested in the successful ones for the purposes of this test.
> Makes test_instance_stats_success more reliable

- integration/.dockerignore
- scheduler/.dockerignore
- Ignore some virtualenv environments
We tend to use these names for virtualenv environments. Lets .dockerignore them so that we get smaller docker images that build faster.
> Tweak dockerignore for integration tests + scheduler

- scheduler/config-composite.edn
- Make a config.edn that activates mesos + GKE
Make it easier for others to replicate my test environment.
> Make composite mesos+k8s edn for docker+gke

- scheduler/config-k8s.edn
- scheduler/config.edn
- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/mesos/task.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/mesos/task.clj
- scheduler/test/cook/test/zz_simulator.clj
- moving the container defaults configuration from the top-level to the compute-cluster
Not all compute clusters can use the same container defaults. For example, you might need to configure Mesos with one set of default volumes that don't exist and therefore don't work in k8s.
> Makes container defaults be compute-cluster specific

- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/mesos/task.clj
- scheduler/test/cook/test/mesos/task.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- adding `use-cook-executor?` to the `ComputeCluster` protocol
- in `job->task-metadata`, consulting `use-cook-executor?` to determine whether or not to do all the Cook executor stuff
The Cook executor is a Mesos-only thing. Even if we're configured to use, it doesn't make sense to use it on k8s.
> Avoids Cook executor when launching on k8s

- integration/tests/cook/test_basic.py
- setting `max_retries` to 5 in `test_multiple_progress_updates_submit`
- marking `test_max_runtime_exceeded` as `xfail`
The retries are to allow `test_multiple_progress_updates_submit` to be resilient to failures.
The `xfail` is because `test_max_runtime_exceeded` can fail due to "Container launch failed", and we don't want to add retries because this test actually expects the job to fail due to exceeding its max runtime.
> Marks one test xfail, makes another more reliable

- integration/tests/cook/test_basic.py
- changing the job command to sleep for the duration of the test
Otherwise, the job can complete before the test completes, causing it to fail.
> Makes test_unique_host_constraint more reliable

- integration/tests/cook/test_multi_user.py
- lowering cpu and mem requests for the test jobs
We have seen these jobs wait for a long time on GKE, and there is no need for them to be requesting so much cpu and memory.
> Lowers resource requests for test_instance_stats_success

- scheduler/src/cook/kubernetes/compute_cluster.clj
- removing `:type` keys from the existing and expected state maps
These are actually being processed by downstream code, as if they were real states, which is not what we want.
> Removes :type keys from state maps

- integration/travis/run_integration.sh
- scheduler/datomic/data/seed_running_jobs.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Make reconciler only reconcile mesos tasks.
Right now if you have kubernetes + mesos enabled, the mesos reconciler sees all these kubernetes jobs not running in mesos and kills them off. Make the mesos reconciler only look at jobs in the relevant compute cluster instead.
> Make reconciler only reconcile mesos tasks.

- integration/tests/cook/test_basic.py
- changing the test from using 3 lines of output to just 1 line
When running in Mesos, the executor can interleave its own output with the output from the command, which causes this test to flakily fail.
> Makes test_output_url more reliable

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
1. in `wait_for_instance`, instead of returning the 0th instance, return the 0th instance that has the desired status
1. in `test_change_failed_retries`, don't assume that there was a non-mea-culpa failure on the job
1. Despite the `wait_until` filtering on status, this function is always blindly returning the 0th instance, which can have a different status, causing tests to fail.
1. If the job fails with a mea-culpa reason, e.g. `Agent removed`, then it will have the full 4 retries instead of only 3.
> Fixes bugs in util.wait_for_instance, test_change_failed_retries

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/unscheduled.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- scheduler/test/cook/test/unscheduled.clj
- using `user->rate-limit-count` instead of `user->number-jobs` for determining whether to report rate-limiting as a reason why the job is not being scheduled
Fixes #1356 
Please see the issue above for more context.
> Fixes incorrect rate-limit reason in /unscheduled_jobs

- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- fixes the compute-cluster argument in mesos-scheduler call to receive-offers
Passing incorrect argument causes the receive offer code to fail which eventually leads to no scheduling of jobs.
> fixes the compute-cluster argument in mesos-scheduler call to receive-offers

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/constraints.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- allowing a configurable max number of pods per node for k8s compute clusters
- filtering out nodes that are not below that threshold
- adding a new Fenzo `ConstraintEvaluator`, `"max_tasks_per_host"`, that enforces the constraint while matching
We need to be able to limit the number of pods Cook will attempt to start up per node.
This is an example of what the `/unscheduled_jobs` output shows for a job that is hitting the new constraint:
```
{
"reason": "The job couldn't be placed on any available hosts.",
"data": {
"reasons": [
{
"reason": "max_tasks_per_host",
"host_count": 1
}
]
}
}
```
> Avoids matching onto nodes that have reached their pod limit

- scheduler/src/cook/rest/api.clj
- Renumber 403→404 for "uuid does not correspond to a valid object" errors
- Renumber 403→400 for "invalid request format" errors
These were typos in the documentation. The typo probably happened in one spot and then got copy/pasted all over the place.
> Correct misnumbered 403 error codes for swagger

- scheduler/config.edn
- Delete `job-adjuster` plugin config from config.edn
The `job-adjuster` plugin implementation doesn't exist.
> Remove missing plugin from config.edn

- cli/.gitignore
- scheduler/bin/run-docker.sh
Add options for `--zk=local` (local zookeeper started in the same container as cook scheduler) or `--zk=minimesos` (minimesos zookeeper) to the `run-docker.sh` script.
This makes it easier to bring up multiple Cook Scheduler instances locally for testing interactions that require leadership checks.
> Add minimesos zookeeper flag in run-docker.sh

- integration/tests/cook/test_basic.py
- integration/travis/run_integration.sh
- add functionality to disable integration tests in travis using travis_skip test marker
Some integration tests require too much modification to the travis pipeline (e.g. upgrading mesos) to work. Add the travis_skip test marker to those tests to skip
> disable test that can't run in travis

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/project.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/rest/api.clj
- simulator/resources/job_schedule.edn
- simulator/src/main/cook/sim/runner.clj
- simulator/src/main/cook/sim/schedule.clj
- populates the user parameter in docker container parameters when not provided explicitly in the job
- removes dependency on me.raynes/conch
When docker user parameters are not provided, the command runs as root inside the docker container. Instead, we would like to limit the container to always run as the user on the job.
> populates the user parameter in docker container parameters

- scheduler/src/cook/compute_cluster.clj
- logging the compute cluster name only in `safe-kill-task`
- making the docstring be in the proper spot in `kill-task-if-possible`
- removing superfluous spaces from a log in `kill-task-if-possible`
To make our logs cleaner.
> Logs the compute cluster name instead of entire object in safe-kill-task

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/progress.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/zz_simulator.clj
The job progress update aggregator is currently part of the Mesos scheduler component. This is for legacy reasons. We should instead initialize it in components.clj and then thread it into other components that use it.
We need the progress update aggregator at the top level so that we can use it both for updates from Mesos framework messages (the current implementation) and from the REST API (wip for k8s).
> Promote progress-aggregator-chan to components graph

- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- Improve our node and pod watches so that they retry forever instead of exiting on certain errors. 
- Also improve logging.
Fix a bug where we lose track of whats going on.
> Improve our node and pod watches so that they retry forever instead of exiting on certain errors

- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- killing all running and waiting jobs for each user at the start of test
- changing the look-back in `util. kill_running_and_waiting_jobs` from 4 hours to 72 hours
If the user under test happens to already have a running job, then the usage assertions will fail. These test users need to start the test with a clean slate.
> Makes test_multi_user_usage more reliable

- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- changing the `log-weird-state` log from `ERROR` level to `INFO` level
- making it use the pre-existing "prepare for logging" functions
`ERROR` is not appropriate for weird cases that will happen regularly. Without the "prepare for logging" functions, this was dumping the entire pod yaml to the log, which is excessive and makes viewing logs pretty painful.
> Improves logging for 'weird' k8s states

- scheduler/src/cook/scheduler/scheduler.clj
- improving error handling / logging in `write-status-to-datomic` and in the startup code
We have run into cases where the `fenzo` scheduler ends up `nil` here. This doesn't fix that bug, but it improves the logging so that we can better track down the cause.
> Improves logging in write-status-to-datomic

- scheduler/src/cook/kubernetes/api.clj
- changing the pod-watch exception log from `ERROR` level to `INFO` level
It's expected and frequent for the pod-watch to throw when it times out.
`ERROR` makes it harder to distinguish these from unexpected errors, and `INFO` will still allow us to view these in the normal places.
> Makes pod-watch exception log INFO level

- integration/setup.cfg
- integration/tests/cook/test_basic.py
- Fix invalid strings escapes in regular expressions
- Add unregistered pytest marks to config
Eliminate warnings from pytest output:
```
==================================================================================================================================== warnings summary ====================================================================================================================================
tests/cook/test_basic.py:51
/home/nickv/projects/cook/integration/tests/cook/test_basic.py:51: DeprecationWarning: invalid escape sequence \(
url_regex = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
tests/cook/test_basic.py:596
/home/nickv/projects/cook/integration/tests/cook/test_basic.py:596: DeprecationWarning: invalid escape sequence \d …
```
> Fix warnings from pytest

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/progress.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/rest/api.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
Add REST endpoint `/progress/<instance-uuid>` for POSTing job instance progress updates.
Job instance progress updates are currently communicated via Mesos framework messages. We need a new mechanism for reporting progress to use on Kubernetes.
We plan to have our Kubernetes log sidecar duplicate some of the current Cook Executor functionality to monitor log files for progress messages, but then POST to this new endpoint rather than sending Mesos framework messages.
This PR only implements the endpoint. The new progress reporting functionality for the log sidecar on Kubernetes will come as a separate patch.
> Add REST endpoint for posting job progress updates

- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Fix a small bug in state machine.
- A variety of weird states aren't as weird as we thought and/or are symptomatic of deeper bugs.
- Improve the logging.
In the kubernetes tracking state machine, the old bad code would go:
(completed,succeeded) -> (missing,succeeded) -> (missing,missing), inadvertently deleting its local state first and keeping the kubernetes state.
The correct transitions should go:
(completed, succeeded) -> (completed,missing), (missing,missing).
so we're always tracking the local state.
Weird states are supposed to be things that should never occur. So we want less false positives in the log.
> Various small tweaks to the state machine

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
Use scalar-requests for job container resources when constructing k8s pod specs.
Fixes a bug where the sidecar's resources were added into the main job
container's resource requests and limits, in addition to specifying
those resources in the sidecar's container.
<details>
<summary>
I dumped the value of <code>task-request</code> at the start of <code>task-metadata->pod</code>, which is when I noticed the difference between its <code>:resources</code> and <code>:scalar-requests</code> members.
</summary>
```clojure
;; 2020-01-29 20:13:56,944 INFO  cook.kubernetes.api [async-thread-macro-4] - TASK FOR POD:
{:job
{:job/pool
{:pool/name "k8s-gamma",
:pool/purpose "This is a pool for testing purposes",
:pool/state :pool.state/active,
:pool/dru-mode :pool.dru-mode/default},
:job/commit-latch …
```
> Use scalar-requests for job container resources

- integration/tests/conftest.py
- setting a configurable timeout on the POST for test metrics
We've seen cases where tests timeout in pytest because the test metrics request hangs.
> Adds timeout to test metrics POST request

- scheduler/src/cook/rest/api.clj
- changing the log level from `ERROR` to `INFO`
These logs are expected to happen regularly, for example when request validation fails. `ERROR` is excessive.
> Makes log in logging-exception-handler be INFO level

- integration/tests/cook/test_basic.py
- scheduler/docs/kubernetes-state.dot
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/controller.clj
When a pod submission fails in a way we know is permanent, mark the instance as Failed in the database and transition from (starting, missing) to (completed, missing) in the k8s state machine.
The `:missing` edge from `Starting` to `Completed` is new:
This is a "fast fail" for invalid pods, so that their jobs don't stay in the Running state forever.
```
$ COOK_TEST_DEFAULT_SUBMIT_POOL=k8s-alpha COOK_TEST_COMPUTE_CLUSTER_TYPE=kubernetes pytest -k test_pod_submission_failed -n1
=============================================================================================================================== test session starts ===============================================================================================================================
platform linux -- Python 3.6.8, …
```
> Handles pod submission failures

- integration/tests/cook/test_multi_user.py
- skipping `test_multi_user_usage` for k8s
- skipping `test_user_total_usage` for k8s
Due to the multi-user aspect of these tests, they are currently failing in some of our environments. We will re-enable when this is resolved.
> Skips two multi-user usage tests for k8s only

- scheduler/src/cook/datomic.clj
- changing the log level from `ERROR` to `INFO`
Cook can log this thousands of times on startup. `ERROR` is excessive.
> Changes 'dropped item from tx-report-mult' log to INFO

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/config-k8s.edn
- scheduler/src/cook/config.clj
- scheduler/src/cook/tools.clj
- adding an integration test that explicitly submits with no pool specified
- commenting out the sidecar configuration
- adding some logs for settings and for `(config/default-pool)`
For some reason, when the `:job-resource-adjustment` config is present, `(config/default-pool)` returns `nil`, which is bad. The test will help us catch issues like this in the future.
Fixing the issue will come in a later patch (@nsinkov has identified the cause).
> Adds test and logging for default pool

- scheduler/config-k8s.edn
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Add support to blacklist nodes in kubernetes that have certain labels. Nodes with these labels will not be used for scheduling. These labels can be dynamically added and removed.
So we can defer using nodes until they're fully initialized.
> Add support to blacklist nodes in kubernetes that have certain labels

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- When we're in the state where we have a starting pod, and kill it, we may think the pod's not on kubernetes because the watch is stale, so we'll not kill it. In this change, we kill the pod. 
- We also log when remaining weirder corner cases occur.
Makes the cook log look less scary and suppresses it mentioning about weird states.
> Fix a race where we don't kill a pod thats been sent to kubernetes because the watch hasn't returned yet.

- scheduler/config-k8s.edn
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/scheduler/scheduler.clj
- don't try to resolve function names when processing the config file
The act of resolving function names when processing the config file has side effects. Some of the side effects can be the calling of functions that depend on the config itself. Until we figure out a way to resolve function names without side effects we need to go back to resolving functions at runtime
> Fix nil default pool

- scheduler/src/cook/kubernetes/api.clj
- Suppress raising an error when we try to delete a pod thats not in k8s.
Avoids log spam and makes it easier to followup on real problems.
> Suppress errors deleting already deleted pods

- integration/tests/cook/test_basic.py
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Fix overlapping k8s mounts. When the workdir has the same path as a mount, we make a bad pod configuration that's rejected by k8s.
We have a failing integration test and this is a legit configuration.
> Fix overlapping k8s mounts

- integration/tests/cook/test_basic.py
- commenting out the wait-for-successful-instance
This assertion is timing out in our internal environments.
> Comments failing assertion in test_docker_fields

- integration/tests/cook/test_basic.py
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- setting the failure reason to `:reason-slave-removed` when a pod goes into `:pod/waiting` after it was running
This is a sign that our pod was moved to a new node.
For example, on GKE preemptible VMs:
> there is no guarantee that Pods running on preemptible VMs can always shutdown gracefully. It may take several minutes for GKE to detect that the node was preempted and that the Pods are no longer running, which will delay the rescheduling of the Pods to a new node.
(https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms#best_practices)
> Sets failure reason appropriately when node goes away

- scheduler/project.clj
Upgrade org.clojure/core.cache to 0.8.2
We've encountered problems with our ttl+lru cache for progress
reporting, and that bug was fixed in release 0.7.0. Upgrading to the
latest stable version (2019-09-30) for additional bug fixes.
> Upgrade org.clojure/core.cache to 0.8.2

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Write new logic for the :running,:missing case.
In cases where a pod disappears on us completely, we'd get a NPE. This can occur in some cases when GKE preempts a node. This changes the logic into a path that no longer NPE's.
> Avoid NPE when a running job goes completely missing

- integration/tests/cook/test_basic.py
- removing assumption about the 0th instance
None of our tests should assume that a particular instance will work, because instances can fail with e.g. "Agent disconnected".
> Makes test_set_retries_to_attempts_conflict more reliable

- executor/cook/executor.py
- logs absolute path of the tracked progress file
We would like to unambiguously and easily determine the progress file being tracked by the executor.
> logs absolute path of the tracked progress file

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- Retry k8s startup forever.
- Some minor logging improvements. 
The kubernetes watches used to retry forever, but the initial cluster setup would not retry. It needs to 
enumerate the pods in k8s in order to determine what state to load from datomic.
> Retry k8s startup forever

- integration/tests/cook/test_basic.py
- Fix integration test broken internally in PR #1406.
- The change to the integration test to validate the instance successfully launched succeeded in minimesos and k8s, but failed in mesos. So, revert that change and make a new integration test for overlapping workdir and volume mount.
> Added new integration test for kubernetes volume=workdir mount successfully launches.

- scheduler/src/cook/kubernetes/api.clj
- Fast fail when we get a bad request response from k8s
If we submit a broken configuration, no need to let it get stuck.
> Fast fail when we get a bad request response from k8s

- scheduler/src/cook/kubernetes/compute_cluster.clj
- `reset!`ing the `pool->fenzo-atom` before initializing the watches
Otherwise, we will start to see and handle events for pods, but we won't be able to update the corresponding Fenzo instance (e.g. un-assigning a completed task from its host).
Observed this log during the compute cluster initialization:
https://github.com/twosigma/Cook/blob/d4ceb8aec493c84cdf93e887642713059d1fab92/scheduler/src/cook/scheduler/scheduler.clj#L264-L265
> Initializes pool->fenzo atom earlier

- scheduler/docs/reason-code
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/mesos/reason.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- adding the "Normal exit" reason (documented but never implemented until now)
- using the "Normal exit" reason when a k8s instance succeeds
- adding the `task-id` to the log when an unknown reason is passed to `mesos-reason->cook-reason-entity-id`
Without the first two changes, we're doing the following on every successful pod:
1. Calling `container-status->failure-reason` for no good reason
1. Logging warnings unnecessarily
The addition of `task-id` to the log is to make the log more useful for troubleshooting.
> Uses 'Normal exit' reason for successful k8s instances

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- Reduce the memory used by 8x forintegration test test jobs.
- Reduce the CPU used by >8x for integration test test jobs.
Increase parallelism and decrease integration test runtimes to give us higher testing throughput.
> Decrease default integration test job size.

- cli/cook/querying.py
- cli/cook/subcommands/ssh.py
- integration/tests/cook/test_cli.py
- don't look up sandbox directory when ssh'ing kubernetes
looking up the sandbox directory when ssh'ing kubernetes is not needed and will fail when there is no ouput_url. There will not be an ouput_url when the fileserver sidecar is not enabled. But a user should still be able to ssh into their pod
> don't resolve the sandbox directory when ssh'ing kubernetes

- integration/tests/conftest.py
- checking the `_skipped_by_mark` attribute to see if a test was actually skipped
Unfortunately, tests marked as `xfail` that fail have a call outcome of 'skipped'. So, we have to workaround this by consulting `_skipped_by_mark`.
> Fixes result reporting for failed xfail tests

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- Most jobs are annotated with which integration test created them. 
Many/most of our test jobs have the same name, this can make it hard to trace where a test job came from (when the underlying integration test passes). Try to auto-pick a name variant to make it easier to do this tracing.
> Name test jobs with their caller function to better identify them.

- integration/tests/cook/test_basic.py
- removing the `max_runtime` from the job spec
If we get "unlucky", the lingering task killer will kill the job before progress is reported.
> Makes test_configurable_progress_update_submit more reliable

- scheduler/src/cook/mesos/sandbox.clj
- changing the log from `ERROR` to `INFO`
In the wild, we see this happen somewhat regularly, and the code is already designed to retry when this fails.
> Changes 'Failed to get mesos agent state' log from ERROR to INFO

- integration/tests/cook/test_basic.py
- Have two integration tests properly skip themselves when max-ports is too low.
- When we set max-ports to zero, these tests fail when they should be skipping themselves.
> Gate the port-related tests to actually having ports enabled.

- integration/tests/cook/test_basic.py
- taking the max of (timeout-interval-based timeout, default timeout)
Even though the test is marked `xfail`, if it times out, the test run fails. In environments with a low timeout-interval, e.g. 1 minute, we may need the longer default timeout.
> Fixes timeout for test_straggler_handling

- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- changing log from `WARN` to `INFO`
- adding more context to the log
In the wild, we see this log thousands of times per day, e.g. we receive "task lost" status updates from Mesos due to "health check timed out" and then 2 minutes later Mesos tells us the task is running again. We don't need this to be `WARN`.
> Improves log in handle-status-update

- integration/tests/cook/test_basic.py
- removing `max_runtime` from the job spec
- fixing a formatting issue
In environments with a small interval for the lingering task killer (e.g. 1 minute), Cook can kill the task with `Task max runtime exceeded` before the progress update is published.
> Makes test_multiple_rapid_progress_updates_submit more reliable

- integration/tests/cook/test_cli.py
- scheduler/docs/reason-code
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/mesos/mesos_compute_cluster.clj
- scheduler/test/cook/test/rest/api.clj
- adding a mapping for this status reason from Mesos
Mesomatic doesn't have a mapping for [`REASON_TASK_KILLED_DURING_LAUNCH`](http://mesos.apache.org/documentation/latest/task-state-reasons/#for-state-task_killed), so we're rolling our own mapping for it here.
This avoids tons of "Unknown mesos reason" warning logs.
> Adds mapping for REASON_TASK_KILLED_DURING_LAUNCH

- integration/tests/cook/test_basic.py
- Don't fail test when pod exits non-zero in the test_workdir_volume_overlap test and the cook init script is used
The test_workdir_volume_overlap test uses a non-writable workdir which causes the cook init script to exit non-zero
> don't fail test when init script is used

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/progress.clj
- Increase progress aggregator's sequence-number cache's TTL
- Improve test_progress_update_rest wait intervals
Increasing the cache TTL should help avoid flakes in the test_progress_update_rest
integration test where out-of-sequence progress updates are not ignored.
The wait/retry intervals in this test should be a function of the
progress reporter's publish interval, not hard-coded.
> Deflake test_progress_update_rest

- scheduler/docs/reason-code
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- scheduler/test/cook/test/rest/api.clj
- adding a "running" reason
- setting the `:reason` to this new reason for k8s instances
The `write-status-to-datomic` code in the scheduler expects a non-`nil` reason, and when it gets `nil` (without this patch), it logs a warning and uses the `:mesos-unknown` reason, which is not what we want.
> Adds running reason for k8s instances

- scheduler/src/cook/kubernetes/api.clj
- Change the log line for blocklist to log the key and value.
Nicer logging when we block a node from being used.
> Change the log line for blocklist to log the key and value.

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- Avoid NPE in sandbox calculation when compute cluster is not found.
- Fix a couple of comments.
NPE is bad.
> Avoid NPE in sandbox calculation when compute cluster is not found.

- integration/tests/cook/test_basic.py
- removing `max_runtime` from the job specs
- add retries to jobs
In environments with a small interval for the lingering task killer (e.g. 1 minute), Cook can kill the task with `Task max runtime exceeded` before the progress update is published. Random failures could also cause the tests to fail if there are no retries.
> Make progress tests more reliable

- integration/tests/cook/test_cli.py
- adding retries to `test_submit_with_command_prefix`
- marking `test_cat_basic` as `xfail`
The retries are to make the test job more resilient to transient failures.
The `xfail` is because the test periodically flakes in our internal environment.
> Makes test_submit_with_command_prefix more reliable

- integration/tests/cook/util.py
- scheduler/bin/help-make-cluster
- scheduler/bin/make-gke-test-clusters
- scheduler/bin/priority-class-cook-workload.yaml
- scheduler/bin/priority-class-synthetic-pod.yaml
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
There are a few different changes all related to improving the way synthetic pods work. The main change is introducing priority classes for Cook job pods and synthetic pods.
The priority classes allow the job pods to preempt the synthetic pods and avoid instance failures due to pending synthetic pods racing with the job pods when new capacity becomes available.
I've marked significant changes in this PR with a comment explaining the "why".
> Improves synthetic pods

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/kubernetes/metrics.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Add metrics on time to process actions caused by k8s events including pod-deleted pod-updated.
- Add metrics on the rate of k8s events, including pod-deleted about pod-updated.
- Add metrics on lock contention and delays from locking.
- Add metrics on loading all nodes and all pods from k8s.
- Add metrics on time-to-waiting and time-to-running (to characterize watch delays, k8s delays, and time it takes for a pod to become running)
- Add metrics on rate of generating synthetic pods.
- Add metrics on k8s operations, including creating and deleting a pod.
- Add metrics on error rates when sending pods to k8s, distinguishing between bad pod specifications versus other errors. 
- Add metrics on the workload cook is putting on the kubernetes compute cluster -- specifically creating and …
> Adds k8s metrics

- integration/tests/cook/test_cli.py
- adding retries to the job
To make the test more resilient to transient instance failures.
> Makes test_show_progress_message_custom_progress_file more reliable

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_multi_user.py
- skipping `test_output_url` for k8s runs
- adding retries to some test jobs
We don't yet support `output_url` on k8s.
The retries are to make those tests more resilient to transient instance failures.
> Disables test_output_url for k8s runs

- integration/tests/cook/test_basic.py
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/schema.clj
- making "Container launch failed" mea culpa
In the wild, these errors are almost always caused by platform issues rather than issues with the user's job.
> Makes "Container launch failed" mea culpa

- scheduler/src/cook/scheduler/scheduler.clj
- removing recently introduced log that does `(count pending-jobs)`
`pending-jobs` is lazy and can be large and expensive to realize.
> Removes expensive log from handle-resource-offers!

- integration/tests/cook/test_multi_user.py
Force the job to retry until we see a running instance (max 5 tries).
We've observed this test fail even though it's sleeping for 5 minutes. The job instance transitioned directly from "unknown" to "success" (missed framework message?).
> Make test_instance_stats_running more reliable

- integration/tests/cook/util.py
Assert success response code in `list_jobs` integration test helper function.
We've seen tests fail because this helper returned a non-JSON error response. It would be better to fail in `list_jobs` rather than later failing in the JSON parser and trying to figure out what went wrong from there.
> Assert success response code in list_jobs test helper

- scheduler/src/cook/kubernetes/compute_cluster.clj
- Add SSL verification between the cook and k8s.
To prevent man-in-the-middle with someone pretending to be the backend.
> Add SSL verification between k8s at cook

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- instead of using match failures, using `pending-jobs` post-match to trigger autoscaling
Let's say we have 1000 jobs in the queue, we send the top 200 to Fenzo, and 100 of those get matched. Instead of autoscaling for only the remaining 100, we want to autoscale for the 900 still-pending jobs. Of course, the KCC `autoscale!` implementation still has a configurable cap on the number of outstanding synthetic pods per compute cluster.
> Autoscales based on pending jobs instead of match failures

- scheduler/bin/help-make-cluster
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- changing the pool label from `cook_pool` to `cook-pool`
- making it a `def`
To make the name match the `cook-pool` taint.
> Changes node label from cook_pool to cook-pool

- scheduler/src/cook/kubernetes/api.clj
- Add `COOK_SANDBOX` env var to k8s sidecar container
- Deprecate `COOK_WORKDIR` env var for k8s sidecar container
This is the first step for untangling the concepts of the _sandbox_ and the _working directory_ for our Cook K8s jobs. Updating the sidecar logic to use `COOK_SANDBOX`, updating the scheduler to allow different values for the two paths, and finally deleting `COOK_WORKDIR` from the sidecar container will each come as later incremental patches.
> Add COOK_SANDBOX, deprecate COOK_WORKDIR for sidecar

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/metrics.clj
- scheduler/src/cook/scheduler/scheduler.clj
- Rename metrics
- Avoid using compute-cluster-* in a metric name. 
Make our new metrics more consistent, in naming, with existing metrics. Also, avoid using compute-cluster-* in metric names so that we can pattern-match this substring in logstash.
> Rename metrics to be consistent with prior metric naming

- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/controller.clj
This is a follow-up to PR #1466.
- instead of immediately considering unschedulable pods to be failed, require that they've been in that state for `:pod-condition-unschedulable-seconds` seconds (defaults to 60)
Kubernetes can be briefly report pods as being unschedulable on their way to getting scheduled. In the wild, we've seen this when a pod (e.g. Cook workload) is preempting another pod (e.g. synthetic pod). Until the preemption is complete, the pod that is doing the preempting is reported as unschedulable.
> Allows pods to briefly be Unschedulable without failing

- integration/tests/cook/test_multi_user.py
- making the jobs sleep for the duration of the test instead of 10 minutes
If the test runs for longer than 10 minutes, we don't want the jobs to complete since we're testing the usage (running jobs) of the user.
> Makes test_user_total_usage more reliable

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/scheduler/constraints.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/scheduler/constraints.clj
- adding node "anti"-affinity to synthetic pods, disallowing them from being scheduled on nodes where their corresponding job has already run
Cook has a "novel host constraint", which disallows a job from running on the same host twice. So, we need to avoid running a synthetic pod on any of the hosts that the real job won't be able to run on. Otherwise, the synthetic pod won't trigger the cluster autoscaler.
> Adds synthetic pod anti-affinity to previous hosts

- scheduler/test/cook/test/scheduler/constraints.clj
This is a follow-up to PR #1477.
- asserting on the length of the returned collection
To ensure there aren't duplicates.
> Improves test-job->previous-hosts-to-avoid

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
Separate the concepts of the working directory and sandbox directory for jobs in k8s pods.
1. The working directory (which may be specified by the user) is not guaranteed to be writable.
2. This separation better models the current behavior of Cook on Mesos.
> Separate k8s job pods' workdir and sandbox

- integration/tests/cook/test_basic.py
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- add another mount for the sandbox directory using the legacy mesos path
provides backward compatibility for a job that assumes running on mesos
> add mesos sandbox mount

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- adding node anti-affinity for node blocklist labels
To prevent synthetic pods from running on nodes with blocklist labels. For example, if there is a node labeled as "unhealthy", we don't want synthetic pods to run there, because the real job pods won't be able to.
> Adds node anti-affinity for node blocklist labels

- cli/cook/querying.py
- cli/cook/subcommands/cat.py
- cli/cook/subcommands/ls.py
- cli/cook/subcommands/ssh.py
- cli/cook/subcommands/tail.py
- change cs cli commands to leverage kubectl
the cs cli commands rely on Mesos APIs. kubectl can be used to implement the same functionality on Kubernetes
> support cs cli commands on kubernetes

- integration/tests/cook/test_basic.py
Remove sandbox workaround in test_workdir_volume_overlap
As per the comment in the deleted code:
Now that the sandbox and workdir are separated, this workaround is no longer needed.
> Remove sandbox workaround in test_workdir_volume_overlap

- integration/tests/cook/util.py
- scheduler/config-k8s.edn
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
Capture stdout and stderr in our default Cook-K8s shell for launching job commands.
Fixes test_command_length_limit, which was broken by the io_redirect
wrapper in our integration support code. Since the default shell now
does the capture, we no longer need to augment the job command for
integration tests that depend on the stdout and stderr files.
> Capture stdout/stderr by default on K8s

- scheduler/src/cook/kubernetes/api.clj
- add writable scratch space separate from the sandbox
we want to preserve the sandbox and /tmp directories when checkpointing a job, but we also need to be able to place checkpointing binaries in a writable directory.
> add writable scratch space separate from the sandbox

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
This is bug-fix followup from PR #1483.
- instead of defining multiple `NodeSelectorTerm`s (one for reach requirement), put them all into a single `NodeSelectorTerm`
https://github.com/kubernetes/kubernetes/pull/70394#issuecomment-434127780
The terms have OR semantics between them. We want AND semantics, so that e.g. all blocklist labels are removed before the synthetic pod will run.
> Makes synthetic pod anti-affinity use AND across requirements

- .travis.yml
- cli/cook/dateparser.py
- cli/cook/http.py
- cli/pytest.ini
- cli/setup.py
- cli/tests/subcommands/test_dateparser.py
- cli/tests/subcommands/test_querying.py
- cli/travis/setup.sh
- Switched to pytest to get rid of warnings from nose
- Changed strings to raw strings in dateparser module to fix warnings about `\d` escape sequence
- Moved "show" tests to "querying" since the command it was checking lives in that module now
- Include CLI tests in the Travis unit tests job
We want to run our `dateparser` unit tests to work without errors or warnings.
> CLI: fix broken unit tests and warnings

- scheduler/Dockerfile
Remove dependency on docker apt to build Cook image
The Docker APT repo has been deleted. The current version hits the following URL when trying to do an `apt update`, and it returns the following error message.
https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages
>**Notice: Shutting down dockerproject.org APT and YUM repos 2020-03-31**
>
>Docker will be shutting down the deprecated APT and YUM repositories hosted at  "dockerproject.org" and "dockerproject.com" on the 31st of March 2020.
>
>We noticed that this project is referencing one of these repositories, and recommend updating to use the "download.docker.com" repository to prevent disruption.
>
>More info: https://www.docker.com/blog/changes-dockerproject-org-apt-yum-repositories/
> Remove dependency on docker apt to build Cook image

- scheduler/Dockerfile
- Copy the config files into docker after we do lein build
- Faster docker file generations. Changing the config no longer requires lein uberjar.
> Make config changes more lightweight and not need lein uberjar

- scheduler/config-k8s.edn
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- The readiness probe endpoint is now configurable and optional.
- When the option is omitted, we don't set an explicit readiness probe.
If the file-server is disabled, then the http readiness probe breaks, and the sidecar container is never considered ready. This can cause a lot of error-noise when looking at pod statuses across a cook k8s cluster.
> Make k8s sidecar readiness probe optional

- cli/setup.py
- cli/travis/setup.sh
- integration/requirements.txt
- Update our python-dateutil dependency to latest stable (2.8.1).
- Update the pattern for CLI test dependencies to allow versions (not just names).
The CLI unit tests rely on an attribute introduced in v2.7.0, but our integration tests were explicitly pulling an old version, and that was causing problems because the Python dependencies are cached across multiple jobs.
> Require dateutil v2.8.1 for CLI tests

- integration/tests/cook/cli.py
Add environment variable for configuring adapters module for the CLI integration tests.
We shouldn't assume that the sessions module and the adapters module are the same.
> Make cli integration adapters module configurable

- integration/tests/cook/test_basic.py
- scheduler/docs/scheduler-rest-api.adoc
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/schema.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/rest/api.clj
- add checkpoint field to job
The checkpoint field will contain configuration to facilitate checkpointing in a job running on kubernetes with a custom shell that supports it. Useful when running on preemptable compute
> Add checkpoint field

- scheduler/bin/help-make-cluster
- setting `--min-nodes=0`
- updating the GKE version
- adding a test label to the node pools
We want min nodes to be 0 so that we scale down to 0 when we're not using the clusters.
> Sets min-nodes to 0 when creating test GKE clusters

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- deleting the code introduced in PRs #1483 and #1493 that adds on synthetic pods node anti-affinity to nodes with blocklist labels 
This is not interacting with the Cluster Autoscaler in the way we expected it would.
> Removes blocklisted node anti-affinity

- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
This is a bug-fix follow-up to PR #1489.
- in `synthesize-state-and-process-pod-if-changed`, allowing the pod to be `nil` (meaning that it doesn't currently exist in k8s) instead of throwing a NPE
To avoid this NPE when the pod doesn't exist in k8s during task scanning:
```
java.lang.NullPointerException: null
at cook.kubernetes.api$V1Pod__GT_name.invokeStatic (api.clj:766)
cook.kubernetes.api$V1Pod__GT_name.invoke (api.clj:763)
cook.kubernetes.controller$synthesize_state_and_process_pod_if_changed.invokeStatic (controller.clj:550)
cook.kubernetes.controller$synthesize_state_and_process_pod_if_changed.invoke (controller.clj:546)
cook.kubernetes.controller$scan_process$fn__37882$fn__37883.invoke (controller.clj:629)
cook.kubernetes.controller.proxy$java.lang.Object$Callable$7da976d4.call …
```
> Gracefully handles missing pod in k8s task scanning

- scheduler/src/cook/kubernetes/api.clj
- set main container envs on init container
The init container needs to be able to adjust what it does based on the main container configuration
> set main container envs on init container

- integration/tests/cook/conftest.py
- integration/tests/cook/util.py
- Make `COOK_SWITCH_USER_SSH_HOST` configurable.
- Enable multi-user tests with running with `pytest -n0` by defaulting worker-name value.
- Switch to proper requests library auth object implementation.
- Fetch multi-user credentials based on the target url.
I ran into several issues trying to run a single multi-user test with `pytest -n0`. These changes fix those issues. Specifically the switch to a proper auth object eliminates the need for the renewer Timer task, which was causing pytest to hang on "thread join" after all tests completed. This change also makes it safe to nest the KerberosUser context (although I don't know why you'd want to do that), whereas previously the asynchronous refresh made nesting illegal.
Fetching credentials based on the target url also fixes the flaky test …
> Improve integration test behavior when run single-process

- integration/tests/cook/test_basic.py
Mark flaky integration test `test_output_url` as `xfail`.
The output url api is flaky, even on Mesos.
> Mark flaky test_output_url as xfail

- cli/cook/mesos.py
- cli/cook/subcommands/cat.py
- cli/cook/subcommands/ls.py
- cli/cook/subcommands/tail.py
- don't connect to kubernetes on finished instance
cs file commands like cat shouldn't try to connect to kubernetes when the instance has stopped running
> Don't connect to kubernetes on finished instance

- cli/cook/version.py
- CLI release version 3.0.0
- Major version changed because the plugins refactor is not backwards compatible
Pushing to pypi
> CLI release 3.0.0

- cli/cook/subcommands/wait.py
- Change default check time for cs wait to 15 seconds.
Real jobs run much longer than 5 seconds. This reduces load on the
server by 3x and makes it less likely users hit API rate limits.
> Change default check time for cs wait to 15 seconds.

- scheduler/src/cook/components.clj
- Make it so that we can see who is rate limited in our HTTP log.
Because of the order we inform Jetty of the logged in user, our access.log doesn't tell us who was rate limited.
> Make it so that we can see who is rate limited in our HTTP log.

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- moving the `autoscale!` timer from `scheduler` to the KCC and renaming it
- renaming `synthetic-pod-submit-rate` -> `cc-synthetic-pod-submit-rate`
- adding a timer specifically around the `launch-tasks` call in `autoscale!`
To be consistent with the other KCC metrics, and to have better autoscaling metrics.
> Improves k8s autoscaling metrics

- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- introducing config field `:set-container-cpu-limit?`, which defaults to `true` (for backwards compatibility)
- if set to `false`, we don't set the cpu limit on the job container
To allow pods to get the [Burstable QoS](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-burstable).
> Allows removing cpu limit in k8s

- cli/cook/subcommands/submit.py
- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- Change output of errors from cs submit from stdout to stderr
If we have an error, we want it printed to stderr to maximize the changes it is seen by users instead of gobbled by a stdout redirection.
> Change output of errors from cs submit from stdout to stderr

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/config-composite.edn
- scheduler/config-k8s.edn
- scheduler/src/cook/config.clj
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- Support for specifying the default container on a per-pool basis.
User convenience. We can specify a default docker image that works for the majority of cases.
> Support for specifying the default container on a per-pool basis

- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- avoiding call to `write-status-to-datomic` for synthetic pods (just like we already do in `handle-pod-submission-failed`, `handle-pod-completed`, etc.)
We don't store synthetic pod info in Datomic. This is causing exceptions to get thrown.
> Avoids synthetic pods in handle-pod-preemption

- scheduler/src/cook/kubernetes/compute_cluster.clj
- reply on a google metadata server when a google-credentials file is not provided
support more ways to authenticate
> Use google metadata server

- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/config.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- scheduler/test/cook/test/rest/api.clj
- adding configuration field `:kubernetes :controller-lock-num-shards`
- creating the corresponding number of lock objects
- introducing `with-process-lock`, a macro that captures the timers and locking logic for anything that makes a call to `process`
We want to introduce parallelism for pod submission API calls, and this is a prerequisite. Without this, any parallelism will get bottle-necked on the current single lock acquisition.
> Adds lock-sharding to k8s controller

- scheduler/config-k8s.edn
- Update the log config to match the rename done a few months ago and align with config-k8s.edn
Consistency between our environments. Make sure that we continue to run the command line length integration test.
> Bring config-k8s up-to-date with mesos config.

- scheduler/config-composite.edn
- Make composite.edn config work with synthetic pods, now that the help-make-cluster script creates clusters that have to have thta support.
- Refresh it with other updates that were made to config-k8s.edn that weren't copied here.
Config doesn't work without these changes.
> Fix config-composite.edn so that we can run tests again.

- scheduler/bin/help-make-cluster
- Change the version number in the script to one that GKE currently supports.
Doesn't work without this change.
> help-make-cluster script uses now unavailable gke k8s version.

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- allowing k8s pods to be launched in parallel with a configurable amount of parallelism per compute cluster
We want to be able to launch pods at a higher rate.
> Launches k8s tasks in parallel

- scheduler/src/cook/kubernetes/api.clj
- avoiding NPE when pod metadata is nil, instead throwing an exception with the string representation of the pod in question
We've seen this happen in the wild, and this will help us track down the reason for the pods with no metadata.
> Avoids NPE when pod metadata is nil

- scheduler/java/com/twosigma/cook/kubernetes/WatchHelper.java
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- adding an event watch
- logging pod events where the involved object is a Cook Scheduler pod
For better troubleshooting. This makes troubleshooting certain types of issues, like "Container initialization timed out" failures, much faster.
```
$ grep 20050622-2856-4c67-be39-0c5dfb84953b log/cook-12321.log | grep "received pod event"
2020-05-06 22:27:07,750 INFO  cook.kubernetes.api [pool-11-thread-5] - In gke-2 compute cluster, received pod event {:event-reason FailedScheduling, :event {"apiVersion":"v1","count":1,"firstTimestamp":"2020-05-06T22:27:07.000-05:00","involvedObject":{"apiVersion":"v1","kind":"Pod","name":"synthetic-k8s-alpha-20050622-2856-4c67-be39-0c5dfb84953b","namespace":"cook","resourceVersion":"15004316","uid":"4fc861eb-09b1-4fc4-b78a-14eaccf5b3e3"},"kind":"Event","lastTi …
```
> Logs pod events

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
This is a follow-up PR to #1529.
Sending all matches for a given compute cluster to `launch-tasks` in a single call instead of making one call per match.
For example, let's say our matches are:
```
[{:task-metadata-seq [t1 t2] ...} ; k8s compute cluster A
{:task-metadata-seq [t3 t4] ...} ; k8s compute cluster A
{:task-metadata-seq [t5 t6] ...} ; k8s compute cluster B
{:task-metadata-seq [t7 t8] ...} ; k8s compute cluster B
{:task-metadata-seq [t9] ...}]   ; k8s compute cluster B
```
Previously, this would result in 5 calls to `launch-tasks`, one for each match in the above collection.
Now, this will result in 2 calls to `launch-tasks`, one for `A`:
```
[{:task-metadata-seq [t1 t2] ...}  ; k8s compute cluster A
{:task-metadata-seq [t3 t4] ...}] ; k8s compute cluster A
```
and one for `B`: …
> Sends matches to launch-tasks in bulk

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- adding the `cluster-autoscaler.kubernetes.io/safe-to-evict` annotation to synthetic pods
This pod annotation signals to the cluster autoscaler that it's safe to remove the node on which the pod is running:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node
Without this, a node that's running only synthetic pods (e.g. for some reason, real jobs pods aren't getting matched to it) won't get removed, which is not what we want.
> Adds safe-to-evict annotation to synthetic pods

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- add option to not checkpoint after some number of job attempts have failed
Checkpointing itself can cause failure. This will allow a job to complete
> Don't checkpoint when max attempts exceeded

- scheduler/docs/reason-code
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- check preemption pod label instead of assuming running to missing transition implies preemption
We can tell the difference between a node just disappearing or getting killed vs being preempted, which is expected on preemptable machines
> Check for preemption using preemption pod label

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- `assertEquals` -> `assertEqual` in a couple spots
- marking `test_mesos_containerizer_image_support` as `skip`
`assertEquals` is deprecated.
`test_mesos_containerizer_image_support` fails on minimesos and the mesos containerizer for running docker containers is not used in the wild.
> Skips test_mesos_containerizer_image_support

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- if there are 0 considerable jobs and all offers are destined to get rejected after the match attempt (i.e. they came from k8s), skipping the matching iteration
We've observed the `match-offer-to-schedule` function take several seconds for k8s pools when there are 0 pending jobs. Mesos offers are retained by Fenzo for a certain amount of time, but k8s offers are immediately rejected after the match attempt, since the k8s offer generation generates a complete set of offers for each cycle. That means we can skip matching for k8s when we have no pending jobs to match against.
> Skips match when there are no considerable jobs

- scheduler/src/cook/kubernetes/controller.clj
- log pod metadata
our state calculation is also a function of the pod metadata. we should log it
> log pod metadata

- integration/tests/cook/test_basic.py
- re-enbable test_kubernetes_checkpointing
should work after MR 567
> re-enbable test_kubernetes_checkpointing

- .gitignore
- README.md
- Vagrantfile
- scheduler/bin/bootstrap
- scheduler/bin/help-delete-temporary-clusters
- scheduler/bin/help-make-cluster
- scheduler/bin/make-gke-test-clusters
- scheduler/bin/run-local-kubernetes.sh
- scheduler/config-k8s.edn
- adding Vagrant support that automates dev environment setup (I've tested this from Ubuntu 18.04 and from Macos)
- adding a new Quickstart section to the README with instructions
- making the GKE creation/deletion scripts support separate "owners" in a single GCP project
To make dev environment setup for new devs easier, and to allow multiple devs to share a single GCP project without stepping on each other's toes.
> Automates GKE dev environment setup

- scheduler/java/com/twosigma/cook/kubernetes/WatchHelper.java
- scheduler/project.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- upgrading the k8s java client library from 4.0.0 to 7.0.0
- fixing breaking changes
- adding a unit test which would have caught a breaking change faster
We're targeting k8s 1.16, and version 4.0.0 of the client library was meant to match with 1.12.
https://github.com/kubernetes-client/java/#compatibility
> Upgrades k8s client library to 7.0.0

- scheduler/src/cook/kubernetes/api.clj
- respect set-container-cpu-limit? in sidecar
Sidecar cpu is usually set low, but it also can't burst. We've allowed main container to burst but haven't done so for the sidecar
> don't set cpu limit on sidecar if not setting on main container

- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- respecting `COOK_TEST_DEFAULT_SUBMIT_POOL` in CLI tests
- marking 3 CLI tests as skip-on-k8s
These changes allow us to run the CLI integration tests against k8s by specifically targeting k8s Cook pools (i.e. setting `COOK_TEST_DEFAULT_SUBMIT_POOL` to a k8s Cook pool).
> Supports running the CLI integration tests against k8s

- Vagrantfile
- scheduler/bin/bootstrap
- moving the python bootstrapping to the non-root section of the vagrant setup
When it was running as root, making changes to the python environment (e.g. the python CLI) was not possible as non-root.
> Makes vagrant python bootstrapping not run as root

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- preempted pod label will not change pod state
Do not use :missing state for preempted pod. Preempted pod is still alive until a new instance is created.
> Do not use :missing state for preempted pod.

- integration/tests/cook/test_basic.py
- giving the job 5 attempts instead of just 1
So that transient instance failures don't cause the test to fail.
> Makes test_basic_submit more reliable

- integration/tests/cook/util.py
- adding `lru_cache` to `util.settings`
To avoid making repeated calls to `/settings` for the same Cook Scheduler.
> Adds lru_cache to util.settings

- scheduler/src/cook/kubernetes/api.clj
- make checkpointing mount writeable
- add more checkpointing fallback reasons
need extra flexibility for checkpointing mounts
max-runtime-exceeded straggler failures could be caused by process stuck on a checkpoint restore. so add these to fallback reasons
> update checkpointing settings

- jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java
This is a follow-up to PR #697.
- adding impersonation support to the jobclient query requests
So that request rate-limiting is applied to the impersonated user instead of the impersonating user. The user on whose behalf the query request is being made should be "charged" for the request. This is already happening for writes (e.g. job submit) from #697, and this PR does the same for reads.
> Adds impersonation to query requests

- jobclient/src/main/java/com/twosigma/cook/jobclient/Instance.java
- adding instance reason string to the `Instance` class
So that clients can access the reason string along with the other instance data.
> Adds reason string to Instance in jobclient

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
-  Remove an expensive O(n**2) in k8s offer calculation.
The former node-schedulable? computation was O(#pods) and was invoked
O(#nodes times). Instead we group-by once at the top level and pass that
down so that now O(#pods) is an O(1) calculation.
> Fix an O(n**2) calculation in computing k8s offers.

- jobclient/python/setup.py
- Rename the Python client API from `cookclient` to `cook-client-api`
- The actual module name is still `cookclient`
Match the convention of Cook's existing pip projects
> Rename package from cookclient to cook-client-api

- .travis.yml
- scheduler/travis/setup.sh
- replacing tab characters with spaces
Travis builds are not working because they can't parse the yaml:
(https://travis-ci.org/github/twosigma/Cook/requests)
> Fixes whitespace bug in .travis.yml

- integration/tests/cook/test_multi_user.py
- scheduler/src/cook/scheduler/scheduler.clj
- split signal from match-trigger-chan per pool
Every pool will get its own chime to do matching instead of randomly getting to match by winning the race to listen on a single chime
> Make separate matching chime per pool

- scheduler/docs/groups.md
- removing the `json` annotation from the code blocks in groups.md
When the markup is rendered, the `...` is showing up in bright red because it's not valid json.
> Removes json annotation from groups.md

- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/tools.clj
- Refactor some redundant code for matching pools against a list of regexps.
Remove redundant code that will be used a third time.
> Refactor out common method for matching regexps against a pool name.

- integration/tests/cook/util.py
- add kill instance method
enhance checkpointing testing by adding functionality like kill instance to simulate preemption
> add kill instance test helper method

- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/tools.clj
- filtering pending jobs based on quota before calling `trigger-autoscaling!`
So that we don't trigger autoscaling beyond what users have quota to actually run.
> Avoids autoscaling beyond what users have quota to run

- integration/tests/cook/test_cli.py
- Disable a broken test.
- Its preventing releases.
> Disable buggy test_jobs_exclude_custom_executor test.

- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/mesos/mesos_mock.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- scheduler/test/cook/test/zz_simulator.clj
- match pools in round-robin order
- add configurable match interval
right now pools match all at the same time on every matching tick. this causes a thundering herd problem
> match pools in round-robin order

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Fix bug where we try to calculate consumption for pods that don't have a node.
- Do some more filtering to keep wrong-pool nodes from being injected into consumption processing.
Avoid thousands of "unable to get node from node name" ERROR logged.
> Fix "unable to get node from node name XXXX" errors.

- scheduler/src/cook/kubernetes/compute_cluster.clj
- skip looking for offers for non-k8s pools in k8s cluster
Don't get bogged down trying to find offers for pools that can't be scheduled
> skip non-k8s pools in k8s cluster

- README.md
- adding a step to the Quickstart to seed Cook pools in the database
The pools have to be there in the database or Cook won't start up.
> Adds seeding Cook pools to the README

- scheduler/CHANGELOG.md
- "blacklist" -> "blocklist"
- "whitelist" -> "allowlist"
To avoid language that is exclusive, offensive, or carries negative historical connotations.
> Corrects some problematic language

- jobclient/python/docs/source/conf.py
- jobclient/python/requirements.txt
- Explicitly set `master_doc` in the documentation's `conf.py` file
- Set up a `requirements.txt` file including `requests` as well as the versions of `sphinx` and `sphinx-rtd-theme` the documentation has been tested with.
We want to publish the Python job client's documentation to readthedocs.io; however, they appear to be using an older version of Sphinx which expects the documentation's root document to be `contents.rst` instead of `index.rst`.
We explicitly set `master_doc` to `index` in the documentation's `conf.py` file, which Sphinx will then pick up as the master doc. Additionally, we specify the versions of `sphinx` and `sphinx-rtd-theme` we use in `requirements.txt` so as to minimize any future headaches involving these configurations.
> Fix Python job client docs for readthedocs

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/bin/help-make-cluster
- scheduler/config-composite.edn
- scheduler/datomic/data/seed_k8s_pools.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/tools.clj
- Support config-based global quotas for a pool
With cloud autoscaling, cook has no limits on autoscaling within cook, only in the underlying k8s cluster. To add more refined control, allow Cook to have specific autoscaling limits.
> Support config-based global quotas for a pool

- cli/cook/subcommands/show.py
- replacing "Slave" with "Agent" in the `cs show <instance-uuid>` output
To avoid language that is exclusive, offensive, or carries negative historical connotations.
> Replaces "Slave" with "Agent" in cs show output

- scheduler/src/cook/scheduler/constraints.clj
- scheduler/test/cook/test/scheduler/constraints.clj
- Modify GPU host constraint to only allow one GPU task per VM
- Added unit test for this special case
- Brian Bao noticed that when he submitted multiple GPU jobs rapidly in succession, they sometimes got matched to the same VM because the GPU constraint was not accounting for tasks that were already assigned to that VM.
> One GPU task per VM

- integration/tests/cook/test_client.py
- Remove test_gpu_submit_c2
- There is already test_gpu_submit_c1 that asserts if there is 1 GPU of the correct model on the VM.
- test_gpu_submit_c2 is frequently the slowest test out of all the integration tests.
- It is highly unlikely that test_gpu_submit_c1 will pass and test_gpu_submit_2 would not pass. We have also done extensive manual testing that has shown GPU jobs are working as expected.
> Remove integration test for 2 GPUs

- cli/cook/version.py
- bumping CLI version to 3.1.0
To publish the new version to pypi.
> Updates CLI version to 3.1.0

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- filtering out `nil` values before summing in `total-resource`
Otherwise, `total-resource` throws a NPE when, for example, a node has no pods running on it.
> Gracefully handles missing resource in total-resource

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/test_client.py
- scheduler/src/cook/kubernetes/api.clj
- using 1024^2 (MiB) as the k8s memory multiplier instead of 1000^2 (MB)
Cook, Fenzo, and Mesos use mebibytes (MiB) for memory, so we need to convert bytes from k8s to MiB when passing to Fenzo, and MiB back to bytes when submitting to k8s.
> Uses 1024*1024 as the k8s memory multiplier

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- adding `workload-class`, `workload-id`, and `resource-owner` labels to synthetic pods
So that synthetic pods can be properly attributed.
> Adds attribution labels to synthetic pods

- integration/tests/conftest.py
- adding `compute-cluster-type` and `url` to the test metrics entries
It's useful to distinguish Mesos from Kubernetes test runs, and runs against different URLs.
> Adds compute-cluster-type and url to test metrics

- integration/tests/cook/test_basic.py
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- adding `agent_id` on job instances as a preferred alternative to `slave_id`, with the same value
As a first step to avoiding language that is exclusive, offensive, or carries negative historical connotations.
> Adds agent_id as preferred alternative to slave_id

- integration/tests/cook/test_client.py
- jobclient/python/cookclient/__init__.py
- jobclient/python/cookclient/util.py
- Fix the Python client so that submitting a job with `None` explicitly set on certain parameters no longer causes a `NoneError`
The following code snippet:
```python
client = JobClient(COOK_URL)
client.submit_all([{'command': 'ls', 'container': None}])
```
will incorrectly cause a `NoneError`. This is because since the `container` key is explicitly set in the jobspec, the client erroneously assumes it is not `None` and attempts to call `jobspec['container'].to_dict()`. This patch fixes this issue.
> Allow explicit `None` in JobClient.submit_all

- scheduler/src/cook/scheduler/scheduler.clj
- making the log line be INFO instead of WARN
- destructuring the `task`
This will get logged anytime a user kills a job instance, so WARN level is not warranted.
> Makes "killing cancelled task" log be INFO

- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- check for preemption label when pod goes missing during initialization
If a pod is preempted during initialization we currently show it as "Command exited non-zero" but we need to show it as  "Agent removed"
> handle preemption on pod initialization

- integration/tests/cook/test_basic.py
- running the test for 1 pool instead of 2
This is our 4th longest running non-`xfail` test over the last 30 days, taking an average of ~125 seconds, and there's no reason it should take this long.
> Runs only one pool in test_list_jobs_by_pool

- scheduler/config-k8s.edn
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/rest/api.clj
- adding optional `:add-job-label-to-pod-prefix` configuration option
- when the option is set, adding any job labels with the configured prefix as pod labels
To allow upstream platforms to specify job labels that dictate behavior in k8s, e.g. the need to have a particular persistent disk attached.
> Allows prefixed job labels to become k8s pod labels

- scheduler/src/cook/scheduler/scheduler.clj
- adding a log at the start and end of pending job ranking
To be able to correlate the ranking and matching cycles in the logs.
> Logs at start and end of job ranking

- scheduler/src/cook/scheduler/scheduler.clj
- only logging when the rate-limit count is > 0
- adding more data to the log
Example:
```
2020-08-16 18:19:28,444 INFO  cook.scheduler.scheduler [async-thread-macro-12] - In k8s-alpha pool, job launch rate-limiting {:count-considerable-jobs 1, :enforcing-job-launch-rate-limit? true, :num-considerable 1000, :total-rate-limit-count 15, :user->number-jobs {vagrant 16}, :user->rate-limit-count {vagrant 15}}
```
We don't need to spam the log with this line when the count is 0. When we do log it, having more data can be useful for troubleshooting issues.
> Improves per-user launch-rate-limit logging

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
Adding the following to the "matching offers to considerable jobs" log:
- total amount offered by resource
- total amount requested by considerable jobs by resource
- total number of considerable jobs per user
Example log:
```
2020-08-17 02:23:26,290 INFO  cook.scheduler.scheduler [async-thread-macro-8] - In k8s-alpha pool, matching offers to considerable jobs {:count-considerable-jobs 7, :count-offers 3, :resource-type->total-considerable {:cpus 3.500, :mem 224.000}, :resource-type->total-offered {mem 2238.203, cpus 0.878, disk 0.000}, :user->number-jobs {vagrant 7}}
```
To get a better sense of the data going into each matching round, especially when troubleshooting issues.
> Improves matching log

- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- extracting a function for the set of Liberator resource attribute functions needed for redirecting to the leader
- adding the `/shutdown-leader` endpoint, which redirects to the leader and exits on the leader
In a multi-node cluster, it's useful to be able to force a leadership election by causing the current leader to relinquish leadership. We don't currently have a clean path for relinquishing leadership other than simply exiting.
> Adds /shutdown-leader API endpoint

- scheduler/src/cook/kubernetes/compute_cluster.clj
- Switch to using a different API to parse .kube/config files. 
Make it easier to directly decide which context out of the config we should be running.
> New API for reading kubectl file

- scheduler/src/cook/scheduler/constraints.clj
- Un-lazy the lost of hosts a job has already run on as a perf optimization.
When diagnosing a production problem, I noticed a lot of of threads blocked on unlazy'ing this list.
> Un-lazy list of hosts a job has run on as a perf optimization

- scheduler/src/cook/scheduler/constraints.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
Use `set` instead of `mapv`->`distinct`
After discussion, using a `set` will reduce lock contention when reading already realized `lazy-seq`
> Use set instead of distinct

- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/tools.clj
- Reverse order of quota application
Applying quotas in the wrong order can also cause us to not launch
jobs that are within quota. A user who's already at their quota will
appear to falsely use global quota that they can't really use.
> Reverse order of quota application

- scheduler/src/cook/scheduler/scheduler.clj
- Unlazy another argument to Fenzo.
Avoid and reduce lock contention and make nicer profiles.
> De-lazy the list of constraints to avoid locking in Fenzo.

- cli/cook/subcommands/admin.py
- cli/cook/subcommands/jobs.py
- cli/cook/util.py
Adding `cs admin instances`, which lets administrators get the number of instances in a specific state and time window, via `/stats/instances`.
We want to be able to easily check (for example) that the number of failed instances in a cluster over the last X minutes has not exceeded a threshold.
> Adds cs admin instances

- scheduler/bin/help-make-cluster
- scheduler/config-k8s.edn
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/scheduler/constraints.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/scheduler/constraints.clj
- adding two new node pools (e2-small) in `help-make-cluster`
- adding support for default job constraints by pool (regex)
- translating EQUALS constraints to node selectors
- mapping all k8s node labels to offer attributes so they can be referenced by constraints
We want to allow users to experiment with different machine types in k8s, and this change allows users to use the existing job constraint mechanism to specify (for example) the machine type they want to use. Note that there's nothing specific here to machine types -- this allows any k8s node label to be selected.
> Adds support for EQUALS constraints in k8s

- integration/tests/cook/test_basic.py
- fix missing key error
Missing key error when we attempt to read 'factory-fn' from filtered_compute_clusters in the following code
> Fix dynamic cluster integration tests

- cli/cook/querying.py
- fix use of "next"
Fix StopIteration error when calling "next" on empty list. This happens now if we are looking for a dynamic cluster that's not found in /settings
> Fix StopIteration bug

- cli/cook/version.py
- bumping CLI version to 3.3.0 
To publish the new version to pypi.
> Updates CLI version to 3.3.0

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/task.clj
- scheduler/test/cook/test/compute_cluster.clj
- scheduler/test/cook/test/rest/api.clj
- fix pool-name->fenzo map
- remove sandbox url error for dynamic clusters
These errors were being logged but were not affecting jobs and were not noticed initially
A malformed pool-name->fenzo map was being passed in to write-status-to-datomic
We were attempting to get output_url from non-leader cluster which had no references to dynamic clusters. But we don't actually need a reference to a kubernetes cluster for output_url
> Fix errors when using dynamic clusters

- integration/tests/cook/test_basic.py
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/api.clj
- adding a new configuration field `:kubernetes` `:synthetic-pod-condition-unschedulable-seconds`, which defaults to 900 seconds (15 minutes)
- changing `pod-unschedulable?` to use the same logic for synthetic pods as for non-synthetic pods, just with a different timeout
So that unscheduled synthetic pods don't stay around forever.
> Deletes unschedulable synthetic pods

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/task_stats.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- logging p50, p95, and p100 offer and job size by CPUs and memory when matching
To be able to better troubleshoot matching issues by understanding the "shapes" of jobs and offers from the logs.
> Logs offer and job percentiles

- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Adding convenience methods:
- `addNodeTypeConstraint`
- `addNodeFamilyConstraint`
- `addCpuArchitectureConstraint`
- `addEqualsConstraint`
- `addGpuModelEnv`
To make setting these constraints / environment variable easier for callers.
> Adds helper methods for constraints and GPU model

- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
- checking if the `gpus` field is present instead of assuming it is
Not all jobs have the `gpus` field.
> Correctly parses jobs with no gpus

- scheduler/src/cook/rate_limit.clj
- scheduler/src/cook/rate_limit/generic.clj
- scheduler/src/cook/rate_limit/token_bucket_filter.clj
- scheduler/src/cook/unscheduled.clj
- scheduler/test/cook/test/rate_limit/generic.clj
- scheduler/test/cook/test/unscheduled.clj
- Get rate limit code ready to have per-key configurations.
- Do some refactors to reduce glue code and make the keys easier to manage and move config elsewhere in code. 
Get ready to have per compute-cluster rate limits as well as other rate limits throughout cook.
> Refactor ratelimit code

- scheduler/src/cook/tools.clj
- Make the match-based-on-regexp code more generic.
We want to be able to reuse this code for matching compute clusters too.
> Refactor regexp list matching code.

- integration/tests/cook/test_multi_user.py
- disable compute cluster integration tests
The tests are not ready and are causing errors to be logged
> disable compute cluster integration tests

- scheduler/src/cook/mesos.clj
- scheduler/test/cook/test/mesos.clj
- don't ignore static clusters when checking that there are no missing clusters for known running tasks
current code will incorrectly raise an error when an existing task is running on a static cluster
> fix missing cluster check

- integration/tests/cook/test_basic.py
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/kubernetes/api.clj
- adding 3 new (optional) fields to the job spec's `application` field: `workload-class`, `workload-id`, `workload-details`
- when set, these fields become pod labels on the job pod in k8s
Similar to #1617, but for job pods instead of synthetic pods. This allows for proper attribution of workloads, e.g. when tracking cost.
> Adds workload fields to job application

- .travis.yml
- integration/tests/cook/test_multi_user.py
- integration/travis/run_integration_ratelimit.sh
- integration/travis/scheduler_travis_config.edn
- scheduler/bin/help-make-cluster
- scheduler/config-composite.edn
- scheduler/config-k8s.edn
- scheduler/config.edn
- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/rate_limit.clj
- scheduler/src/cook/rate_limit/generic.clj
- scheduler/src/cook/regexp_tools.clj
- scheduler/src/cook/scheduler/constraints.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/regexp_tools.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- scheduler/test/cook/test/tools.clj
- scheduler/test/cook/test/zz_simulator.clj
- Remove the old global (across all compute clusters) rate limit.
- Repurpose it as a per-compute-cluster rate limit, using regexp's to look for compute clusters matching a pattern.
The global rate limit is to protect the backend. Now that we have separate backends, especially hybrid ones, we don't want them to share the same global rate limit, so now split into separate rate limits.
> Add rate limits per compute cluster.

- scheduler/src/cook/scheduler/constraints.clj
- Extract the job's GPU count requested and GPU model requested into the defrecord so that calculation is not performed multiple times per job 
- Trying to optimize constraint evaluation for Cook
> Optimize GPU constraint

- scheduler/src/cook/components.clj
- scheduler/src/cook/quota.clj
- Remove metatransaction.core import that causes problem with mount.
Avoids an incomprehensible error with mount. Diagnoses #1370 with a workaround.
> Remove metatransaction.core import that causes problem with mount.

- scheduler/src/cook/queries.clj
- scheduler/src/cook/quota.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/scheduler/share.clj
- Remove circular dependency by moving a first query out of cook.tools.
Cook tools depends on a lot of cook code, so that depending on it can accidently introduce circular dependencies. Much of the code there is database queries. If we move this to a new file, then we can break the circular dependencies.
> Remove circular dependency by moving a query out of cook.tools

- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/tools.clj
- Refactor to propagate pool-name into quota filters.
No functionality change except to add an extra field to a debug log line, but this enables future changes where we want the quota filter to be pool specific.
> Refactor to propagate pool-name into quota filters.

- scheduler/src/cook/rate_limit.clj
- scheduler/src/cook/rate_limit/generic.clj
- scheduler/test/cook/test/rate_limit/generic.clj
- Add the ability to flush a ratelimit from the cache so it gets reloaded.
We want to be able to update ratelimits dynamically.
> Add the ability to flush a rate-limit from the cache

- cli/cook/subcommands/ssh.py
- cli/cook/version.py
- adding an optional command argument, e.g. `cs ssh $uuid ls -al`
So that users can run an arbitrary command on the remote machine and then return.
> Adds optional command to cs ssh

- scheduler/src/cook/config.clj
- scheduler/src/cook/scheduler/scheduler.clj
Logging a warning when a high (configurable) percentage of considerable jobs have gone unmatched for more than a configurable number of consecutive match cycles.
To help alert us to situations where job scheduling is not working as expected.
> Warns when jobs are unmatched for too long

- scheduler/src/cook/compute_cluster.clj
- For API requests that are wrong should be reported as WARN's, not ERROR's. 
Avoid ERROR's during integration test runs.
> Change log from ERROR to WARN

- integration/tests/cook/test_basic.py
- Make this test run only if the image is docker --- not just if cook is in docker.
This test only makes sense to run within a public cloud mesos environment
that uses docker.
> We need an actual UID for test_docker_port_mapping to run.

- scheduler/bin/run-docker.sh
- Fixes:
test_compute_cluster_api_delete_invalid
test_compute_cluster_api_create_invalid
Having our tests pass in open source.
> Fix compute-cluster API tests when run in docker.

- scheduler/config-k8s.edn
- scheduler/src/cook/config.clj
- introducing `:rate-limit` `:auth-bypass-limit-per-m` (defaults to 10,000)
- using this different limit for requests that bypass authentication
We don't want full Kerberos authentication on the progress update requests (`/progress/<uuid>`) to avoid crippling the leader from many progress update requests at the same time. See issue #1367 for the plan to add lightweight authentication.
In the meantime, the issue with bypassing authentication is that all of the progress update requests are being treated as though they were coming from a single user for rate-limiting purposes, which is problematic. This PR allows us to set a different (higher) limit for auth-bypass requests.
> Adds different rate limit for auth-bypass requests

- scheduler/src/cook/config.clj
- scheduler/test/cook/test/config.clj
Lowering the default request rate limit for auth-bypass requests to 600 / minute.
To have a more conservative default.
> Lowers default auth-bypass request rate limit

- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/tools.clj
- Enable tracking of whenever we rate limit.
- Indicate when we are updating the backing data for /unscheduled (and a sense as to what the changes are) 
- 
Track down the consequences of the (expected) race where /unscheduled is showing what we expect. That endpoint is inherently racy, but we think the race is behaving worse than we expected.
> Enable tracking of how rate limiting is affecting the queue.

- scheduler/src/cook/caches.clj
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/plugins/launch.clj
- scheduler/src/cook/plugins/submission.clj
- scheduler/src/cook/scheduler/data_locality.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/rest/api.clj
- scheduler/test/cook/test/scheduler/constraints.clj
- scheduler/test/cook/test/scheduler/data_locality.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Make our cache sizes configurable from the configuration file, so they can be sized to an expected working set size.
- Better handling with longer queues and reduce the risk of hitting a performance cliff.
> Make our cache sizes configurable from the configuration file.

- integration/tests/cook/test_cli.py
- scheduler/src/cook/compute_cluster.clj
- removing the `:ca-cert` from the cluster configs when logging them
The log can get huge (> 80kb), which can cause problems with logstash, and the ca-cert makes the log hard to read.
> Shortens the 'updating dynamic clusters' log

- scheduler/src/cook/caches.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/kubernetes/api.clj
- adding a cache from user -> group ids
- populating the cache when needed with `id -G`
- setting the supplemental groups in the pod security context
So that the pod runs with the proper group membership for the user.
> Sets supplemental groups in the pod security context

- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Group.java
- jobclient/java/src/test/java/com/twosigma/cook/jobclient/GroupTest.java
- removing job group name validation from the Java client library
The client is validating group names, but these are not currently enforced at the Cook Scheduler level, which is inconsistent and can cause problems when reading job groups created by other clients.
> Removes group name validation from Java client

- scheduler/src/cook/scheduler/scheduler.clj
- removing the list of hostnames matched from the log
The list of hostnames can get long and is not very useful. This log line can get > 9k, which can cause problems for logstash.
> Shortens the 'launching matched tasks' log

- scheduler/src/cook/kubernetes/api.clj
- not logging the entire job
Depending on the job, this log can get very long (> 22k), which can cause problems for logstash.
> Shortens the 'Will not checkpoint' log

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/tools.clj
- adding `try` / `catch` to `offers->stats` and `jobs->stats`
- ignoring unknown resource types in `job-ent->resources`
If a new resource type is added to jobs in the database, as with `disk` in PR #1709, we need old code (that is unaware of the new resource type) to not fail when encountering those jobs.
- If we can't collect stats, the whole matching cycle should not error out.
- If there is an unknown resource type, `job-ent->resources` shouldn't throw.
> Gracefully handles unknown job resource type

- scheduler/src/cook/config.clj
- increasing default from 32 to 4095
- increasing max from 255 to 32777
To better support environments with high job volume.
> Increases default and max :controller-lock-num-shards

- scheduler/test/cook/test/config.clj
This is a follow-up PR to #1724.
- fixing the unit test that became broken in PR #1724 
To make the unit test agree with the new maximum number of controller lock shards.
> Fixes test-config-settings

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- We want launches across different pools (in particular across mesos and GKE) to be isolated.
- Add some metrics for lock acquisition time.
- Isolate different pools from impacting each other via this lock.
> Make the kill-lock be a ReentrantReadWriteLock and add metrics.

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
…ontext configurable
- Add configuration knobs to choose which node selector cook puts on its pods.
- Add configuration knobs to choose which taint cook uses to choose its pool name.
- Add configuration knob to select one context out of a kubeconfig file.
Give us  more configurability for how we connect to k8s.
> Refactor to make pool taint / label and context configurable

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Fix a leak where we we would unconditionally write back to the k8s state when the state scanner visited a pod which had been deleted. This ends up leaking.
- Avoids a memory leak.
> Fix memory leak in k8s state for deleted pods

- integration/tests/cook/test_basic.py
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- add metadata env vars
We need access to more metadata like cook URL to get info about past instances, compute cluster name, pool name
> add metadata env vars

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/tools.clj
- scheduler/src/cook/util.clj
- add support for modifying pod image when checkpointing
We want to be able to modify the image spec when checkpointing. We want to be able to translate to a spec that is based on the image ID and is fixed. We need to get the exact same image when restoring even if new builds of the image have been made in the interim.
> add support for modifying pod image when checkpointing

- Vagrantfile
- `$repo_root/jobclient` -> `$repo_root/jobclient/java`
To fix the Vagrantfile with the new location of the Java jobclient.
> Fixes Java jobclient path in Vagrantfile

- cli/cook/subcommands/show.py
- integration/tests/cook/test_cli.py
- scheduler/config-k8s.edn
- Add 'Disk Request', 'Disk Limit', and 'Disk Type' fields to cs show
- Allow users to see disk specs on jobs they submitted
> Add disk fields for cs show

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Cook uses a k8s taint to determine which nodes are in which pool. When extracting the value of that taint, have cook subtract off a prefix and place the node in the pool with that suffix.
- Gives us more flexibility in the taint value we attach to Cook-used nodes.
> Add support for ignoring a taint prefix.

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Do not schedule nodes with unschedulable node-spec
This allows node cordoning to work.
> Do not schedule nodes with unschedulable node-spec

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Let us set a range up to 511 threads.
- Give is more flexibility in tuning how many threads, in particular when we have to handle slow API response times.
> Increase limit for launch-task-num-threads

- scheduler/src/cook/kubernetes/api.clj
- Make the path be an absolute path relative to the workdir
This way the path for coordinating between the job and progress reader works regardless of CWD.
> Make progress an absolute path in k8s

- scheduler/src/cook/kubernetes/api.clj
- When we setup the init container, attach resources to it.
When K8S is run with quotas, any container without attached resources will be rejected at submission. We don't want that, so attach resources to the init container.
> Add resource request and limit to init-container in pod

- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
- Parse a single Job from a `JSONObject`.
- Update `Builder.of(job)` to set constraints and disk.
In Spark we want to allow users to pass a jobspec, `spark.cook.jobspec`, which we'll pass directly down to `Job.parseFromJson` for submission.
> Add ability to parse single Job, update Job -> Builder

- integration/tests/cook/test_basic.py
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- Accept int values for disk request and limit
- Improve user experience since people may want to just specify int values for disk request and limit
> Allow disk request/limit to be an int

- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Disk.java
- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
- Add that disk request and limit are in MiB in the docstrings
- Clarification for users
> Specify that disk request and limit are in MiB

- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
- Add `throws JSONException` to `parseFromJSON`
- Set `status` and `priority` when creating a `Builder` object  from a `Job`.
- Allow users to create a `Builder` object from a `JSONObject`.
Forgot to throw the exception up. Also if you create a Job from a JSON object or vice versa it's incomplete. It makes more sense from an API perspective to allow users to parse JSON -> `Builder`, then be able to make further changes to the builder object. You can't do that with the existing code since Job is effectively immutable after built.
> Add ability to convert JSON->Builder, set fields when JSONizing

- jobclient/java/pom.xml
- scheduler/project.clj
> Updates java jobclient to v0.8.1

- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
- Uses `addLabel`/`addEnv` over `setLabel`/`setEnv`.
Since the `Builder` object is not immutable, when you call `setLabels`, it sets it to an `ImmutableMap`, which prevents the user from being able to call `addLabel` afterwards.
> Use add over set when parsing JSON.

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/schema.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/compute_cluster.clj
- adding a `location` field to the compute cluster
To eventually support constraining job instances to specific locations, e.g. specific cloud regions.
> Adds location to compute cluster

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
If checkpointing is enabled, sending the synthetic pod for a new instance to the same location (e.g. region) as the checkpointed instance.
To take advantage of data locality for the checkpoint data.
This PR only affects synthetic pods, not the actual matching constraint to enforce where the real job pods run. That will come in a subsequent patch.
> Sends synthetic pod to same location as previous checkpoint

- scheduler/java/com/twosigma/cook/kubernetes/TokenRefreshingAuthenticator.java
- scheduler/src/cook/kubernetes/compute_cluster.clj
- Add a workaround for refreshing the k8s authenticator for non-GKE k8s.
- Without this change, the k8s java library fails to refresh the authenticator and we lose k8s connectivity after an hour.
> Set special authenticator refresh logic needed for non-GKE K8s

- cli/cook/querying.py
- cli/cook/subcommands/cat.py
- cli/cook/subcommands/ls.py
- cli/cook/subcommands/ssh.py
- cli/cook/subcommands/tail.py
- cli/cook/version.py
- don't assume kubectl for cat, ls, tail on running job on kubernetes
Make the plugin functions for ls, cat, tail be able to work without using kubectl when on kubernetes
> Refactor cs kubernetes commands

- scheduler/config-k8s.edn
- Add back sidecar memory limit to prevent NPE in open source
- Prevent NPE
> Fix NPE bug for sidecar mem limit

- cli/cook/querying.py
- Fix a bug.
If there are no dynamic compute clustes, we will get a StopIterationException instead of falling through to config-defined clusters, thus breaking cs for those clusters. Fix the that bug with a default None.
> Fix bug where we would fail to check for config-defined compute clusters in cs

- scheduler/java/com/twosigma/cook/kubernetes/WatchHelper.java
- scheduler/project.clj
- scheduler/src/cook/kubernetes/api.clj
- Upgrade kubernetes-java to 11.0.0 to support setHostnameAsFQDN
- setHostnameAsFQDN to false so that we can support longer pod name default paths.
Support longer podname paths.
> Support longer pod names

- scheduler/src/cook/rest/api.clj
- removing the requirement to pass `user` on `/usage` requests
- when `user` is not passed, making `/usage` return usage for all users that have running jobs
It's useful to know usage for all users, e.g. when troubleshooting scheduling issues. The existing `/running` endpoint is not sufficient for this because it returns individual running tasks, and there can be thousands of running tasks on some clusters.
> Allows getting /usage for all users

- integration/tests/cook/test_basic.py
- scheduler/src/cook/config.clj
- scheduler/src/cook/plugins/definitions.clj
- scheduler/src/cook/plugins/demo_plugin.clj
- scheduler/src/cook/plugins/submission.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/jobclient/jobclient.clj
- scheduler/test/cook/test/plugins/submission.clj
- scheduler/test/cook/test/rest/api.clj
Adding a new submission plugin that validates resources across node types.
So that Cook can apply different resource limits based on the node-type, node-family, and cpu-architecture constraints that users can specify.
> Validates job resources by node type

- scheduler/src/cook/util.clj
- scheduler/test/cook/test/util.clj
Logging exceptions in `deep-merge-with`.
Without this, it's not possible to understand which portion of the input maps is causing an exception.
> Logs exceptions in deep-merge-with

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Various changes to enable local kubernetes operation.
- Support for a supplemental group ignore list for k8s.
We need these changes for integration tests to pass in non-GKE environments.
> Enable local k8s

- scheduler/src/cook/config.clj
- scheduler/src/cook/scheduler/scheduler.clj
Before distributing pending jobs to compute clusters for autoscaling purposes, take the top X (where X is configurable and defaults to 1,000).
Distributing jobs to compute clusters can require database lookups, and we shouldn't be doing this on the entire pending queue of jobs, which can grow to tens of thousands of jobs. We already limit the number of synthetic pods we submit in downstream code, so it doesn't make sense to calculate the distribution on the entire queue.
> Takes only top X jobs when triggering autoscaling

- jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
- Pass `decorator down`
My bad.
> cook: pass decorator through to List<Job> parseFromJSON

- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
Making pods that fail and have a `:pod-preempted-timestamp` go down the `handle-pod-preemption` path so that they get the appropriate `Agent removed` failure reason.
Currently, pod failures from node preemption result in the confusing and misleading `Unknown mesos reason`.
> Marks reason correctly for pod failures from preemption

- scheduler/src/cook/caches.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
* Parallel synthetic pod launching across compute clusters
* Launch synthetic pods proportional to queue length
* Don't launch synthetic pods for the same job too frequently
* Parallel synthetic pod launching across compute clusters
* Launch synthetic pods proportional to queue length
* Don't launch synthetic pods for the same job too frequently
Reduce the overheads of autoscaling.
> Numerous autoscaling improvements

- scheduler/src/cook/scheduler/scheduler.clj
- Stop calculating offer attribute map unnecessarily then throw it away.
Faster match performance.
> Stop calculating offer attribute map unnecessarily then throw it away.

- scheduler/src/cook/kubernetes/api.clj
- when looking for cook memory labels, look at all labels, not just pod labels
memory can be controlled by job labels that are not also pod labels
> fix cook memory label handling

- cli/cook/format.py
- cli/cook/subcommands/usage.py
- when converting MiB to bytes, multiplying by (1024 * 1024) instead of (1000 * 1000)
- when displaying formatted memory amounts, using base 2 units (e.g. `GiB`) instead of base 10 units (e.g. `GB`)
- in `cs usage`, changing `Max Quota` -> `Quota` and `Non-preemptible Share` -> `Share`
The memory units are using an incorrect and awkward combination of base 10 and base 2; everything should be base 2, since that's what Cook actually uses internally.
The word `Max` in `Max Quota` is superfluous, and `Non-preemptible` is unhelpful, especially in environments where Cook is not configured to do rebalancer preemption.
> Fixes cs memory formatting

- scheduler/config-k8s.edn
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Have synthetic pods sleep for a while after starting so that the space
cannot be reused for other synthetic pods. 
- In addition, have Cook ignore
the space used by synthetic pods, so that Cook will barge in and take
those resources away.
Improve autoscaling. At present, an empty node can have synthetic pods sequentially match on it, attenuating the autoscaling signal Cook is intending to send.
> Ignores the space used by synthetic pods

- scheduler/src/cook/kubernetes/api.clj
Allowing synthetic pods to have a non-default termination grace period.
So that they can be deleted immediately (grace period = 0) to free up space on nodes for real job pods. The default grace period of 30 seconds can cause real job pods to be deemed unschedulable and fail.
> Allows synthetic pods to have a non-default termination grace period

- jobclient/python/cookclient/__init__.py
- Add support for disable_mea_culpa_retries to python jobclient.submit
We would like to be able to use the disable_mea_culpa_retries param with jobclient.submit, currently it doesn't have all jobspec params enabled.
> Support for disable_mea_culpa_retries on python jobclient.submit

- scheduler/src/cook/kubernetes/api.clj
- Add support for node tenuring taint
This lets us redirect synthetic pods toward the autoscaler instead of having them run on existing old nodes.
> Add support for node tenuring taint

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- change the COOK_MEMORY_REQUEST_BYTES pod environment variable to be the actual pod memory request
> fix memory request value sent to pod

- jobclient/python/cookclient/__init__.py
- Upgrade cook-client-api-version to 0.3.2
- Publish the new version to pypi
> Upgrade cook-client-api-version to 0.3.2

- jobclient/python/cookclient/__init__.py
- Upgrade cook-client-api-version to 0.3.3
Publish the new version to pypi
>  Update cook-client-api version to 0.3.3

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
Allowing (optionally) synthetic pods to have inter-pod anti-affinity to a configurable pod label.
In order to repel synthetic pods from tenured nodes, e.g. by running a "repeller" pod on nodes that have been up and running for a certain amount of time.
> Supports synthetic pod inter-pod anti-affinity

- integration/tests/cook/test_cli.py
- making `test_list_by_state` more reliable
- `cli.wait` -> `util.wait_for_jobs` in a few places
- several formatting-only changes
To make failures less likely and/or easier to diagnose.
> Improves several integration tests

- jobclient/python/cookclient/__init__.py
- Add support for constraints to python jobclient.submit
We would like to be able to use the constraints param with jobclient.submit, currently it doesn't have all jobspec params enabled.
> Add constraints to jobspec.submit, bump version

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- logging a warning instead of causing an exception to be thrown when the watch object is `nil`
In the wild, we occasionally see `nil` watch objects come through the watch.
> Gracefully handles nil watch objects

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
Allowing a namespace to be specified on the synthetic pod anti-affinity.
> because pods are namespaced (and therefore the labels on pods are implicitly namespaced), a label selector over pod labels must specify which namespaces the selector should apply to
(https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity)
> Allows namespace to be added to synthetic pod anti-affinity

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- filtering out nodes with empty or `nil` pods in `get-consumption`
In the wild, we occasionally see nodes at the beginning of their lifetime come through this code path with no pods associated to them. When this happens, an exception is thrown in the offer generation code and no offers are generated.
> Gracefully handles nodes with no pods in get-consumption

- scheduler/src/cook/kubernetes/api.clj
Instead of logging the watch response, which does not have a `toString`, logging the `status` field, which does have a `toString`. Note that we're now logging all fields on the watch response (`object`, `status`, `type`): https://github.com/kubernetes-client/java/blob/fbf46529894c7f189cc5a604716aae50769d2caf/util/src/main/java/io/kubernetes/client/util/Watch.java#L48-L53.
In order to understand the reasons we're seeing `ERROR` type responses on pod watches.
> Logs watch response status field

- scheduler/docs/reason-code
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/kubernetes/api.clj
Similar to PR #1489, but for a different pod condition.
- adding a new failure reason "Container readiness timed out"
- fast-failing jobs using this new reason when they get into the `ContainersNotReady` condition for a prolonged (configurable) amount of time
Without this, pods can remain in the `ContainersNotReady` state forever, and their jobs stay in the `Running` state forever, despite not actually having started running the user's workload.
> Treats prolonged ContainersNotReady condition as failure

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
In `get-consumption`, only returning entries with non-`nil` resource-type -> consumption maps.
The resource-type -> consumption map can be `nil`, for example, if all pods on the node have no resource request.
> Gracefully handles nodes with nil consumption maps

- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Separate lock shards per compute cluster. 
Right now the set of lock shards is global across all of Cook, so one stuck thread can hold a lock shard which, via lock aliasing, can get another thread stuck which can cascade throughout the system. By splitting it, we can limit the blast radius of a stuck thread to the transitive closure of the related pools and the compute clusters that supply them. Even if a thread is stuck, we can at least make more progress before it cascades into everything freezing.
> Separate lock shards per compute cluster.

- scheduler/src/cook/scheduler/constraints.clj
- Optimize novel-host-constraint time by ~10%.
This check is run whenever trying to see if a job can run on a prospective host. Use a hashset instead of list traversal for membership testing. This is about 10% of total runtime.
> Optimize novel-host-constraint

- scheduler/src/cook/pool.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
Only starting a scheduling loop for pools that are active.
We don't want to waste CPU, mem, etc. on scheduling loops for pools that have been disabled.
> Prevents inactive pools from having a scheduling loop

- scheduler/config-k8s.edn
- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/src/cook/util.clj
- scheduler/test/cook/test/compute_cluster.clj
- scheduler/test/cook/test/mesos/mesos_compute_cluster.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- scheduler/test/cook/test/util.clj
- Do unassignments asyncronously, adding to a list, and later unassigning just before matching.
This avoids the fenzo lock being held when processing the k8s state machine, which would otherwise cause all pod completions to get stuck waiting for that lock.
> Do fenzo unassign in batches outside of the fenzo lock

- scheduler/src/cook/kubernetes/compute_cluster.clj
- Make the lock vector a vector, not a sequence.
So we can get access to locks with O(1) instead of O(n).
> Make the lock vector a vector, not a sequence.

- scheduler/src/cook/kubernetes/controller.clj
- Collect metrics for time until waiting and running for synthetic pods and regular pods separately.
We think that these will have different responsivenesses, so track them separately.
> Split metrics for synthetic pods and normal pods for time until run and time until waiting

- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- We need to detach the timer so that we don't count waiting excessively for synthetic pods. We'll count each state revisit, not the first one where the pod shows as there.
Make the metric correct.
> Fix time-until-waiting metric.

- cli/cook/subcommands/ssh.py
For not-yet-running or already-completed k8s jobs, giving an informative message instead of attempting to `kubectl exec` to something that doesn't exist.
To improve the user experience when users run `cs ssh` to a job instance that isn't running.
> Improves cs ssh messages for k8s jobs

- cli/cook/version.py
Bumping the CLI version.
To release the CLI.
> Bumps CLI version to v3.9.1

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- adding the configured pod label prefix to the `workload-*` labels
- changing the defaults to `undefined` for the `workload-*` labels
So that the `workload-*` labels are consistent with the other pod labels that are passed through from job labels due to their prefix.
> Adds pod label prefix to workload labels

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- adding `application.` to the application-based pod labels
- adding application name and version as pod labels
- when necessary, coercing application name and version to be valid k8s pod label values
The workload-* field values are already checked for pod-label-value validity at job submission time, but the name and version fields existed prior to the k8s support in Cook, so we need to coerce names and versions that are too long and/or start/end in a non-alphanumeric character.
> Adds pod labels for application name and version

- scheduler/src/cook/schema.clj
- make straggler kill mea culpa
Consider straggler kill as something that is not a property of the job. Allow it to re-run
> make straggler kill mea culpa

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Conj matched-job-uuids into launch-job-uuids in update-host-reservation instead of the other way around.
This data is used by the rebalancer. 
Maunched-job-uuids is the much bigger set. Its more efficient to add the matches to this much larger set than the reverse.
I estimate cook slows down about 2%/day in the matching loop as this set grows.
> Conj the smaller set into the bigger set in update-host-reservation

- scheduler/src/cook/scheduler/scheduler.clj
- This swaps a dictionary lookup for a simple field query in fenzo's matching logic.
More efficient matching in Fenzo. This saves mostly CPU, not scheduling latency.
> Optimize TaskRequestAdapter.

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/constraints.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Refactor VirtualMachineLeaseAdaptor constructor to go through factory.
This is the first on a set of refactors to compute VirtualMachineLeaseAdaptor.getAttributes more efficiently at construction time instead of at query time. In particular, get-attr-map can be calcualted much more efficiently on a set of offers in bulk instead of individually. That is the long term goal of these refactors.
> Refactor VirtualMachineLeaseAdaptor to go through factory.

- scheduler/src/cook/scheduler/scheduler.clj
Filtering out inactive pools when ranking jobs.
1. There's no need to run the ranking code on inactive pools.
1. The map returned by the ranking function is used by the rebalancer, and when the rebalancer encounters an inactive pool, it throws an NPE when it calls `view-incubating-offers` with that inactive pool, because that code path is already filtering out inactive pools.
> Skips inactive pools when ranking

- scheduler/docs/kubernetes-state.dot
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Introducing a new k8s state, `:pod/deleting`, which until now has been captured by the combination of (`:missing` + `:pod-deleted? true`).
- Adding entries to the state machine for `:pod/deleting`, but (mostly) without changing behavior (in this PR).
- The one behavior change introduced here is that prior to this change, the state machine is sometimes generating two kill requests within 100ms of each other due to the fact that pods with a deletion timestamp are being treated the same as pods that are completely missing from k8s. The "opportunistic killing" code is there to avoid a race where the kill request enters the state machine before it's become aware of the pod's existence from the pod watch. This code makes sense, but only for the "actually missing from k8s" scenario, not for …
> Introduces :pod/deleting state

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
Adding support for environment variables that configure telemetry for jobs.
To be able to collect and analyze telemetry data for Cook jobs.
> Adds environment variables for telemetry

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
If a pod has a deletion timestamp older than a configurable amount of time (e.g. 15 minutes), Cook will hard-delete the pod (with grace period = 0).
Without this, Cook will assume any pod with a deletion timestamp is already deleted, which is sometimes not the case.
> Hard deletes pods that have been deleting for too long

- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
Adding optional support for replacing characters from telemetry tag keys.
Some telemetry sinks don't support certain characters in tag keys.
> Supports replacing invalid characters from telemetry tag keys

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
Adding the configured label prefix and `application.` to the workload label keys for synthetic pods.
To make them consistent with the labels for real job pods.
> Fixes the names for synthetic pod workload labels

- jobclient/python/cookclient/__init__.py
`jobspec['disk']` may already be in the proper form if it was specified with `jobspec={'disk': {'request': 64000}}`.
> ENH: Only convert Disk to dict if not already a dict

- integration/tests/cook/test_dynamic_clusters.py
- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/compute_cluster.clj
Adding a `features` field to the compute cluster.
To eventually support constraining job instances to specific compute clusters based on the features those compute clusters support, e.g. specific NVIDIA driver versions.
> Adds features to compute cluster

- scheduler/src/cook/scheduler/offer.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/mesos/task.clj
- scheduler/test/cook/test/scheduler/constraints.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Refactor the offer and lease->offer code to a new file.
- No functionality change
Prepare for VirtualMachineLease calculations to happen behind the compute cluster API layer.  Gets this code into a file with a lot less dependencies than cook.scheduler.scheduler
> Refactor the offer->lease code to a new file.

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/compute_cluster.clj
Allowing cluster features to change on an existing cluster.
We want to support updating cluster features after the initial cluster creation.
> Allows cluster features to be dynamic

- scheduler/config-k8s.edn
- reduce default job disk size
So that a default job will fit on test cluster
> reduce default job disk size

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_multi_user.py
- scheduler/src/cook/caches.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/plugins/definitions.clj
- scheduler/src/cook/plugins/submission.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/monitor.clj
- scheduler/test/cook/test/rest/api.clj
Adding support for configurable job-routing to a Cook pool based on a "special" (configurable) pool name.
In order to support intelligent job routing within Cook, e.g. choosing the most appropriate of multiple possible pools for a job.
> Supports pluggable job-routing

- scheduler/config-k8s.edn
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/rebalancer.clj
- scheduler/src/cook/scheduler/constraints.clj
- scheduler/src/cook/scheduler/offer.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/rebalancer.clj
- scheduler/test/cook/test/zz_simulator.clj
- Add comments about a particular wart in the agent attribute cache.
- Refactor agent-attrbute-cache to happen lower down than in components.
- Change agent-attribute-cache to use guava cache instead of clojure cache.
- Make the rebalancer selectable by pool regexp.
Rebalancer can be something we need for a fixed size k8s cluster. We've also seen it show up, occasionally, as a scaling bottleneck, running for excessive time in Mesos, and k8s lets us go to a higher scale. So, get rid of the O(n) cache it uses and replace with guava cache. In addition, we may only want it active for some pools, not all pools, so make this selectable.
> Update rebalancer to use guava cache and be per-pool selectable.

- cli/cook/subcommands/show.py
- displaying job labels (if any) in their own table instead of in a cell in the top table
- sorting job instances by start time
The current job label display gets really ugly when there are many or big labels. It's annoying to not show job instances in time order.
> Displays job labels in a table

- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/rest/api.clj
- saving the pool name that was specified on the job submission
- returning it in the job query response
Job routing plugins can convert a "special" pool name provided at submission time to a real pool, and it's useful to be able to know when this happened.
> Saves the submitted pool name

- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/passport.clj
- scheduler/src/cook/rest/api.clj
- Adding a new logger that logs Cook passport events to a passport-only log file
- Adding a structured logging wrapper to log passport events as json
- Adding passport logging for the following events:
- Job submission through raw API
- Pod submission
- Pod completion
- Having structured passport logging makes it easier to work with and filter logs
> Add passport logger and json passport log events

- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- don't override existing job groups
If you add a job to a group currently you will override the existing group with an implicit group
> don't override existing job groups

- scheduler/src/cook/kubernetes/api.clj
- Add scratch-space volume mount to cook-sidecar setup
- This change will help us implement on-pod passport event logging
> Give scratch space read/write access to cook-sidecar

- scheduler/src/cook/passport.clj
- scheduler/src/cook/rest/api.clj
- adding a new passport event type, `:api-job-creation`
- changing the existing stamp in `create-jobs!` to use `:api-job-creation`
- stamping with `:api-job-submission` from the `malformed?` check (earlier in the request flow)
- adding how the pool was sourced (request parameter vs. `x-cook-pool` header) to `:api-job-submission` 
We want to be able to distinguish between jobs that landed in a pool via the request parameter and those that landed in a pool via the `x-cook-pool` request header. This change also allows for a passport event to be logged earlier in the request flow, before all of the validation checks have run.
> Adds pool source to job submission passport stamp

- scheduler/src/cook/cached_queries.clj
- scheduler/src/cook/caches.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Add a cache mapping `instance-uuid` to `job-uuid`
- Update `assoc-uuids` function to get `job-uuid`s from cache when needed and append them to passport event maps
- Add `with-redefs` logic to spoof cache hits in `cook.test.kubernetes.controller` tests
- Adding this cache gives us the ability to log `job-uuid` for all Passport events in the state machine where `job-uuid` is not immediately visible
- These changes will give us a way to associate `instance-uuid` with `job-uuid` without querying datomic each time we want to access it
> [DRAFT] Add instance-uuid->job-uuid cache and update kubernetes/controller tests

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Fix bug that adds synthetic pods to the `instance-uuid->job-uuid` cache instead of normal pods
We only want to add instance uuids for non-synthetic pods to that cache. Before this change, we were doing the opposite of that and only adding synthetic pods to the cache.
> Fix adding instances to cache bug

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- Change `:cluster-name` to `:compute-cluster` in passport logs
`:compute-cluster` is a more clear name than `:cluster-name`, and this helps us differentiate between Cook cluster and compute cluster in the passport event logs.
> Change cluster-name to compute-cluster

- scheduler/src/cook/util.clj
- Note that this code is buggy.
We believe that this may be linked to some random nondeterministic behavior we've previously seen. Note its buggy and leave breadcrumbs behind to fix it.
> Note bug in require not being thread safe.

- integration/tests/cook/test_multi_user.py
-  Make test_user_pool_rate_limit more reliable and more clear what its doing.
- Make the test more deterministic.
> Adjust test_user_pool_rate_limit to make it more reliable.

- integration/tests/cook/util.py
- scheduler/src/cook/rest/api.clj
**This is an API change.**
- Fixes two bugs that mostly compensated for each other. 
- When we generate Location: headers for redirect-to-leader, we should include any query parameters in the response.
- The follow redirects code in the integration tests would add those parameters (including duplicating them)
This is correct behavior.
> Fix Location header of redirects to include request parameters

- integration/tests/cook/util.py
- scheduler/src/cook/rest/api.clj
- Make /unscheduled endpoint redirect to leader.
- Make the code around redirect-to-master more robust and backward compatible for code that uses :exists? handlers
The /unscheduled endpoint must always redirect to leader to get appropriate data from Fenzo causes. This has been partially broken for a long time.
> Make /unscheduled endpoint redirect to leader.

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/passport.clj
- scheduler/src/cook/rest/api.clj
- Update names for passport event types
- Add cook-scheduler namespace on event-type strings
- Add `source` field with value `cook-scheduler`
These changes keep our `event-type` strings up to date with our design document and provide us with `source` information in every log.
> Update passport event types with cook-scheduler source and namespace

- scheduler/src/cook/kubernetes/api.clj
Logging `INFO` instead of `WARN` when the node watch times out.
We expect timeouts to happen on the node watch when there is no node-related activity.
> Logs info instead of warn for node-watch timeouts

- scheduler/src/cook/cache.clj
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/mesos/task.clj
- scheduler/src/cook/rate_limit/generic.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/rest/spnego.clj
- scheduler/src/cook/scheduler/constraints.clj
- scheduler/src/cook/scheduler/fenzo_utils.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/tools.clj
- Annotate a number of types within Cook to avoid reflective calls
We found that a lot of heap space is spent/wasted on reflection. A reflection call is roughly O(n) time and garbage with N being the number of methods in the called java class. Even small test clusters are seeing 100k calls/sec.
> Avoid reflection by annotating Java calls with java object types.

- scheduler/project.clj
- scheduler/src/cook/config.clj
- use date in passport log file name
Instead of using a fixed file name for the passport log file and renaming daily we want to use a file name that includes the date. When a new day starts a new file is created and no file is renamed. This reduces the chances for watchers of the passport log files to miss events when the file is renamed.
> use date in passport log file name

- scheduler/src/cook/cached_queries.clj
- scheduler/src/cook/caches.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Create a cache mapping `job-uuid` to `job-map`
- Log `pool`, `job-name`, and `user` fields in passport events
- Add `COOK_JOB_NAME` AND `COOK_JOB_USER` as pod environment variables
- These changes allow us to use those 3 fields when looking at cook metrics and to filter on them when looking at passport events.
> Add pool-name, job-name, and user to Passport Logs

- scheduler/src/cook/kubernetes/api.clj
- Use `cached-queries/job->pool-name` function for getting `pool-name`
- This chance will fix the bug where `pod-launched` and `pod-completed` logs have a `nil` pool field when a job is submitted with no pool specified
> Fix nil Pool logs

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Make flag for enabling shm support on k8s.
- Some cases of python multiprocessing need SHM support to work.
> Make flag for enabling shm support on k8s.

- scheduler/src/cook/rest/api.clj
Adding cpus, gpus, and mem to the `job-submitted` passport stamp.
It's useful when analyzing job submission events to know what their resource requests were.
> Adds resource requests to job-submitted event

- scheduler/config-k8s.edn
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Let us make a predefined environment in the config variable so that Cook can inject environmental variables an a per-pool basis. 
- 
- 
So that we can have runtime wrapper scripts properly configured as a function of the pool name.
> Add support for defaulting the environmental variables as a function of the pool

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/passport.clj
Instead of a single `pod-launched` event type, introducing the following 4 event types:
- `pod-submission-succeeded`
- `synthetic-pod-submission-succeeded`
- `pod-submission-failed`
- `synthetic-pod-submission-succeeded`
and firing off these events after the pod submission request returns.
To make the distinction between synthetic and real pod submissions and successful / failed ones more clear.
> Revamps pod-submission-related passport events

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
At the beginning of `test_pool_quota`, killing any running or waiting jobs in the pool we're testing against.
If we don't, they will take up quota and could cause the jobs submitted in the test to never get scheduled.
> Makes test_pool_quota more reliable

- scheduler/src/cook/kubernetes/controller.clj
Adding exit-code (which can be `nil`) to the `pod-completed` passport event.
It can be useful for analysis to have exit-code in addition to the instance reason.
> Adds exit-code to pod-completed passport event

- scheduler/src/cook/kubernetes/compute_cluster.clj
Changes the not-looking-for-offers log to make it more clear. Instead of saying `Skipping pool because it is not a known Kubernetes pool`, we now say `it doesn't autoscale for, and has 0 nodes tainted for <pool>`.
Because saying `it is not a known Kubernetes pool` is misleading / incorrect.
> Clarifies not-looking-for-offers log

- integration/tests/cook/test_basic.py
- scheduler/src/cook/rest/api.clj
- log job's name instead of the name clojure function
- edit test_default_container_for_pool test to allow for incrementally configured default image
The default image selection logging payload is not the job name, it is the clojure function "name" and it crashes if we attempt to log
> Fix default image selection logging

- integration/tests/cook/test_multi_user.py
- making `test_preemption_basic` use the default submit pool for testing, if it's set and the rebalancer is enabled on it
- deleting `test_preemption_for_pools`
`test_preemption_for_pools` was attempting to test preemption on every active pool, which was overkill and broken. `test_preemption_basic` was not respecting the default submit pool for testing, and instead using the default pool of the cluster under test, which was broken in cases where that pool didn't have the rebalancer enabled but some other pool in the cluster did.
> Makes test_preemption_basic respect the default submit pool

- .github/workflows/executor-tests.yml
- .github/workflows/unit-tests.yml
- jobclient/java/pom.xml
- scheduler/Dockerfile
- scheduler/bin/bootstrap
- scheduler/project.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Update Cook to support JDK-11
- JDK8 is EOL
> Update Cook to run on JDK-11

- scheduler/bin/start-datomic.sh
- scheduler/project.clj
- scheduler/test/cook/test/compute_cluster.clj
- Update Cook to Clojure 1.10
- Ensure that unit and integration tests pass.
This enables us to use next.jdbc JDBC library.
> Update to clojure 1.10

- integration/tests/cook/test_basic.py
- scheduler/src/cook/config_incremental.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/passport.clj
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/config_incremental.clj
- scheduler/test/cook/test/kubernetes/api.clj
- add incremental image config support for aux containers
We want the auxiliary containers for the job pod to support incremental image configurations. This will allow us to incrementally test new functionality.
> add incremental image config support for aux containers

- scheduler/src/cook/kubernetes/api.clj
- sidecar/cook/sidecar/config.py
- don't use instance uuid in progress file name
When we use instance uuid in progress file name we make it fail when a job is checkpointed and restored because the instance uuid changes.
> make progress file compatible with checkpointing

- scheduler/docs/configuration.adoc
- scheduler/project.clj
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/reporter.clj
- scheduler/src/fork/metrics_clojure/LICENSE.markdown
- scheduler/src/fork/metrics_clojure/README.txt
- scheduler/src/fork/metrics_clojure/metrics/jvm/core.clj
- Remove support for Riemann metrics
- Update to newer version of dropwizard metrics that support >JDK8
- Import unreleased metrics-clojure that has changes needed to support later version of dropwizard.
This makes metrics work with JDK11. Previously, they were failing because of JVM modularity rules. We needed to update dropwizard metrics, but have to deal with the non-updated metrics-clojure. (There is a class rename in io.dropwizard that causes them to fail.)
> Fix metrics no longer beling logged with jdk11 update

- .github/workflows/executor-tests.yml
- .github/workflows/unit-tests.yml
- jobclient/java/pom.xml
- scheduler/Dockerfile
- scheduler/bin/bootstrap
- scheduler/project.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
This reverts commit 957ecf968f03eae7a8d62bb701cb4bcf9dcd1347.
- Revert "Update Cook to run on JDK-11 (#1937)"
We encountered issues upgrading from JDK-8 to JDK-11 and wish to revert for now
> Revert "Update Cook to run on JDK-11 (#1937)"

- scheduler/src/cook/kubernetes/controller.clj
Instead of logging the entire pod metadata object, hand-picking the fields from it that we want to log.
To reduce excessive Cook logging.
> Trims down pod metadata logging

- .github/workflows/executor-tests.yml
- .github/workflows/unit-tests.yml
`ubuntu-16.04` -> `ubuntu-18.04` in the GitHub actions yaml.
16.04 is no longer listed as an available environment here:
https://github.com/actions/virtual-environments#available-environments
> Updates github actions to ubuntu-18.04

- integration/tests/cook/util.py
Adding `application` to the default job spec for integration test jobs.
To have better analytics for integration test jobs.
> Adds application to integration test jobs

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
This is a follow-up to PR #1948.
Trimming down the pod event log lines.
To avoid excessive and unnecessary logging.
> Trims pod event logs

- scheduler/java/com/twosigma/cook/kubernetes/FinalizerHelper.java
- scheduler/java/com/twosigma/cook/kubernetes/RemoveFinalizerHelper.java
- scheduler/src/cook/config_incremental.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
This gives Cook time to collect the pod completion status.
- Have Cook put finalizers on its pods
This prevents pod-gc from deleting pods before cook can collect the completion status.
> Make cook add a finalizer to its k8s pods to prevent GC.

- integration/tests/cook/test_cli.py
- integration/tests/cook/util.py
- making the test jobs use at least the configured default test job memory
- making the test jobs have retries
To make the test jobs less likely to fail.
> Makes test_usage more reliable

- integration/tests/cook/test_cli.py
When there is no default submit pool configured, using the default pool from the cluster under test.
Not all test runs configure the default submit pool.
> Makes test_submit_constraint work with no default submit pool configured

- scheduler/src/cook/monitor.clj
- scheduler/test/cook/test/monitor.clj
- add waiting under quota user metrics
If Cook and the public cloud were perfectly elastic then a user would not have any waiting jobs if they are under quota. This metric will show the real world tracking error at any moment from the theoretical ideal.
> add waiting under quota user metrics

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- Improve finalizer logging and add some metrics.
Because of races, we can see error responses when deleting finalizers that are innocuous.
> Improve finalizer logging code.

- scheduler/src/cook/config.clj
Adding `production?` field to Cook's config settings.
So that we can ask a Cook if it is production or not, in order to only do certain operations (like killing running and waiting jobs) in non-production Cooks.
> Adds production? to settings

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- add metrics related to node and pod usage
We have limits to the total number of nodes and pods we can have and we alert when we hit those limits. But we don't have metrics of those limits.
> add metrics related to node and pod usage

- README.md
- scheduler/bin/start-datomic.sh
- scheduler/project.clj
- fix version of datomic.zip
- fix COOK_VERSION in start datomic script
- update jobclient dependency version
- add instructions to build jobclient dependency
We should be able to follow the steps to set up Cook using Vagrant and have it work: https://github.com/twosigma/Cook#readme
> Fix vagrant scripts

- scheduler/src/cook/rebalancer.clj
Logging the job instance in question when a rebalancer preemption transaction fails.
So that searching the log by job instance brings up these failures.
> Logs job instance when preemption transaction fails

- README.md
Fixes the single-test command in the quick start by adding the file path.
Otherwise, `pytest -k` will pick up other tests that start with `test_basic_submit`, like `test_basic_submit_and_wait`, which is not the goal of this example command.
> Fixes the single-test command in the quick start

- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/schema.clj
Adding a field for the length of the job command.
For easier data analysis on command line lengths in the wild.
> Adds field for command length

- scheduler/src/cook/kubernetes/api.clj
Logging pod events that do not correspond to currently tracked pods, if they both have event type `Warning` and reference `cook` in the `fieldPath`.
Pod events tied to Cook pods can arrive after Cook has deleted the pod, and we want these events to show up in the log as well.
> Logs pod events with type Warning

- scheduler/src/cook/passport.clj
- scheduler/src/cook/scheduler/constraints.clj
- allow incremental configurations for default job constraints
We want different default job constraints for different jobs for example to transition to different GPU driver versions
> allow incremental configurations for default job constraints

- integration/tests/cook/test_client.py
- jobclient/python/cookclient/__init__.py
- jobclient/python/cookclient/containers.py
- scheduler/src/cook/config.clj
- scheduler/src/cook/rest/api.clj
- support using default image with a user-specified container
Currently the user can only use the default image if they do not specify any container. A user is not able to specify properties of a container such as open ports and at the same time use the default image. They must specify all or nothing.
This PR lets the user set a special symbolic image in their container spec name that will be translated into the default image.
> support using default image with a user-specified container

- integration/tests/cook/test_basic.py
- don't set container for gpu jobs
GPU drivers can depend on container and tests should let Cook default them
> don't set container for gpu jobs

- scheduler/test/cook/test/compute_cluster.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Make offer handling unit test not depend on database at compile time.
Helps with the postgres migration.
> Make offer handling unit test not depend on database at compile time.

- scheduler/project.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/kubernetes/metrics.clj
Adding metrics for:
- time during a disconnected pod/node watch
- time between pod/node watch responses
- pods processed from the pod watch
To better understand the effects of watches disconnecting.
> Adds watch gap metrics

- integration/tests/cook/test_basic.py
- scheduler/src/cook/rest/api.clj
- properly resolve incremental default image configuration
- fix bad test assertion
We need to fix support incremental default image configuration. If a user omits the image from their container we must still resolve the image configuration from the default container, not try to use it directly.  The image configuration from the default container might be an incremental configuration, in which case it needs to be resolved. That is what this PR fixes.
> fix support for incremental default image configuration

- scheduler/src/cook/config_incremental.clj
- scheduler/src/cook/kubernetes/api.clj
- allowing a "use all gids" pod annotation to be incrementally added to pods
In order to avoid contradictions between which group Cook thinks a user belongs to and which group Kubernetes thinks the user belongs to.
> Adds annotation for using all gids

- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- add missing fields to compute cluster API validation
This was missed when adding the `location` and `features` fields to dynamic compute clusters
> Add missing fields to compute cluster API validation

- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- Fix valid pod label regex to match spec
Our current pod label validation regex does not match the spec https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
> Fix pod label regex

- scheduler/postgresql/sql/docker_init_new_database.sql
- Make sure all schemas created as any user are readable by Cook.
Postgres schemas are, by default, permissioned only for the creating user. Make them available as cook_scheduler user for convenience.
> Fix permission bug in setting up databases in opensource.

- scheduler/.gitignore
- With JDK11 logging changes. we clutter the directory with gclog files. Hide them with gitignore.
> Add gclog to .gitignore.

- scheduler/datomic/data/seed_k8s_pools.clj
- scheduler/docker/run-cook.sh
- scheduler/project.clj
- scheduler/src/cook/postgres.clj
- scheduler/src/cook/test/postgres.clj
- Enable Cook to use c3p0 connection pooling for postgres.
- Fix a bug where we didn't set the connection metadata from the environment in seed_pools startup.
Enable c3p0 and fix a bug in Postgres support
> Switch Cook to using c3p0 for database pooling.

- scheduler/project.clj
- scheduler/src/cook/postgres.clj
- scheduler/src/cook/test/postgres.clj
- Switch the implementation from using java.jdbc to next.jdbc
This is a more modern more performant library.
> Switch the implementation from using java.jdbc to next.jdbc

- scheduler/liquibase/README.md
- scheduler/liquibase/changelog/com/twosigma/cook/changelogs/setup.postgresql.sql
- scheduler/postgresql/README.md
- scheduler/postgresql/bin/setup-database.sh
- scheduler/postgresql/bin/setup-new-schema.sh
- scheduler/postgresql/sql/init_cook_database.sql
- Add support for liquibase configuration for posgres database schems for Cook.
This change gives us better control over postgres schemas and versioning Cook's schema on postgres.
> Initial Liquibase support for Cook for postgres configuration.

- scheduler/src/cook/rest/api.clj
- Increase logging verbosity when submission fails with an exception.
Improve the visibility. Make these errors show up in the log, not just returned to the user.
> Increase logging verbosity when submission fails with an exception.

- cli/.gitignore
- Add virtualenv to .gitignore in cli directory.
- Avoid clutter in dirty files if there are any virtualenvs here.
> Add virtualenv to .gitignore in cli directory.

- integration/bin/run-integration.sh
- Partial fix for integration tests running in docker in opensource.
- Remove some minimesos dependencies in opensource tests harnesses.
These tests have bitrotten and not all succeed in integration/bin/run-integraion.sh. But at least this improves things a bit; you can run them. A lot still fail, but ate least we can run.
> Partial fix for integration tests running in docker in opensource.

- cli/cook/http.py
- integration/Dockerfile
- integration/requirements.txt
- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- scheduler/config-k8s.edn
- Upgrade everything to python 3.9 dependencies.
- Everything was previously wired to python 3.5.9 or python 3.6, but those are old and no longer maintained.
> Upgrade everything to python 3.9 dependencies.

- scheduler/config-k8s.edn
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Capability for default Kubernetes pod labels per pool
We want to give operators the ability to mark pool membership by labelling individual Kubernetes pods. This change supports the same regex pool name matching as the default-env configuration.
> Add capability for default K8s pod labels per pool

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- remove per-uuid Fenzo "retracting lease" log
- remove per-taskid Kubernetes compute cluster scan log
- remove Cook-Kubernetes state map log when both agree the pod is running
We prepose a few simple logging changes to remove low-value logs and slim down log volume (both number of lines and bytes).
> Cook logging diet

- scheduler/CHANGELOG.md
- scheduler/project.clj
> Release Cook v1.59.2

- scheduler/src/cook/kubernetes/controller.clj
- Fix the condition for deciding when to log expected versus actual Kubernetes state in the controller
- Previously, we were not comparing the right things, which resulted in no filtered logs
> Fix k8s controller pod process logs filter condition

- cli/cook/cli.py
- cli/cook/metrics.py
- Adds cluster as a tag to the existing command.<subcommand>.runs metric
Allows us to track how users are submitting jobs (are they cluster dependent?)
> Add tag for user-specified cluster to cli 'command.runs' metric

- scheduler/src/cook/kubernetes/api.clj
- Add support for a second init container that is used for setting up checkpointing.
- This improves support when the sidecar and user container have a different platform.
This diff is much smaller if you suppress whitespace. Some refactoring was done to extract common variables.
> Add second init sidecar for checkpointing.

- scheduler/CHANGELOG.md
- scheduler/project.clj
> Release Cook v1.59.3

- cli/cook/version.py
bumping CLI version to 3.1.0
To publish the new version to pypi.
> Updates CLI version to 3.10.0

- scheduler/src/cook/compute_cluster.clj
- Split the "Updating dynamic clusters" log line into multiple entries for each config.
The current log is too long and hard to read.
> Splitting 'updating dynamic clusters' log into separate entries

- scheduler/src/cook/scheduler/scheduler.clj
- Convert existing log in handle-resource-offers! to structured logging
- Add basic number matched, unmatched, considered metrics
We want to improve Cook's metrics surrounding the match cycle. This is a first step to aid in gathering data to determine future metrics.
> Convert match cycle log line to structured logging and add simple counters

- scheduler/CHANGELOG.md
- scheduler/project.clj
> Release Cook v1.59.4

- integration/tests/cook/test_client.py
- integration/tests/cook/util.py
- Change the integration test to use the default GPU model, That way when we warm up for integration tests, the test will succedd.
- Increase integration test pass rate.
> Change GPU test to use the default GPU model

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/tools.clj
- Remove string formatting from structured logging output
We want to allow downstream systems to intelligently pick type-mappings for the match cycle structured logs.
> Stop string formatting stats in match logging

- scheduler/src/cook/log_structured.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/util.clj
- Splitting per-user match cycle metrics to individual log lines. 
- Adding a utility function to emit structured logging, with support for specifying a custom logger namespace.
- Splitting the per-user metrics to individual log lines reduces the cardinality of the structured logs field; instead of having custom field names with the user name, we will have a consistent log format with the user as the value.
- We intend to convert more log messages to use structured logging for fields like the pool name and kubernetes cluster.
- Having the ability to use a custom logger namespace allows us to send certain logs to a separate index for faster querying.
> Adding utility function for emitting structured logs and updating structured logging for match cycle metrics

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/log_structured.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/log_structured.clj
- Update more messages to use structured logging with fields like pool name and compute cluster name.
This will make it easier to filter out logs and visualize metrics.
> Updating more logs to use structured logging

- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/scheduler/dru.clj
- Add a unit test that checks to make sure that running and waiting jobs sort in the right (implicit) order.
- Also checks that we successfully cache the owners of these jobs in our cache.
- Make sure that we cache the user for any job or instance.
This helps to avoid some 10x rank time outliers. The unit test helps make sure that we order jobs correctly on future changes to this code.
> Speed up rank loop worst case by improving the instance->user cache.

- scheduler/src/cook/test/postgres.clj
- Fix a missing import in setting up postgresql for unit tests.
In some `lein test :only` paths, we can get an import error.
> Fix a missing import in setting up postgresql for unit tests.

- sidecar/cook/sidecar/version.py
- sidecar/setup.py
- Bump sidecar `requests` requirement to `~=2.27.0`
> Bump sidecar requests requirement to 2.27.0

- scheduler/src/cook/util.clj
- scheduler/test/cook/test/util.clj
- Updates the `format-map-for-structured-logging` function to not flatten nested maps, but instead traverse them and format their values appropriately.
This allows us to safely call the function on nested maps without flatting its values unintentionally.
> Updating format-map-for-structured-logging to not flatten nested maps

- integration/tests/cook/test_cli.py
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Make Cook decide the pool based on the node label instead of taint.
- Change the CPU requirements for a couple integration tests.
Labels are more visible and easier to use for node filtering.
> Make Cook decide the pool based on the node label instead of taint.

- scheduler/src/cook/kubernetes/controller.clj
- Map a NodeAffinity failure reason to a preemption.
Some preemptions can show up with this error which we want to be
mapped to :reason-slave-removed so that they can be handled with the
mea culpa machinery.
> Map a NodeAffinity failure reason to a preemption.

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- scheduler/test/cook/test/zz_simulator.clj
- Change `api-only?` instances to still configured leader election, without actually joining the selection process.
Currently, `api-only?` instances fail client requests that require forwarding to the leader. This change fixes that by giving `api-only?` instances the ability to forward to the elected leader.
> Fixing bug when running in api-only mode

- cli/cook/querying.py
- Use `__call__()` instead of the deprecated `call()` API from tenacity which was removed in In jd/tenacity#307 but was still used in the CLI
The deprecated call was removed and this will no longer work with newer Tenacity versions.
> Use non-deprecated Tenacity API

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- scheduler/test/cook/test/zz_simulator.clj
- Moves the previously global kill/launch sequencing lock to be per compute cluster rather than per Cook cluster
A global kill lock forces all compute clusters to wait behind the slowest. Switching to a per-cluster design breaks that bottleneck, but trades for another. Instead, we may end up with different pools waiting for the same compute cluster.
Long term goal is to remove the lock by removing the requirement that kill signals process strictly after the relevant task was launched.
> Moving global kill-lock to be per cc

- scheduler/CHANGELOG.md
- scheduler/project.clj
> Release Cook Scheduler v1.61.0

- cli/.cs.json
- cli/cook/cli.py
- Add functionality to specify cluster or url action defaults for Cook's CLI
This change allows us to be more flexible when assigning defaults. Specifically, if we desire different defaults per action.
> Add support for specifying a default Cook cluster per Cook CLI action

- cli/.cs.json
- cli/cook/cli.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/test_cli_multi_cluster.py
- Bugfix for default cluster & pool per action
Previous logic did not allow us to specify a cluster and a default at the same time! Also, we want to explicitly allow any cluster or pool CLI flag to override the default.
> version bump to 3.9.5 and bugfix action-default cluster logic

- scheduler/src/cook/scheduler/scheduler.clj
- Add missing `:pool` tag to top-most match cycle tracing span. 
This allows us to filter traces by pool.
> Adding :pool tag to top-most match cycle span

- scheduler/CHANGELOG.md
- scheduler/project.clj
- Updating changelog and version for v1.61.2.
> Release v1.61.2

- cli/cook/subcommands/submit.py
- Add units to the cook submit help strings.
- It makes the help strings more detailed and useful, indicating what values are valid and what they mean.
> Add units to cook submit help strings (COOKS-2079)

- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/tools.clj
- A cleanup to simplify util/global-pool-quota invocation.
Split off from the joint quota work.
> Refactor: Make util/global-pool-quota simpler to use.

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Support global pool quotas across aggregations of pools. 
When we split a set of jobs among multiple pools, we want global pool quotas to continue to apply.
> Support global pool quotas across aggregations of pools. 

- scheduler/src/cook/monitor.clj
- scheduler/src/cook/prometheus_metrics.clj
- Adding prometheus metrics to `monitor.clj`, which contains user resource usage and count metrics.
> Adding prometheus metrics for user resource usage and count

- scheduler/src/cook/prometheus_metrics.clj
- scheduler/src/cook/scheduler/scheduler.clj
- Adding prometheus metrics to match cycle stats.
> Adding match cycle metrics to prometheus

- scheduler/src/cook/pool.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/rest/api.clj
- Filter on both `:job/pool :pool-name` and `:job/submit-pool-name` in the `/jobs` API endpoint
The job routing changes makes it harder for users to track where their jobs start if the `/jobs` endpoint only looks at the effective pool name. This change allows users to use the same pool for creating and looking up jobs while Cook handles the routing logic behind the scenese.
> Use pools & submit pools in /jobs list endpoint

- scheduler/src/cook/prometheus_metrics.clj
- scheduler/src/cook/scheduler/scheduler.clj
- Adds a counter for total jobs launched per pool and compute cluster.
- This would let us visualize the job launch rate.
> Adding prometheus metric for jobs launch count

- scheduler/CHANGELOG.md
- scheduler/project.clj
- Updates changelog and version of v1.62.1.
> Releasing Cook v1.6.2

- scheduler/src/cook/scheduler/scheduler.clj
- For the case where there are 0 considerable jobs, update the match-percent to 100, and the head-was-matched and all-matched to 1.
This makes visualizations more consistent.
> Updating match cycle metric logic for 0 considerable case

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/prometheus_metrics.clj
- Adds prometheus metrics for current and total synthetic pods count.
> Adding prometheus metric for synthetic pods count

- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/plugins/definitions.clj
- scheduler/src/cook/plugins/job_expander.clj
- scheduler/src/cook/plugins/job_submission_modifier.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/plugins/job_submission_modifier.clj
- scheduler/test/cook/test/rest/api.clj
- Add the JobSubmissionModifier plugin location and default, IdentityJobSubmissionModifier
- Refactors JobRouter logic to be applied inside the Job Submission Modifier
We want to create the ability to modify user jobs based on what they submit (e.g. for routing or constraints)
> Add new JobSubmissionModifier and refactor JobRouter

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
Previously, `create-datomic-scheduler` would call `make-offer-handler` for each pool, which setup an anonymous function on the trigger-chan for the pool. This anonymous function is the beginning of the scheduling cycle for a pool.
This PR inserts a new factory function between these two in order to setup for instantiating other types of pool handlers in the future (e.g. Kubernetes Scheduler pools). Currently, the factory only calls one new handler for all pools: `make-fenzo-handler`. This new function is essentially identical to the old `make-offer-handler` function, except for some variables such as `user->quota` moved one call higher as it can be imagined this would be a common variable with other types of handlers.
There are no TODOs with this change.
> use a factory fn for creating (future) different types of pool handlers

- scheduler/CHANGELOG.md
- scheduler/project.clj
- Updates changelog and version of v1.62.4.
> Release Cook v1.62.4

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/mesos/mesos_mock.clj
- scheduler/src/cook/prometheus_metrics.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Adding prometheus metrics to the kubernetes module.
> Adding prometheus metrics to cook.kubernetes

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Add special version of add-starting-pods-reverse
It is more efficient to add the smaller set to the larger set. In other contexts, we want to add the starting pods to the set of all pods. But in the specific context of calculating pods on a machine, the number of pods on the machine is the smaller set.
> Add special version of add-starting-pods-reverse

- scheduler/src/cook/scheduler/scheduler.clj
- Remove metatransaction filter from match.
This should make the database pathway used to load jobs from the database (at match time) more efficient. At this point, we're already filtering to jobs with a commit latch set.
> Remove metatransaction filter from match.

- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Compute the number of pods on a node more efficiently.
This should make matching take less time and generate less garbage.
> Calculate the number of pods a node more efficiently.

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Use 'into' instead of 'merge' for merging maps.
Using `into` here lets clojure use a more optimized codepath where it doesn't make persistent collections for the intermediate states. This means less copying and less garbage. (See docs on `persistent!` and `transient`)
> Better version of add-starting-pods

- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Slightly more efficient job to resources lookup in the cache miss path.
Should help matcher run faster.
> Make job resource lookup more efficient in the miss path.

- scheduler/src/cook/config.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/benchmark.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Delazy some of the list generation; do it at rank time to overlap generation with launch.
This slows down rank time by forcing the lazy list then, but should speed up the first one or two match cycles, and help parallelize the delazy'ing the ranked jobs and launching.
> Delazy some of the list generation; do it at rank

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- Updates the logic to set the synthetic pods metric counters to happen even if that match cycle is not autoscaling.
This makes the metric more accurate when we're matching at 100%.
> Updating synthetic pods counters even if we don't autoscale in that match cycle

- scheduler/src/cook/scheduler/scheduler.clj
- Parallalize autoscale to run at same time as main job launches.
Faster match cycle time and higher launch throughput.
> Parallalize autoscale to run at same time as main job launches.

- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/controller.clj
- Pull `pod-status` and `container-status` from the pod object in `container-status->failure-reason`, instead of passing them in with the pod.
- Follow-up feedback from #2150
> Container status to failure reason selects fields from pod object

- scheduler/src/cook/queries.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Use `d/entity` to query for instance in `write-sandbox-url-to-datomic` and `write-hostname-to-datomic`.
- Refactor error handling in `write-status-to-datomic` and `write-sandbox-url-to-datomic`.
- Follow-up feedback from #2150
> Better error handling in scheduler/write fns

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/prometheus_metrics.clj
- Updates the calculation for the pod count metric to avoid unnecessary operations.
Improved runtime and reduced memory footprint.
> Optimizing total pod count metric

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/config.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- The Kenzo loop will now account for available scheduling capacity before "assigning" a job to an acceptable compute cluster. This is done via  `pos?` filter in the distribution function.
- Kubernetes compute clusters now report their "max launchable" stat, which is a measurement of pods without assigned nodes. This is our best approximation for pressure inside the Kubernetes Scheduler.
- The Kenzo handler will not try scheduling more jobs than total available scheduling capacity across all compute clusters. This reduces expensive work for jobs that would be filtered out at distribution stage.
- The Kenzo handler will short-circuit and then delay the next scheduling loop if there isn't sufficient scheduling capacity (configurable). This will prevent incurring expensive cycle overhead for …
> Use backpressure of scheduling pods to moderate launching new pods for real jobs

- scheduler/project.clj
- scheduler/src/cook/prometheus_metrics.clj
- Enables the default JVM instrumentation available with the prometheus module.
> Enabling JVM metrics in prometheus

- scheduler/java/com/twosigma/cook/kubernetes/ParallelWatchQueue.java
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Do watch processing on the `controller-executor-service` threadpool
Processing watches was previously done by a single thread which could impact the rate Cook could process job completions. Doing it in parallel allows us  to handle a higher job completion throughput.
> Parallel watch processing.

- scheduler/src/cook/scheduler/scheduler.clj
- When creating the task-metadata for Kenzo jobs, do not set scalar-requests to the pool-specific resources. Instead, set to the unmodified job resource values.
- Kenzo pods include sidecar and other containers in addition to the job container. It does not need to account for the overhead like synthetic pods, which only have a single container.
> do not set scalar-requests to pool specific resources for Kenzo pods

- scheduler/java/com/twosigma/cook/kubernetes/ParallelWatchQueue.java
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Parallel watch processing. Slight change to old version to avoid a deadlock.
- Made the threadpools give threads useful names.
Higher watch throughput.
> Parallel watch processing. (#2169)

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/prometheus_metrics.clj
-  Updating a prometheus metric that was recording the compute cluster incorrectly.
> Fixing compute_cluster value in metric to use :name

- scheduler/java/com/twosigma/cook/kubernetes/ParallelWatchQueue.java
- Fix a bug in the newly added parallel watch thread.
- We are supposed to be processing the event, not adding it back into the executor queue.
> Fix the parallel watch
