twosigma/Cook

.travis.yml
README.md
scheduler/src/clj_http_async_pool/circuit_breaker.clj
scheduler/test/clj_http_async_pool/circuit_breaker_test.clj
scheduler/test/clj_http_async_pool/pool_test.clj
scheduler/test/clj_http_async_pool/router_test.clj
scheduler/test/clj_http_async_pool/test_utils.clj

https://travis-ci.org/twosigma/Cook/jobs/81488613
It's those circuit breaker tests!

Why is this test flaky?

---

scheduler/src/clj_http_async_pool/client.clj

Revert "Refactor http async pool client"

---

scheduler/src/clj_http_async_pool/client.clj

CLA signed and sent this time!

Refactor http async pool client

---

jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java

Add support for job labels

---

scheduler/project.clj
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/src/cook/mesos/schema.clj
scheduler/src/cook/mesos/util.clj

This code was derived from sdegler's pull request #91.

Add docker support 

---

scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/schema.clj

This pull request adds support for force-image-pull option the the job's docker configuration.

Adding support for docker force pull image

---

scheduler/docs/configuration.asc
scheduler/docs/scheduler-rest-api.asc
scheduler/example-prod-config.edn
scheduler/project.clj
scheduler/src/cook/authorization.clj
scheduler/src/cook/components.clj
scheduler/src/cook/mesos.clj
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/monitor.clj
scheduler/src/cook/mesos/quota.clj
scheduler/src/cook/mesos/rebalancer.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/src/cook/mesos/schema.clj
scheduler/src/cook/mesos/share.clj
scheduler/src/cook/mesos/task.clj
scheduler/src/cook/mesos/util.clj
scheduler/src/cook/reporter.clj
scheduler/src/cook/util.clj
scheduler/src/metatransaction/utils.clj
scheduler/test/cook/test/authorization.clj
scheduler/test/cook/test/mesos/api.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/cook/test/mesos/task.clj
scheduler/test/cook/test/mesos/util.clj

This is a modified version of https://github.com/twosigma/Cook/pull/185 .
It has been rebased against newer master, and the conflicts have been resolved.  A couple of other incompatibilities have also been fixed.

Add authorization, operator apis, quota, reliability fixes and fail fast

---

.travis.yml
scheduler/src/cook/components.clj
scheduler/src/cook/mesos/api.clj
scheduler/test/cook/test/mesos/api.clj

This also will serve to document the newer endpoints (/share, /quota,
/retry) via swagger.

scheduler: Refactor new API endpoints to use compojure-api.

---

jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java

This pull request is to support the max_timeout feature in the job client API

Support max_runtime in job client

---

jobclient/pom.xml
jobclient/project.clj
jobclient/src/main/java/com/twosigma/cook/jobclient/Group.java
jobclient/src/main/java/com/twosigma/cook/jobclient/HostPlacement.java
jobclient/src/main/java/com/twosigma/cook/jobclient/StragglerHandling.java
scheduler/docs/groups.md
scheduler/project.clj
scheduler/src/cook/mesos.clj
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/group.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/src/cook/mesos/schema.clj
scheduler/src/cook/mesos/task.clj
scheduler/src/cook/mesos/util.clj
scheduler/test/cook/test/jobclient/jobclient.clj
scheduler/test/cook/test/mesos/api.clj
scheduler/test/cook/test/mesos/group.clj
scheduler/test/cook/test/mesos/rebalancer.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/cook/test/mesos/util.clj
scheduler/test/cook/test/testutil.clj

Add concept of straggler handling to groups. 
Clean up processing in api

Straggler handling

---

scheduler/src/cook/mesos/scheduler.clj
scheduler/test/cook/test/mesos/scheduler.clj

Fixes https://github.com/twosigma/Cook/issues/262

Issue 262 job usage bug

---

.gitignore
jobclient/src/main/java/com/twosigma/cook/jobclient/Application.java
jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/src/test/java/com/twosigma/cook/jobclient/JobClientTest.java
jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/schema.clj
scheduler/test/cook/test/mesos/api.clj

Resolves issue https://github.com/twosigma/Cook/issues/192

Adds an optional application field to the job description

---

scheduler/src/cook/mesos/dru.clj
scheduler/src/cook/mesos/rebalancer.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/test/cook/test/mesos/dru.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/metatransaction/utils_test.clj

Fixes https://github.com/twosigma/Cook/issues/254

Issue #254 refactor handle-resource-offer! and add unit tests

---

.gitignore
README.md
scheduler/Dockerfile
scheduler/bin/run-docker.sh
scheduler/bin/sample_launch.sh
scheduler/container-config.edn
scheduler/minimesosFile
scheduler/src/cook/components.clj
scheduler/test/cook/test/components.clj

This is almost entirely copied from PR #195, with some small modifications. I figure it will be good to pull out the Docker parts of that PR into this standalone PR so we can go ahead and start using them.

Adds basic docker and minimesos support

---

scheduler/minimesosFile

Minimesos HEAD expects a marathon to be running and gets an NPE otherwise:
https://github.com/ContainerSolutions/minimesos/blob/master/minimesos/src/main/java/com/containersol/minimesos/cluster/MesosCluster.java#L109

Add marathon to minimesosFile

---

scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/reason.clj
scheduler/test/cook/test/mesos/api.clj
scheduler/test/cook/test/mesos/reason.clj

scheduler: Add /failure_reasons endpoint describing known reasons.

---

integration/tests/cook/test_basic.py
jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/src/test/java/com/twosigma/cook/jobclient/JobClientTest.java
jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java
scheduler/docs/scheduler-rest-api.asc
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/schema.clj
scheduler/test/cook/test/mesos/api.clj

Adds expected-runtime to the Job description

---

CHANGELOG.md
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/quota.clj
scheduler/src/cook/mesos/schema.clj
scheduler/src/cook/mesos/share.clj
scheduler/test/cook/test/mesos/api.clj
scheduler/test/cook/test/mesos/dru.clj
scheduler/test/cook/test/mesos/mesos_mock.clj
scheduler/test/cook/test/mesos/quota.clj
scheduler/test/cook/test/mesos/rebalancer.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/cook/test/mesos/share.clj

scheduler: Require a reason for changing shares/quotas.

---

scheduler/src/cook/mesos/scheduler.clj

mapcat better expresses what is intended here

Replace flatten with mapcat

---

scheduler/src/cook/components.clj
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/scheduler.clj

Independent changes to declutter diff in cook-executor PR

Scheduler: minor refactoring and reformatting of existing code, cleanup of imports

---

scheduler/src/cook/mesos/mesos_mock.clj
scheduler/test/cook/test/mesos/mesos_mock.clj
scheduler/test/cook/test/testutil.clj

- move execution time into an environment variable.
Independent changes to declutter diff in cook-executor PR.

mesos_mock: minor refactoring and reformatting of mesos_mock

---

integration/travis/run_integration.sh
simulator/travis/run_simulation.sh
travis/minimesos
travis/minimesosFile
travis/show_executor_logs.sh

Independent changes to declutter diff in cook-executor PR

Launch scripts refactor

---

integration/setup.cfg
integration/tests/cook/test_basic.py
scheduler/src/cook/mesos/api.clj

- Make wait_for_job max delay configurable
- Increase nose process-timeout
- Add additional types to JSON string serialization

Miscellaneous fixes

---

scheduler/src/cook/mesos/scheduler.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/cook/test/testutil.clj

Revert "Refactor sort-jobs-by-dru"

---

integration/tests/cook/test_basic.py
scheduler/src/cook/mesos/api.clj

Re-throw exception in create-jobs!

---

jobclient/pom.xml
jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java

It is a mistake to use guava `ImmutableMap` as an interface of `JobClient`. Change it to `java.util.Map`

Change JobClient interface from guava Immutable to java.util.Map

---

scheduler/src/cook/mesos/scheduler.clj
scheduler/test/cook/test/mesos/scheduler.clj

Do not overwrite end-time on duplicate mesos message

---

CHANGELOG.md
scheduler/project.clj

Version 1.5.4

---

CHANGELOG.md
scheduler/project.clj

Please do not squash commits on merge

Version 1.5.6

---

integration/tests/cook/test_basic.py
scheduler/src/cook/mesos/api.clj

Fix queue endpoint

---

scheduler/docs/scheduler-rest-api.asc

Document instance parameter to /rawscheduler

---

integration/tests/cook/test_basic.py
scheduler/src/cook/mesos/api.clj

Correct handling of group query detailed option

---

integration/tests/cook/test_basic.py
scheduler/src/cook/mesos/task.clj
scheduler/src/cook/mesos/util.clj

Correct handling of docker container jobs

---

integration/Dockerfile
integration/bin/run-integration.sh
integration/tests/cook/test_basic.py
integration/tests/cook/util.py
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/task.clj
scheduler/test/cook/test/mesos/task.clj

- Change name from port-mapping to port-mappings
- Populate low port numbers (0, 1, etc) from offer similar to marathon

Fix port mapping support

---

executor/cook/executor.py
executor/tests/test_executor.py
executor/tests/utils.py

Older versions of Mesos (e.g. 0.27.1) create the `stdout` and `stderr` with only read permissions for the user running the task. As a result, the Cook executor receives a permission error when it tries to open these files in append mode. Instead, we can pass in the stdout/stderr file descriptors to the child process.
Note: This issue does not occur in later versions of Mesos (e.g. 1.2) where the `stdout` and `stderr` files are created with read/write permissions of the user running the task.

Forward standard stdout and stderr files while launching process

---

integration/tests/cook/test_basic.py
integration/tests/cook/util.py
scheduler/src/cook/mesos/api.clj

Allow killing a group of jobs

---

integration/tests/cook/reasons.py
integration/tests/cook/test_basic.py
integration/tests/cook/util.py

Fix flaky integration test for max_runtime_exceeded

---

integration/bin/single-test.sh

I find this utility script useful for debugging failed tests.

Add single-test.sh script for integration testing

---

integration/tests/cook/test_basic.py

Allow EXECUTOR_UNREGISTERED failed job reason for group_kill_simple

---

integration/tests/cook/util.py

Delete redundant all_instances_killed def

---

executor/cook/executor.py
executor/setup.py

upgrades pymesos version to 0.2.15

---

executor/cook/_version.py
scheduler/CHANGELOG.md
scheduler/project.clj

Please 
- do not squash during merge
- choose the rebase and merge option
- excuse the name of the branch.

Version 1.8.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

Version 1.8.1

---

scheduler/src/cook/mesos/constraints.clj
scheduler/src/cook/mesos/scheduler.clj

Please hold off on this PR until I have time to do a simulator run to make sure it actually helps. Just wanted to get the travis build going.

Defer calculation of group components until constraint construction

---

scheduler/src/cook/mesos/scheduler.clj
scheduler/test/cook/test/mesos/scheduler.clj

Use millisecond time resolution for lingering tasks

---

scheduler/CHANGELOG.md
scheduler/project.clj

Version 1.8.2

---

integration/tests/cook/test_basic.py

Mark test_balanced_host_constraint_cannot_place as explicit

---

executor/cook/__init__.py
executor/cook/__main__.py
executor/cook/_version.py
executor/cook/executor.py
executor/requirements.txt
executor/tests/test_executor.py
executor/tests/utils.py

Here are snippets of how the `executor.log` looks like:
```
2017-11-21 12:33:20,821 INFO Updating task 9f3024df-02cf-4399-9dcf-a9e83c51228f state to TASK_FAILED
2017-11-21 12:33:20,824 INFO Sending kill signal to group (id: 35973)
2017-11-21 12:33:20,824 INFO CookExecutor has completed
2017-11-21 12:33:20,825 INFO Unable to find group (id: 35973) to send kill signal
2017-11-21 12:33:20,825 INFO MesosExecutorDriver requested to stop
2017-11-21 12:33:20,825 INFO MesosExecutorDriver has been stopped
2017-11-21 12:33:20,825 INFO Waiting up to 1 second(s) for CookExecutor to disconnect
2017-11-21 12:33:20,826 INFO Mesos requested executor to disconnect
2017-11-21 12:33:20,826 INFO Executor exiting with code 0
```
```
2017-11-21 12:34:23,032 INFO Updating task …
```

ensures driver is stopped after task completes execution

---

executor/cook/executor.py
executor/cook/progress.py
executor/tests/test_executor.py
executor/tests/test_progress.py

checks for maximum length validations for progress messages

cook executor - checks for maximum length validations for progress messages

---

executor/cook/progress.py
executor/tests/test_executor.py
executor/tests/utils.py

Before the logging changes:
After the logging changes:

Reduces logging overheads - progress reporting performance

---

integration/tests/cook/test_basic.py

- integration tests to verify memory limit exceeded behavior
- To verify that the Cook Executor supports the same behavior as Mesos' Command executor when memory limit is exceeded

adds integration tests to verify container memory limit exceeded behavior

---

executor/cook/io_helper.py

- changes call from [`readline()`](https://docs.python.org/3/library/io.html?highlight=bufferedreader#io.IOBase.readline) to [`read1()`](https://docs.python.org/3/library/io.html?highlight=bufferedreader#io.BufferedReader.read1) to improve speed of output syncing
The stdout and stderr syncer is much slower than the Mesos `CommandExecutor` version. We wish to lower the performance gap by optimizing the stdout/stderr writers.
- I did not use [`readinto`](https://docs.python.org/3/library/io.html?highlight=bufferedreader#io.BufferedIOBase.readinto) or `readinto1` suggested in [this article](http://rabexc.org/posts/io-performance-in-python) as I would then need to manually create the byte array to send to write.
- The command `python3 -c '[print("Hello:",i) for i in range(10000000)]'` runtime …

Improve stdout and stderr processing speed

---

scheduler/CHANGELOG.md
scheduler/project.clj

**Note**: Please select the rebase and merge option.
- Please see the changelog
Cutting for a new release.

Version 1.8.3

---

integration/tests/cook/test_basic.py
scheduler/src/cook/mesos/api.clj

- Fix bug with NPE on group show of invalid group
- Add an integration test for this case
Apparently we have something against NPEs.

Fix NPE for nonextant group show

---

cli/README.md
cli/cook/cli.py
cli/cook/mesos.py
cli/cook/querying.py
cli/cook/subcommands/cat.py
cli/cook/subcommands/tail.py
cli/cook/version.py
integration/tests/cook/cli.py
integration/tests/cook/test_cli.py

- adds `cs cat`
- adds integration tests for it
- adds docs for it
We already have `ls` and `tail`, and `cat` is useful and simple.

Adds cat sub-command to cs

---

integration/tests/cook/util.py

- Use a common constant for most `wait_until` timeout duration in our integration test utilility functions.
- Specifically bumps the `wait_for_exit_code` duration up from the current value of 2 seconds (which was causing lots of failures in Travis) to the new default duration of 2 minutes.
We had fairly arbitrary duration values scattered throughout our utility functions, so using a single constant should make the utility functions' behavior easier to predict. Since we expect failure to occur infrequently, waiting for 2 minutes by default will hopefully lessen the number of spurious failures without impacting our average test completion times.

Normalize wait_until timeout in integration tests

---

jobclient/src/main/java/com/twosigma/cook/jobclient/Instance.java
jobclient/src/test/java/com/twosigma/cook/jobclient/InstanceTest.java

- adds support for progress percent and message to the instance
Allows users of the job client to query the instance for progress message and percent.

Job Client: adds support for progress percent and message to the instance

---

scheduler/src/cook/mesos/scheduler.clj

- adds metrics for rate of receiving Mesos status updates and framework messages
- also reformats the code in create-mesos-scheduler
It helps us track the rate at which the scheduler is receiving messages and status updates from the Mesos executor.
Viewing the code [with whitespace diffs ignored](https://github.com/twosigma/Cook/pull/654/files?w=1) simplify the review.

CS: adds metrics for rate of receiving Mesos status updates and framework messages

---

scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/constraints.clj
scheduler/src/cook/mesos/mesos_mock.clj
scheduler/src/cook/mesos/rebalancer.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/src/cook/mesos/unscheduled.clj

- Small refactoring suggested by kibit
Cleanup of code to use common Clojure idioms.

CS: refactors code using suggestions from kibit

---

cli/README.md

- changing several subcommand headings to the correct heading level
To make formatting consistent.

Fixes formatting in cs README

---

integration/tests/cook/test_basic.py

- Fix logic for handling multiple jobs in attribute_equals test
The existing code had the commands flipped: there would be one job which slept for 600 seconds and several jobs that exited immediately, instead of the other way around. The jobs could then complete serially on the same host and cause the test to fail.

Fix logic for multiple jobs in attribute equals test

---

scheduler/test/cook/test/mesos/api.clj

- adding `test-fetch-job-with-no-name`, a unit test that asserts that a job with no name field can be retrieved via the api
We want to ensure that any jobs in the database without a name can continue to be fetched via the API.

Adds test for fetching a job with no name

---

jobclient/src/main/java/com/twosigma/cook/jobclient/constraint/Constraints.java
jobclient/src/main/java/com/twosigma/cook/jobclient/constraint/OneToOneConstraint.java

Adds missing checked exceptions to JSON-related methods.
@WenboZhao asked for these to be added.

Add missing checked exceptions for JSON conversions

---

integration/tests/cook/util.py

Cache users' Kerberos tickets during integration tests.
This speeds up the integration tests a bit when using Kerberos, as this version only creates one subprocess for each unique user, rather than one per user per test.
I've tested this patch on a Kerberos cluster. The tests passed, and they seemed noticeably faster.

Cache users' kerberos tickets during integration tests

---

scheduler/CHANGELOG.md
scheduler/project.clj

- filling in the CHANGELOG information for this release
- bumping the version (in two separate commits)
We would like to release the latest batch of enhancements.

Updates CHANGELOG and version for 1.11.0

---

scheduler/config.edn

- sorts `config.edn`
Sorting the file makes it easier to find config entries

cs: refactor: sorts config.edn

---

scheduler/project.clj
scheduler/src/cook/mesos/util.clj
scheduler/test/cook/test/mesos/api.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/cook/test/mesos/util.clj
scheduler/test/cook/test/testutil.clj

- Cache job resources, task->user mapping, and job categories.
- 
- 
Improves performance of various scheduler tasks.

Added resource and job category caching.

---

integration/tests/cook/test_basic.py
integration/travis/scheduler_travis_config.edn
scheduler/config.edn
scheduler/src/cook/components.clj
scheduler/src/cook/config.clj
scheduler/src/cook/cors.clj
scheduler/src/cook/mesos/api.clj
scheduler/test/cook/test/cors.clj
scheduler/test/cook/test/mesos/api.clj

- Adds new middleware for supporting CORS requests
Support apps making requests to Cook from a different origin

Add CORS middleware

---

scheduler/test/cook/test/mesos/util.clj

- Name some jobs.
- 
- Was having trouble figuring out why my test was failing. This makes it easier.

Add names to some jobs in unit tests.

---

scheduler/src/cook/components.clj

- fixing gpu support
- working is better then don't

fix gpu support

---

integration/tests/cook/test_basic.py

- returning early if there aren't enough agents to satisfy the retries
Resolves https://github.com/twosigma/Cook/issues/735

resolves issue #735 by returning early if there aren't enough agents to satisfy the retries

---

scheduler/src/cook/mesos/pool.clj
scheduler/src/cook/mesos/util.clj

- Convert pool query logic to pure function call
- Easier to read
- Easier to reuse
- Better performance
```
New (no pool)
Evaluation count : 83280 in 60 samples of 1388 calls.
Execution time mean : 724.906725 µs
Execution time std-deviation : 7.126763 µs
Execution time lower quantile : 717.701292 µs ( 2.5%)
Execution time upper quantile : 740.208994 µs (97.5%)
Overhead used : 1.565043 ns
Found 3 outliers in 60 samples (5.0000 %)
low-severe	 1 (1.6667 %)
low-mild	 2 (3.3333 %)
Variance from outliers : 1.6389 % Variance is slightly inflated by outliers
Old (no pool)
Evaluation count : 40980 in 60 samples of 683 calls.
Execution time mean : 1.470291 ms
Execution time std-deviation : 8.615948 µs
Execution time lower quantile : 1.453152 ms ( 2.5%)
Execution time upper quantile : 1.486338 ms …
```

Convert pool query to function call

---

integration/tests/cook/test_basic.py

- setting max retries to 2 for the "fast" job in the group
- adding an earlier assertion that the "fast" job succeeded
We've seen this test fail because the "fast" job failed instead of succeeding. I don't know what causes this, but we should be a little more resilient by adding a second attempt if the first one fails.

Makes test_group_kill_simple more reliable

---

integration/Dockerfile
integration/tests/cook/test_basic.py
integration/tests/cook/util.py
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/monitor.clj
scheduler/src/cook/mesos/pool.clj
scheduler/src/cook/mesos/quota.clj
scheduler/src/cook/mesos/ranker.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/src/cook/mesos/schema.clj
scheduler/src/cook/mesos/share.clj
scheduler/src/cook/mesos/unscheduled.clj
scheduler/test/cook/test/benchmark.clj
scheduler/test/cook/test/mesos/api.clj
scheduler/test/cook/test/mesos/dru.clj
scheduler/test/cook/test/mesos/mesos_mock.clj
scheduler/test/cook/test/mesos/quota.clj
scheduler/test/cook/test/mesos/rebalancer.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/cook/test/mesos/share.clj
scheduler/test/cook/test/mesos/unscheduled.clj
scheduler/test/cook/test/simulator.clj

- Adds pool support to the quota and share endpoints
This is part of adding pool support to all of the relevant scheduler endpoints

Add pool support to share and quota endpoints

---

integration/tests/cook/test_multi_user.py

- setting `max_retries` to 2 for the jobs submitted
- dumping sandbox files for any failed instances (which we don't expect)
We've seen this test fail because one of the jobs completes prematurely, presumably because it failed, and we want to be able to track down why.

Adds debugging info to test_multi_user_usage

---

integration/tests/cook/test_basic.py

- setting `max_retries` to 2 for the jobs we expect to succeed
- logging and asserting on the job status before running the `/jobs` queries
We've seen this test fail due to:
```bash
./master-logs/mesos-master.INFO:I0502 23:23:15.970085    13 master.cpp:5190] Sending status update TASK_ERROR for task 904aa052-91bb-4a48-bfe6-2e7d8def11a8 of framework cook-framework-1 'Task uses more resources mem(cook):256; cpus(cook):0; cpus(*):1 than available ports(cook):[32000-33000]; mem(cook):2816; disk(cook):10000; ports(*):[31000-32000]; disk(*):10000; cpus(*):3; mem(*):4096'
```
And we want to have more information / prevent it going forward.

Add debug info to test_list_jobs_by_completion_state_with_jobs_endpoint

---

integration/tests/cook/test_basic.py

- preventing mea culpa failures, such as `Invalid Mesos offer`, from breaking the test
We have seen this test fail with:
```bash
____________ CookTest.test_no_cook_executor_on_subsequent_instances ____________
[gw0] linux -- Python 3.6.3 /opt/python/3.6.3/bin/python3.6
self = <tests.cook.test_basic.CookTest testMethod=test_no_cook_executor_on_subsequent_instances>
def test_no_cook_executor_on_subsequent_instances(self):
retry_limit = util.get_in(util.settings(self.cook_url), 'executor', 'retry-limit')
if retry_limit is None:
self.logger.debug("Cook executor is not configured (retry-limit is None)")
return
else:
num_hosts = len(util.get_mesos_state(self.mesos_url)['slaves'])
if retry_limit >= num_hosts:
self.logger.debug("Skipping test as not enough agents to verify Mesos executor on …
```

Makes test_no_cook_executor_on_subsequent_instances more reliable

---

integration/tests/cook/test_basic.py

- giving the job we expect to get to running a second attempt
We've seen this test fail due to:
```bash
./log/cook-12321.log:2018-05-18 16:48:50,763 INFO  cook.mesos.scheduler [clojure-agent-send-pool-0] - Mesos status is: #mesomatic.types.TaskStatus{:task-id #mesomatic.types.TaskID{:value 82883296-0ca4-4910-8313-d164b1d74937}, :state :task-error, :message Task uses more resources mem(cook):256; cpus(cook):0; cpus(*):1 than available mem(cook):3072; mem(*):4096; cpus(*):4; ports(cook):[32000-33000]; disk(cook):10000; ports(*):[31000-32000]; disk(*):10000, :source :source-master, :reason :reason-task-invalid, :data #object[com.google.protobuf.LiteralByteString 0x6cf121d9 <ByteString@6cf121d9 size=0>], :slave-id #mesomatic.types.SlaveID{:value f13b23eb-1d15-4fd4-a121-87d5038b967c-S3}, …
```

Makes test_retries_unchanged_conflict more resilient

---

scheduler/src/cook/mesos/constraints.clj
scheduler/test/cook/test/mesos/constraints.clj

- adding checks for `nil` before calling `.getTime` on the instance timestamps
We've seen this cause NPEs.

Checks for nil timestamps when calculating instance runtime

---

scheduler/CHANGELOG.md
scheduler/project.clj

- bumping the version (in 2 separate commits)
To release the bug fix described below.

Updates changelog and version for v1.17.1

---

scheduler/src/cook/mesos/scheduler.clj
scheduler/test/cook/test/mesos/scheduler.clj

- Fix bug with `processed-tasks` in `reconcile-tasks`
Reconciliation is currently not working

Fix bug causing reconciliation to fail

---

scheduler/src/cook/mesos/sandbox.clj

- removes superfluous logs from the sandbox publisher
Avoids confusion due to the presence of the logs on multiple Cook nodes in a cluster. Now the logs will only appear if the syncer is publishing sandbox directories.

removes superfluous logs from the sandbox publisher

---

integration/README.md

- Tip for getting the integration tests running.
- 
- 
- I tripped up on this when trying to run the integration tests locally.

Docfix for integration tests.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- adding issue templates for bug reports and feature requests
To make it easier for people to create issues with complete information.

Creates issue templates

---

integration/tests/cook/test_basic.py

- isntead of running `docker inspect` with the container name, first running `docker ps --filter "name=..."` to retrieve the container ID, and then running `docker inspect` with the ID
We have seen (not consistently, but fairly commonly) the `docker inspect` fail with:
```bash
Error response from daemon: no such image: mesos-d3a14998-5e06-4d5f-8328-330c61bf1467-S2.21d645d8-dea6-4798-893c-64de3a4d6f4e: invalid reference format: repository name must be lowercase
```
It's not entirely clear what causes that, but the hope is that this change will avoid this type of error.

Uses docker ps --filter 'name=...' to retrieve container id

---

scheduler/src/cook/components.clj

- Read entire request before sending response
This makes Cook play nicer with most proxies. Without consuming a large request before sending a response (on a 401 for instance) it can lead to the connection with the proxy being closed before the proxy reads the response from cook. This change causes cook to read the entire request before sending the response.

Add consume-request-stream

---

integration/tests/cook/test_multi_user.py
integration/tests/cook/util.py
integration/travis/scheduler_travis_config.edn
scheduler/config.edn

- adding an integration test that triggers task preemption
We don't currently have any integration tests for the preemption path.

Adds integration test for task preemption

---

scheduler/CHANGELOG.md
scheduler/project.clj

Outgoing/release v1.19.1

---

integration/tests/cook/test_impersonation.py
scheduler/src/cook/impersonation.clj

The impersonation header is ignored in the case when the impersonating-user and the impersonated-user principals are equal.
This simplifies testing code for one of our users. It can be hard to determine the user principal of the current kerberos ticket from a Java client, so we're handling this on the server instead.

Allow self-impersonation requests from normal users

---

integration/tests/cook/test_cli.py

- adding a retry to the notebook pre-processing
- only deleting the executed notebook if it was created
We've seen this test flake due to the pre-processing step failing, e.g.:
```bash
2018-08-29 21:21:32,845 [INFO] Executing notebook with kernel: python3
2018-08-29 21:21:34,042 [DEBUG] Starting kernel: ['/opt/python/3.6.3/bin/python3.6', '-m', 'ipykernel_launcher', '-f', '/tmp/tmp4h4_ykbf.json']
2018-08-29 21:21:34,060 [DEBUG] Connecting to: tcp://127.0.0.1:47627
2018-08-29 21:21:34,338 [DEBUG] connecting shell channel to tcp://127.0.0.1:35840
2018-08-29 21:21:34,339 [DEBUG] Connecting to: tcp://127.0.0.1:35840
2018-08-29 21:21:34,345 [DEBUG] connecting iopub channel to tcp://127.0.0.1:57587
2018-08-29 21:21:34,345 [DEBUG] Connecting to: tcp://127.0.0.1:57587
2018-08-29 21:21:34,348 …
```

Makes test_show_from_jupyter more reliable

---

scheduler/CHANGELOG.md
scheduler/project.clj

- updating changelog for `1.20.0`
To release `1.20.0`.

Release 1.20.0

---

integration/tests/cook/test_basic.py

- filtering out mea-culpa failures from two assertions
We've seen this test flake when instances have mea-culpa failures such as "Invalid Mesos offer".

Makes test_instance_stats_failed more reliable

---

scheduler/CHANGELOG.md
scheduler/project.clj

- adding to the changelog for v1.21.0
- bumping the version (in two separate commits)
To release the new version.

Release v1.21.0

---

jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java

- Add datasets field to jobclient
Allow users to submit jobclient jobs with datasets

Add datasets to jobclient Job

---

integration/travis/run_integration.sh
scheduler/bin/run-docker.sh

- Fixes setting up the data local environment in run-docker.sh
So that the dummy data local service is started correctly.

Fix run-docker.sh

---

scheduler/src/cook/mesos/dru.clj
scheduler/src/cook/mesos/monitor.clj
scheduler/src/cook/mesos/rebalancer.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/test/cook/test/benchmark.clj
scheduler/test/cook/test/mesos/dru.clj
scheduler/test/cook/test/mesos/scheduler.clj

- Moves additional scheduler metrics to be pool-specific
Provide more accurate metrics for each pool

Move additional metrics to pool-specific metrics

---

scheduler/test/cook/test/simulator.clj

- adds the ability to run optimizer queries at intervals during simulation
It is possible that the optimizer server takes long to respond to queries. Allowing the simulator to invoke the optimizer at intervals allows us to support the use-case that the simulator and the ranker/matcher can run independently of each other.

adds the ability to run optimizer queries at intervals during simulation

---

scheduler/test/cook/test/simulator.clj

- adds support for incremental output of completed tasks in the simulator
We would like to get quicker feedback than having to wait for the simulator to end running before seeing the list of completed tasks.

adds support for incremental output of completed tasks in the simulator

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Release 1.25.0 with launch rate limits.
- 
-

Release v1.25.0

---

scheduler/src/cook/mesos/scheduler.clj

- This rename was missed in pool rollout.
- 
-

Rename fix for pool variable.

---

integration/tests/cook/test_multi_user.py
scheduler/src/cook/mesos/scheduler.clj
scheduler/test/cook/test/mesos/scheduler.clj

- Alter how we do rate limiting. 
Instead of sending all or none of a users considerable jobs based on whether they're in or out of debt. A user with N tokens can only launch at most n jobs. This has two consequences. First, a user's launches will be spread out more over time. E.g., if we have 5 launches/second, instead of E.g., 200 launches every 40 seconds, it would be 25 launches 5 second (one scheduler cycle). Another consequence is that a user never goes into debt in the rate limit filtering, and the rate limit filtering is a bit tighter. 
We think it has nicer ergonomics.

gradual launch rate limit

---

scheduler/src/cook/mesos/scheduler.clj

- This code is dead. It seems to have been replaced with the new code in cook.mesos.constraints
- 
-

Cleanup code.

---

scheduler/src/cook/mesos/util.clj

- Remove jobs-by-user-and-state
Dead code.

Remove jobs-by-user-and-state

---

scheduler/src/cook/mesos/constraints.clj

- Small tweak from review feedback on last request.
- 
-

Add comment and review feedback

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release 1.26.0

---

integration/tests/cook/test_basic.py

- adding `-9` as an allowable exit code for the python script
- removing the `skipUnless` that keeps the test from running locally
We've seen the exit code `-9` happen in the wild. As for removing the `skipUnless`, this test passes reliably in my local environment, and I think it would be good for devs to be running it.

Makes test_memory_limit_exceeded_cook_script more reliable

---

scheduler/test/cook/test/mesos/scheduler.clj

- Add a missing `setup` call to fix the benchmark suite
To fix the benchmark suite

Fix benchmark suite

---

integration/tests/cook/test_basic.py
integration/tests/cook/util.py
scheduler/project.clj
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/schema.clj
scheduler/src/cook/mesos/task.clj
scheduler/test/cook/test/mesos/task.clj

- Adds support for docker images in mesos containerizer
Allows users to use docker images while still using the Mesos Containerizer.

Add support for images in mesos containerizer

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release 1.27.0

---

jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java
jobclient/src/main/java/com/twosigma/cook/jobclient/JobClientInterface.java
jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java

- Add pool parameter to job client submit instead of job builder
The current code is incorrect

Add pool parameter to jobclient submit

---

jobclient/pom.xml
scheduler/project.clj

Please rebase this PR instead of squashing

Release jobclient 0.4.0

---

scheduler/src/cook/config.clj

- Copy over the entire :plugin map from the config.
- 
- 
So we have a place to put plugin-relevant arguments.

Copy over the entire :plugins subkey from the config map.

---

integration/requirements.txt

- Pin dependency on tornado version 5.1.1
Fix nbconvert integration test

Fix tornado dependency

---

scheduler/src/cook/plugins/launch.clj
scheduler/src/cook/plugins/submission.clj

-  Make this plugin exposed, so that we can default to it in cluster-specific config files more easily.
- 
-

Expose accept-all-plugin

---

integration/tests/cook/cli.py

- Actually load the environment variable `COOK_PLUGIN_JSON` into a base config file when running integration tests.
This pull request completes the work done in #1086 which allows us to run the integration tests using our own internal plugins by specifying them in an environment variable.

Adding env plugins to base config test file

---

scheduler/README.adoc

- fixing wording in the scheduler README
Correctness.

Fixes wording in scheduler README

---

integration/tests/cook/test_basic.py

- Move the output URL check into a separate test (from `basic_submit`)
This runs the output URL check in a separate test with a longer-running job. This will ensure that the sandbox syncer has time to run on that task.

Move output url check to separate test

---

integration/tests/cook/util.py

- Add a `try...except` around the check for supported isolators
Improves test reliability

Catch error in supported isolators

---

scheduler/src/cook/components.clj
scheduler/src/cook/config.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/src/cook/plugins/completion.clj
scheduler/src/cook/plugins/definitions.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/cook/test/simulator.clj

- Adds a new plugin to be invoked on instance completion 
Allows custom integrations to be run on instance completion.

Add instance completion plugin

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release version 1.29.0

---

executor/RELEASING.md

- Add a RELEASING.md doc for cook executor
Describe the process for releasing a new executor version to PyPI

Add RELEASING.md

---

executor/cook/_version.py

Release executor version 0.1.13

---

integration/tests/cook/test_basic.py

- Change the reset_vars test to check the value of `EXECUTOR_RESET_VARS`, and check those variables if configured.
Since a job cannot override `EXECUTOR_RESET_VARS` if it's specified in the config, the test will fail. This allows the test to work in both kinds of environments.

Update reset_vars test to work when EXECUTOR_RESET_VARS is configured

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release version 1.30.0

---

integration/tests/cook/test_basic.py
integration/tests/cook/test_cli.py

- Xfail these.
- 
- 
Over the course of trying to get a different patch done, I had to rerun integration tests multiple times because of these spurious failures.

Xfail some flaky tests

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release 1.30.1

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release version 1.31.0

---

scheduler/src/cook/components.clj
scheduler/src/cook/compute_cluster.clj
scheduler/src/cook/mesos.clj
scheduler/src/cook/mesos/api.clj
scheduler/src/cook/mesos/rebalancer.clj
scheduler/src/cook/mesos/scheduler.clj
scheduler/src/cook/mesos/task.clj
scheduler/src/cook/task.clj
scheduler/src/cook/test/testutil.clj
scheduler/test/cook/test/compute_cluster.clj
scheduler/test/cook/test/mesos/api.clj
scheduler/test/cook/test/mesos/mesos_mock.clj
scheduler/test/cook/test/mesos/scheduler.clj
scheduler/test/cook/test/simulator.clj

- Refactor driver propagation into the new compute-cluster.
- 
- 
Preparation for kubernetes support.

Refactor driver into compute-cluster throughout cook

---

integration/tests/cook/test_master_slave.py

- Use a bad constraint instead of submitting many jobs in `test_get_queue`
Makes the test more reliable.

Use bad constraint in test_get_queue

---

scheduler/src/cook/components.clj
scheduler/src/cook/compute_cluster.clj
scheduler/src/cook/mesos.clj
scheduler/src/cook/mesos/mesos_compute_cluster.clj
scheduler/src/cook/mesos/task.clj
scheduler/src/cook/scheduler/scheduler.clj
scheduler/src/cook/test/testutil.clj
scheduler/test/cook/test/compute_cluster.clj
scheduler/test/cook/test/mesos/task.clj
scheduler/test/cook/test/scheduler/scheduler.clj

- Refactor launch task so it occurs behind the ComputeCluster API.
- 
-

Refactor launch task

---

integration/Dockerfile
integration/bin/run-integration.sh
integration/tests/cook/test_basic.py
integration/travis/scheduler_travis_config.edn
scheduler/config.edn
scheduler/src/cook/config.clj
scheduler/src/cook/mesos/task.clj
scheduler/src/cook/tools.clj
scheduler/test/cook/test/mesos/task.clj

- Adds support for default container images
Supports adding default container volumes for all jobs.

Add default container volumes

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release 1.32.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release 1.32.1

---

.github/mergeable.yml

- Add `mergeable.yml`
Enforce `internal-green` label

Add mergeable.yml

---

scheduler/src/cook/components.clj
scheduler/src/cook/rest/api.clj

- Log errors in `render-error` at info level
- Log unhandled exceptions
More visibility into errors encountered by users

Add additional error logging

---

integration/tests/cook/test_basic.py
integration/tests/cook/util.py
integration/travis/scheduler_travis_config.edn
scheduler/config.edn
scheduler/src/cook/plugins/demo_plugin.clj
scheduler/src/cook/plugins/submission.clj
scheduler/test/cook/test/plugins/submission.clj

- Adds support for multiple submit plugins
To use multiple submit plugins

Add support for multiple submit plugins

---

scheduler/src/cook/kubernetes/api.clj
scheduler/src/cook/kubernetes/compute_cluster.clj
scheduler/src/cook/kubernetes/controller.clj
scheduler/test/cook/test/kubernetes/api.clj
scheduler/test/cook/test/kubernetes/compute_cluster.clj

- Make the code work with minikube ot the point of using the state machine to successfully launch and kill jobs.
- 
- 
- They make us able to run kubernetes jobs via our state machine.

kubernetes integration draft

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release 1.33.0

---

scheduler/src/cook/kubernetes/api.clj
scheduler/src/cook/kubernetes/controller.clj
scheduler/test/cook/test/kubernetes/compute_cluster.clj
scheduler/test/cook/test/kubernetes/controller.clj

- Added some deftest stubs for us to fill in.
- 
- 
Indicate the deftests we want to implement as TODO's.

Added some deftests and other small cleanups.

---

scheduler/src/cook/kubernetes/controller.clj

- Change the message
- 
- 
We know the state, we just haven't added the term for diagnosing the failure reason (if any)

Clarify a confusing log message.

---

scheduler/src/cook/rest/api.clj

- Metric the rate and time it takes to fetch an instance map
- 
- 
Better metrics

Metric on instance fetch rates.

---

scheduler/CHANGELOG.md
scheduler/project.clj

- populating the changelog
- bumping the vserion
To release Cook.

Updates CHANGELOG and version for 1.34.0

---

scheduler/src/cook/rebalancer.clj
scheduler/src/cook/tools.clj

-  Add a couple of comments that came up in discussion
- 
- 
Explaining why we are doing things and how they work helps people understand the code.

Improve docs in sorting jobs and for rebalancer.

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.34.1

---

scheduler/src/cook/kubernetes/api.clj

- Fix arity bug in initialize-pod-watch
- 
- 
If we don't, the watch will die and not recover.

Fix arity bug in initialize-pod-watch

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for 1.34.2

---

integration/tests/cook/util.py

- Improve logging around user session changing.
Make diagnosing what actually occurred a little bit easier.

Better logging messages for integration test user changing.

---

scheduler/bin/gcloud-make-for-integration.sh
scheduler/bin/make-gke-test-cluster
scheduler/docs/make-kubernetes-namespace.json

- A script for making a GKE cluster for running tests.
Make it easy to replicate a test environment.

Configure a GKE kubernetes cluster on GKE for running tests.

---

integration/tests/cook/test_basic.py
integration/tests/cook/test_multi_user.py
integration/travis/run_integration.sh
scheduler/config-k8s.edn
scheduler/src/cook/config.clj
scheduler/src/cook/kubernetes/api.clj
scheduler/src/cook/rest/api.clj
scheduler/test/cook/test/kubernetes/api.clj
scheduler/test/cook/test/kubernetes/compute_cluster.clj

- Add support for `workdir`, `env`, and `docker` parameters
Increase support for the existing mesos API

Add support for user, workdir, and env docker parameters

---

scheduler/src/cook/mesos.clj

- Add a comment
Document a weird metric

Add a comment

---

integration/tests/cook/test_basic.py

- making `test_failing_submit` and `test_change_retries` tolerate "extra" failed instances due to e.g. "Agent removed"
In environments with preemptible hosts, we can get unlucky and get preempted in the middle of a test.

Makes two tests resilient to "Agent removed"

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.35.0

---

scheduler/docs/reason-code

Update docs to add 99003 reason code
A user got a 99003 user code and this document didn't cover it.

Add 99003 to reason code documentation

---

integration/tests/cook/test_multi_user.py

- fixing a bug that was introduced in a recent PR
So the test can pass.

Fixes test_instance_stats_running

---

scheduler/src/cook/kubernetes/api.clj
scheduler/src/cook/kubernetes/compute_cluster.clj

- Increase visibility when we are processing a pod.
Improve visibility for why we're processing a change. Help diagnose a weird pod lifecycle bug.

Indicate when we're processing a given change.

---

scheduler/src/cook/kubernetes/controller.clj

- Explicitly report when we think a pod is deleted
- Help trace down a weird pod lifecycle bug.

Report when we detect a pod as deleted

---

scheduler/src/cook/kubernetes/controller.clj

- Add a type annotation to make things more clear.
Catch some bugs or other weird invocations.

Add a type annotation to make things more clear.

---

scheduler/bin/help-delete-temporary-clusters
scheduler/bin/help-make-cluster
scheduler/bin/make-gke-test-clusters

- Make a single cluster or make more than one cluster.
Prepare for making multiple clusters for the multi-cluster kubernetes support in progress

New scripts for making GKE clusters.

---

scheduler/src/cook/mesos/mesos_compute_cluster.clj

- Improve the logging so that we unambiguously log when the driver join! unblocks.
Help debug/understand this code for our leadership changes/refactors.

Add more logging when we join on the mesos driver

---

scheduler/src/cook/scheduler/scheduler.clj
scheduler/test/cook/test/scheduler/scheduler.clj

- catching inside the `doseq` that iterates over compute clusters calling `launch-tasks`
We don't want an error launching tasks in one compute cluster to cause other compute clusters to not launch tasks.

Prevents errors in launch-tasks from one compute cluster affecting others

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Release next version of cook
We want this cook in production.

Outgoing/release 1.36.0

---

scheduler/src/cook/scheduler/scheduler.clj

- Revert a change that added extra logging to jobs being considered for scheduling.
These slow down resource offer handling.

Remove extra logging that makes computing the result more expensive.

---

scheduler/Dockerfile

- Reduce the layers in the docker image.
Smaller docker images and faster to build

Some more tweaks to de-layer docker image

---

integration/tests/cook/test_multi_user.py

- increasing the `stop_max_delay` to 4 minutes
- logging when there's an exception
- logging the sleep amount
- moving the sleep to the `finally` block
We need to earn back the tokens when the assertions fail so that the next attempt has a shot at succeeding with a clean slate. So the earning back logic needs to be in the `finally`. The `stop_max_delay` was inappropriate because if we're going to sleep for 70 seconds to earn back tokens, the max delay can't be less than that.

Makes test_rate_limit_while_creating_job more reliable

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.36.2

---

integration/tests/cook/test_basic.py

- stop assuming that all failed instances are `Mesos executor terminated`
There can be other failures, e.g. `Agent removed`.

Makes test_mea_culpa_retries more reliable

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.37.0

---

scheduler/test/cook/test/rest/api.clj

- fixes the failing tests after sandbox refactoring
The `api/retrieve-url-path` function was renamed to `api/retrieve-sandbox-url`. Now some unit tests that were excluded from the refactoring are failing.

fixes the failing tests after sandbox refactoring

---

scheduler/test/cook/test/kubernetes/api.clj

fix test-task-metadata->pod unit test

fix test-task-metadata->pod unit test

---

cli/cook/querying.py
cli/cook/subcommands/cat.py
cli/cook/subcommands/ls.py
cli/cook/subcommands/ssh.py
cli/cook/subcommands/tail.py

use plugin to ssh to kubernetes
we can't use ssh directly when a job is scheduled on kubernetes - we need to use kubectl

ssh cli support for kubernetes

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.38.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.38.1

---

scheduler/CHANGELOG.md
scheduler/project.clj

Revert "Updates changelog and version for v1.38.1"

---

integration/tests/cook/test_basic.py

We need to wait for the job to complete in this test.
If we only wait until Running, the job might start running, then the instance might fail with e.g. "Agent removed", and then we'd have to wait for it to get scheduled again but we'd already have moved past this wait, which can cause the test to flake.

Makes test_progress_update_submit more reliable

---

scheduler/src/cook/kubernetes/api.clj

- adding logging around the node and pod watches
- making sure to have `pod watch` / `node watch` in each of the relevant logs for search-ability
To make it easier to track what Cook is doing when an error happens, e.g. when connecting to k8s for the watches.

Adds logging around node and pod watches

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.38.3

---

scheduler/CHANGELOG.md
scheduler/project.clj

- updates changelog
- bumps version

Updates changelog and version for v1.38.4

---

integration/tests/cook/test_basic.py
integration/tests/cook/util.py

- Fix integration test that attempts to submit a bad job with no image.
Avoid a false positive error log.

Fix integration test that attempts to submit a bad job with no image.

---

scheduler/src/cook/kubernetes/api.clj
scheduler/src/cook/kubernetes/compute_cluster.clj
scheduler/src/cook/kubernetes/controller.clj
scheduler/test/cook/test/kubernetes/api.clj
scheduler/test/cook/test/kubernetes/compute_cluster.clj

- Fix a bunch of indentation bugs I found in recent work.
- Make future code and reviews easier.
- Fewer whitespace changes in future diffs.

Fix indentation in k8s code.

---

scheduler/src/cook/rest/api.clj

- changing the job response schema from `NonNegInt` to `Int`
- adding a warning log when the retries remaining is negative
There's a bug in the retries remaining logic that causes this number to sometimes be negative. It's not clear yet where/what the bug is, but when it happens, this schema is causing us to not be able to query the job through the API, which is frustrating for users and makes it very difficult to track down the bug. So, while we're not yet fixing the bug, we're making it easier to troubleshoot by making the response schema less strict.

Makes negative retries remaining easier to troubleshoot

---

scheduler/src/cook/kubernetes/compute_cluster.clj

- preventing exceptions from blowing past the `doseq`s in these functions
To get better logging and to prevent a local issue from affecting other tasks.

Adds exception handling to scan-tasks and launch-tasks

---

scheduler/src/cook/kubernetes/api.clj

- enable tty in kubernetes containers
allocate a TTY to support tools that need to read from stdin

add tty support

---

cli/cook/subcommands/ls.py
cli/cook/subcommands/ssh.py

- Remove Mesos-only help text
can schedule on kubernetes also now

Fix help text

---

scheduler/src/cook/kubernetes/api.clj
scheduler/test/cook/test/kubernetes/api.clj

- calling `set` on the pod-name lists that are passed to `set/union` in `initialize-pod-watch-helper`
Without this change, if a pod is present both in `namespaced-pod-name->pod` (fetched from k8s) and `old-all-pods` (in the compute cluster), then it will get processed twice, which is obviously not what we want.
```
; Before
(set/union [:a] [:a])
=> [:a :a]
; After
(set/union (set [:a]) (set [:a]))
=> #{:a}
```

Processes each pod only once on pod watch initialization

---

integration/tests/cook/test_basic.py
scheduler/src/cook/kubernetes/api.clj

-  change checkpointing volume from init container to scratch space
need more flexibility for checkpointing code

change checkpointing volume from init container to scratch space

---

cli/cook/querying.py
cli/cook/subcommands/cat.py
cli/cook/subcommands/ls.py
cli/cook/subcommands/ssh.py
cli/cook/subcommands/tail.py

- pass through job info to cs commands
some cs commands need more data, e.g. user

Pass through job info to cs commands

---

scheduler/CHANGELOG.md
scheduler/project.clj

**Please Rebase and merge to preserve the two commits**

Release 1.40.4

---

scheduler/config.edn

- Update the log config to match the rename done a few months ago and align with config-k8s.edn
Consistency between our environments.

Bring config.edn up to date with config-k8s.edn.

---

scheduler/config-composite.edn
scheduler/config-k8s.edn
scheduler/src/cook/kubernetes/compute_cluster.clj

- add flag to use google service account
Make it optional to use google credentials

add flag to use google service account

---

scheduler/CHANGELOG.md
scheduler/project.clj

**Please Rebase and merge to preserve the two commits**

Release 1.41.0

---

integration/tests/cook/reasons.py
integration/tests/cook/test_basic.py
scheduler/docs/reason-code
scheduler/src/cook/kubernetes/controller.clj
scheduler/src/cook/scheduler/scheduler.clj
scheduler/src/cook/schema.clj

- Handle Killed by user reason code

Handle Killed by user reason code

---

scheduler/src/cook/scheduler/scheduler.clj

This is a follow-up to PR #1536.
- for `MesosComputeCluster`s, avoiding launching tasks in a `future`
We're seeing the following exception inconsistently but regularly:
```
2020-05-11 01:04:17,105 ERROR cook.scheduler.scheduler [clojure-agent-send-off-pool-6] - In no-pool pool, error launching tasks for default-compute-cluster-from-config-defaulting compute cluster
java.lang.ClassNotFoundException: com/google/protobuf/ByteString
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at clojure.lang.RT.classForName(RT.java:2168)
at clojure.lang.RT.classForName(RT.java:2177)
at cook.mesos.task$task_info__GT_mesos_message.invokeStatic(task.clj:374)
at cook.mesos.task$task_info__GT_mesos_message.invoke(task.clj:338)
at …
```

Avoids future for Mesos launch-tasks! call

---

integration/tests/cook/test_basic.py

mark test_kubernetes_checkpointing xfail

---

scheduler/src/cook/kubernetes/api.clj
scheduler/test/cook/test/kubernetes/api.clj

- add mounts for init container in checkpointing config
Need more flexibility for checkpointing tool

add support for init container checkpointing mounts

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release Cook 1.42.4

---

.gitignore
integration/tests/cook/test_client.py
jobclient/python/cookclient/__init__.py
jobclient/python/cookclient/containers.py
jobclient/python/cookclient/instance.py
jobclient/python/cookclient/jobs.py
jobclient/python/cookclient/util.py
jobclient/python/docs/source/api.rst
jobclient/python/docs/source/index.rst
jobclient/python/docs/source/usage.rst
jobclient/python/tests/test_instance.py
jobclient/python/tests/test_job.py

- Adds node pool and container support
- Fixes Instance parsing issue

Update Python client to 0.2.0

---

README.md

- adding links to the API docs, Java client, Python client, and CLI
To make the README a little more informative.

Adds links to README

---

scheduler/config-composite.edn
scheduler/src/cook/kubernetes/compute_cluster.clj
scheduler/src/cook/test/testutil.clj
scheduler/test/cook/test/kubernetes/compute_cluster.clj

- Implement a total number of nodes and pods quota for k8s.
So we can control the load we put on k8s.

Implement a total number of nodes and pods quota for k8s.

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release 1.42.5

---

scheduler/src/cook/kubernetes/compute_cluster.clj
scheduler/test/cook/test/kubernetes/compute_cluster.clj

- Fix NPE when we ask a k8s pool for offers when it has none
Avoid spam in the log.

Fix NPE when we ask a k8s pool for offers when it has none

---

scheduler/src/cook/kubernetes/controller.clj

- adding overload to `synthesize-state-and-process-pod-if-changed` that takes in a `force-process?` arg
- when `force-process?` is true, calling `process` regardless of changes
- calling it with `force-process?` set to true from the state scanner
Otherwise, we're not retrying certain states like failed pod submissions.

Forces processing when state scanning in k8s

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.43.1

---

jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java

- Add GPU support for Java job client
- Update unit tests
- Users using the Java job client cannot request GPUs until we add GPU support

GPU support for the Java jobclient

---

integration/tests/cook/util.py

Adding the calling test function name to the User-Agent on `util.kill_jobs`, e.g.:
```
0:0:0:0:0:0:0:1 - vagrant [03/Aug/2020:18:59:00 +0000] "DELETE /rawscheduler?job=20080318-ef40-4153-b630-5edb59e5a917 HTTP/1.1" 204 - "-" "test_cancel_job (Cook-Scheduler-Integration-Tests (python-requests/2.20.0))" 23
```
Since our tests run concurrently, it can be helpful when troubleshooting test failures to know which test a particular delete jobs request came from.

Adds the calling test name to the User-Agent on kill_jobs

---

jobclient/java/src/main/java/com/twosigma/cook/jobclient/Checkpoint.java
jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java

- Add checkpoint job field to jobclient

Add checkpoint field to jobclient

---

cli/cook/version.py

- bumping CLI version to 3.2.0
To publish the new version to pypi.

Updates CLI version to 3.2.0

---

scheduler/src/cook/scheduler/scheduler.clj

Adding the following to the launching tasks log:
- hostnames matched
- number of offers matched
- number of jobs matched per user
Also, as a nice side effect, fixing the existing metric, which was broken because it was incorrectly destructuring the matches collection.
Example log:
```
2020-09-04 03:57:07,787 INFO  cook.scheduler.scheduler [async-thread-macro-3] - In k8s-alpha pool, launching matched tasks {:hostnames-matched (gke-dpo-test-0714-19-cook-pool-k8s-al-a9fd9d62-707q gke-dpo-test-0714-19-cook-pool-k8s-al-a9fd9d62-57jx), :number-offers-matched 2, :number-tasks 4, :user->number-jobs {vagrant 4}}
```
To make troubleshooting issues easier.

Adds information to the launching tasks log

---

scheduler/src/cook/kubernetes/compute_cluster.clj

- only logging when the maxes are exceeded
- making the logs be WARN level
- adding data to the "cannot launch more synthetic pods" log
Examples:
```
2020-09-04 22:10:48,347 WARN  cook.kubernetes.compute-cluster [async-thread-macro-5] - In gke-2 compute cluster, total pods are maxed out {:max-total-pods 4, :total-pods 23}
2020-09-04 22:10:48,347 WARN  cook.kubernetes.compute-cluster [async-thread-macro-5] - In gke-2 compute cluster, nodes are maxed out {:max-total-nodes 3, :total-nodes 3}
2020-09-04 22:10:48,347 WARN  cook.kubernetes.compute-cluster [async-thread-macro-5] - In gke-2 compute cluster, cannot launch more synthetic pods {:max-synthetic-pods 2, :max-total-nodes 3, :max-total-pods 4, :synthetic-pods 0, :total-nodes 3, :total-pods 23}
2020-09-04 22:10:48,347 WARN …
```

Improves logging when we stop launching synthetic pods

---

scheduler/src/cook/scheduler/scheduler.clj

- moving the log from `match-offer-to-schedule` (pre-match) to `handle-resource-offers!` (post-match)
- adding several more potentially useful pieces of data to it
Example log:
```
2020-09-08 03:08:55,176 INFO  cook.scheduler.scheduler [async-thread-macro-6] - In k8s-alpha pool, matching offers to considerable jobs {:jobs-considerable {:user->number-total {vagrant 12}, :user->number-matched {vagrant 3}, :head-resources {:ports 0, :cpus 0.1, :mem 32.0}, :number-unmatched 9, :head-matched? false, :number-total 12, :number-matched 3, :resource-type->total {:cpus 2.100, :mem 480.000}, :user->number-unmatched {vagrant 9}}, :offers {:number-matched 1, :number-total 1, :number-unmatched 0, :resource-type->total {mem 937.125, cpus 0.739, disk 0.000}}}
```
To make troubleshooting matching issues …

Adds information to the matching offers log

---

scheduler/CHANGELOG.md
scheduler/project.clj

**Please Rebase and merge to preserve the two commits**

Release v1.45.1

---

jobclient/java/pom.xml
scheduler/project.clj

- updating java jobclient version

Java jobclient v0.7.0

---

jobclient/java/pom.xml
scheduler/project.clj

Java jobclient v0.7.1

---

scheduler/src/cook/kubernetes/api.clj
scheduler/src/cook/kubernetes/compute_cluster.clj
scheduler/src/cook/scheduler/scheduler.clj
scheduler/src/cook/tools.clj
scheduler/test/cook/test/scheduler/scheduler.clj
scheduler/test/cook/test/tools.clj

- making several logs much less long
To make the log size more manageable.

Reduces excessive logging

---

scheduler/src/cook/scheduler/constraints.clj
scheduler/test/cook/test/scheduler/constraints.clj

- Cache the job constraints in the defrecord for user-defined-constraint
- Optimizing constraints

Optimize user-defined-constraint

---

Vagrantfile
integration/bin/force-leader-change
integration/tests/cook/test_basic.py
integration/tests/cook/test_dynamic_clusters.py
integration/tests/cook/test_multi_user.py
integration/tests/cook/util.py
scheduler/config-k8s.edn
scheduler/src/cook/compute_cluster.clj

- fix dynamic cluster integration tests

Fix dynamic cluster integration tests

---

integration/tests/cook/util.py

- Refactor functionality so0 that we can do special redirecting for DELETE and POST requests with authentication.
Needed to enable quota changes which require redirects to the cook primary.

Refactor special redirect to code to support POST and DELETE

---

integration/tests/cook/test_dynamic_clusters.py

- set correct wait_until predicate

fix dynamic cluster integration test

---

scheduler/src/cook/kubernetes/api.clj
scheduler/test/cook/test/kubernetes/api.clj

- add checkpointing kill switch

add checkpointing kill switch

---

cli/cook/subcommands/show.py
cli/cook/subcommands/submit.py
cli/cook/version.py

- add checkpointing options
allow user to enable checkpointing without using raw job spec

add checkpointing options

---

scheduler/src/cook/scheduler/scheduler.clj

- only logging the job uuid and task id for each of the first 10 tasks
- logging the total number of tasks
Example:
```
2020-10-15 21:45:32,912 INFO  cook.scheduler.scheduler [async-thread-macro-4] - In k8s-alpha pool, writing tasks {:first-10-tasks ({:job-uuid 20101521-ba37-4101-aee4-f65f5d7669ae, :task-id 5f88c2fc-0c8b-42ad-8d2f-66c768e2dc1b} {:job-uuid 20101521-b2c1-4059-8504-0cdec25befc7, :task-id 5f88c2fc-39f6-435b-a1ee-7380f3212a76} {:job-uuid 20101521-a3cf-43c7-964b-1265d56c1b98, :task-id 5f88c2fc-f348-44c5-ae89-3e1b451aa30d} {:job-uuid 20101521-36b6-4274-a77b-03f25dc1d877, :task-id 5f88c2fc-4a2a-4a61-8a75-b6ddf6380d99} {:job-uuid 20101521-8c35-49b1-8fcc-8183a795c4c6, :task-id 5f88c2fc-1537-4036-baee-a4c86bb5ff2d} {:job-uuid 20101521-5b55-4205-93e6-880a6279573b, :task-id …
```

Shortens the 'writing tasks' log

---

jobclient/java/src/main/java/com/twosigma/cook/jobclient/Disk.java
jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java

- Add Disk class
- Add set and get functions for Disk request, limit, and type
- Allow Java jobclient users to specify disk

Add support for disk field in Java job client

---

jobclient/java/src/main/java/com/twosigma/cook/jobclient/Application.java
jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobClientTest.java
jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java

- add workload fields to application object on job

add workload fields to job client

---

scheduler/CHANGELOG.md
scheduler/project.clj

**Please Rebase and merge to preserve the two commits**
- bumping version 

update changelog and version for v1.49.0

---

scheduler/src/cook/util.clj

Add Comment

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release 1.49.1

---

scheduler/src/cook/kubernetes/compute_cluster.clj

- Refactor how we read a .kubeconfig file and do authentication.
No functionality change. Prepare for an upcoming change to for refreshing authenticators.

Refactor authenticator initialization

---

scheduler/src/cook/kubernetes/compute_cluster.clj

- allowing the read timeout to be configured instead of hard-coded to 120 seconds
So that we use a different timeout than 120 seconds.

Makes k8s API client read timeout configurable

---

jobclient/java/pom.xml
scheduler/project.clj

Updates java jobclient version to 0.8.2

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.50.1

---

cli/cook/version.py

- Update the version of the cli client.
Upgrade version of cli client in preparation for release.

Upgrade version of cli client 3.7.0 in preparation for release.

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and bumps version for v1.51.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.51.1

---

cli/README.md
cli/cook/cli.py
cli/cook/plugins.py
integration/tests/cook/test_cli_subcommand_plugin.py

Extend CLI plugin infrastructure to support new subcommands
We'd like to be able to support additional subcommands outside of the core already provided

extend plugin infrastructure to support new subcommands

---

cli/cook/version.py

Bumping CLI version to 3.8.0
To publish the new version to pypi

Updates CLI version to 3.8.0

---

cli/cook/subcommands/submit.py
cli/cook/version.py
integration/tests/cook/test_cli.py
integration/tests/cook/test_client.py

Support for constraints as CLI args
Feature parity with REST API

Cli constraints

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.51.2

---

scheduler/CHANGELOG.md
scheduler/project.clj

Please rebase, do not squash these changes.
- Release Cook.

Release 1.51.3

---

integration/tests/cook/test_basic.py
integration/tests/cook/util.py
scheduler/config-k8s.edn
scheduler/src/cook/kubernetes/api.clj
scheduler/test/cook/test/kubernetes/api.clj

- Let users set on configurable job label if they want to allow memory usage above memory request
We found use cases of memory limit

Add memory limit job label

---

scheduler/CHANGELOG.md
scheduler/project.clj

Please rebase, do not squash these changes.
- Release Cook

Release 1.51.4

---

scheduler/CHANGELOG.md
scheduler/project.clj

Please rebase but do not squash.
- Release Cook

Release 1.51.5

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.51.6

---

scheduler/CHANGELOG.md
scheduler/project.clj

Please rebase but do not squash.
-  Update changelog and version
Release Cook.

Outgoing/release 1.51.7

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.51.8

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.51.9

---

integration/tests/cook/test_basic.py

- making `test_memory_limit` jobs have retries and not make assumptions about the 0th instance
- making several formatting-only changes
To make the test more reliable.

Makes test_memory_limit more reliable

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Update release files
Release Cook.

Release 1.51.11

---

scheduler/CHANGELOG.md
scheduler/project.clj

Please rebase and do not squash these commits.
- Prepare for release
Release Cook.

Release 1.51.12

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Prepare for release
Release Cook

Release 1.51.13

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.51.14

---

jobclient/java/pom.xml
scheduler/project.clj

Updates java jobclient version to 0.8.5

---

scheduler/src/cook/rest/api.clj
scheduler/src/cook/scheduler/scheduler.clj
scheduler/src/cook/schema.clj

- when we transition a job into the waiting state, saving the time of that transition, `:job/last-waiting-start-time`
- when we create a job instance, calculating `now - :job/last-waiting-start-time` and saving that as `:instance/queue-time`
- returning the queue time when a job instance is fetched
To be able to see how long job instances and jobs are queued for.

Adds field for how long the job queued before each instance

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.52.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.53.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.53.1

---

scheduler/project.clj
scheduler/src/cook/kubernetes/api.clj

- adding [`better-cond`](https://github.com/Engelberg/better-cond) as a dependency
- refactoring `node-schedulable?` with `better-cond`
(read the [rationale](https://github.com/Engelberg/better-cond#rationale) for `better-cond` itself)
To make the function easier to read:
- bindings are closer to where they're used
- less nesting

Refactors node-schedulable? with better-cond

---

scheduler/src/cook/kubernetes/api.clj

- Refactor task-metadata->pod to create and add containers in helper functions
- Simplify task-metadata->pod function
- Prepare for future incremental feature rollouts that will require dynamically built pod configurations

Refactor pod creation

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.53.3

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.53.4

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.53.5

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.53.6

---

scheduler/src/cook/kubernetes/api.clj

-  Fix a whitespace bug.
Cleaner patches.

Fix whitespace

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.54.0

---

scheduler/src/cook/config_incremental.clj
scheduler/src/cook/passport.clj
scheduler/src/cook/rest/api.clj
scheduler/src/cook/schema.clj
scheduler/src/cook/task.clj
scheduler/test/cook/test/config_incremental.clj
scheduler/test/cook/test/rest/api.clj
scheduler/test/cook/test/task.clj

- add incremental feature flags
We want to be able to have configurations that take on more than one value. Based on the job uuid one of the values is picked. The values are weighted.
This allows an incremental roll out of new features or even kill switch functionality for disabling features

Incremental feature flags

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Release new version of Cook.
- Bring the changes into production.

Release v1.56.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

**Please rebase but do not squash these commits.**
- Release Cook 1.56.1
Get new changes into production.

Release Cook 1.56.1

---

scheduler/bin/start-datomic.sh
scheduler/project.clj
scheduler/test/cook/test/compute_cluster.clj

Revert "Update to clojure 1.10"

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release Cook 1.56.2

---

scheduler/src/cook/config_incremental.clj
scheduler/src/cook/rest/api.clj
scheduler/src/cook/schema.clj
scheduler/test/cook/test/config_incremental.clj
scheduler/test/cook/test/rest/api.clj

- add optional comments to incremental value configurations
To be able to describe how an incremental value is different from others

add optional comments to incremental value configurations

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.57.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.57.1

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.58.4

---

integration/tests/cook/test_multi_user.py

Making the test use `util.default_job_mem_mb()` instead of hard-coding 32 MiB.
So that the test works reliably in environments that configure a different default memory amount.

Makes test_instance_stats_success more reliable

---

scheduler/src/cook/rest/api.clj
scheduler/test/cook/test/rest/api.clj

- add check to job labels on submission
Check that job labels that are pod labels have valid format on job submission

Check that job labels that are pod labels have valid format

---

integration/tests/cook/test_cli.py
integration/tests/cook/test_multi_user.py
scheduler/src/cook/rest/api.clj
scheduler/test/cook/test/rest/api.clj

- Check that job constraints are valid k8s pod labels
We should reject jobs with invalid constraints at submission time

validate job constraints

---

integration/tests/cook/test_dynamic_clusters.py

- clean up jobs in dynamic cluster test
Cook won't be able to manage a job running on a test cluster. we need to clean them up

clean up jobs in dynamic cluster test

---

integration/tests/cook/util.py

- Remove some dead integration test helper functions that are mesos-specific.
Less code is good.

Remove dead mesos integration test code.

---

sidecar/cook/sidecar/version.py
sidecar/setup.py

- Upgrade dependencies to newer versions in preparation for releasing a new version.
- Our dependencies are old.

Upgrade sidecar dependencies

---

jobclient/java/src/main/java/com/twosigma/cook/jobclient/Instance.java
jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
jobclient/java/src/test/java/com/twosigma/cook/jobclient/InstanceTest.java

- add exitCode
- add fileURL
- expose setPool on the Job builder
Match client to API

Cook Java client updates

---

Development.md
scheduler/project.clj

- Adding a whole lot of development environment docs
Make it easier to onboard new users to Cook OSS development.

Development Documentation for Cook

---

scheduler/CHANGELOG.md
scheduler/project.clj

Updates changelog and version for v1.59.5

---

scheduler/CHANGELOG.md
scheduler/project.clj

- updating changelog 
- updating version

Release 1.59.7

---

scheduler/CHANGELOG.md
scheduler/project.clj

Release v1.60.1

---

.gitignore
scheduler/src/cook/rebalancer.clj
scheduler/src/cook/schema.clj
scheduler/test/cook/test/rebalancer.clj

Revert "allow preemptions for tasks with unknown status"

---

scheduler/project.clj
scheduler/src/cook/kubernetes/compute_cluster.clj
scheduler/src/cook/scheduler/scheduler.clj

- Adds open tracing library.
- Adds open tracing to the core parts of the match cycle logic.
This will allow us to inspect runtime performance bottlenecks.

Adding opentracing

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updates version and changelog for v1.61.1 

Release version v1.61.1

---

scheduler/src/cook/scheduler/scheduler.clj
scheduler/src/cook/tools.clj

- Adds a few more tracing spans to the match cycles.
- Fixes some typos in existing spans.
To get a better understanding the match cycle time breakdown.

Fixing up some opentracing issues and adding more spans to the match cycle

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updates changelog and version of v1.61.3.

Release v1.61.3

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updates changelog and version of v1.62.0.

Release v1.62.0

---

scheduler/src/cook/config.clj
scheduler/src/cook/monitor.clj
scheduler/src/cook/tools.clj

- Some mild refactors split off from the main joint quota work.
More smaller changesets are easier to review.

Refactor to move quota-grouping-config definition and list of all pools.

---

Development.md

- Improve the dev docs, indicating how to teach cursive about macros.

Added development doc tweak on teaching cursive how to understand macros.

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updates changelog and version of v1.62.1.

Release v1.62.1

---

scheduler/project.clj
scheduler/src/cook/components.clj
scheduler/src/cook/prometheus_metrics.clj
scheduler/src/cook/rest/api.clj
scheduler/src/cook/scheduler/scheduler.clj
scheduler/src/cook/test/testutil.clj
scheduler/test/cook/test/scheduler/scheduler.clj

- Adding support for prometheus metrics in cook.
- Instrumenting `scheduler.clj` with latency metrics.
Migrating our metrics framework to prometheus.

Prometheus

---

scheduler/src/cook/components.clj
scheduler/src/cook/config.clj

- Adds support for a custom rate limit to the /metrics endpoint.
The default rate limit for endpoints with no auth is not sufficient, and we want to ensure that the /metrics endpoint always works correctly.

Adding configurable rate limit for the /metrics endpoint

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updating changelog and version. 

Release v1.62.3

---

scheduler/src/cook/scheduler/scheduler.clj

- A light zero-functionality refactor.
This separates out the mutation code from the logic code.

Refactor code for processing matches.

---

scheduler/src/cook/prometheus_metrics.clj
scheduler/src/cook/rest/api.clj
scheduler/src/cook/tools.clj

- Adding prometheus metrics to the API layer and related tools module.

Adding prometheus metrics to the API layer and related tools module

---

scheduler/src/cook/scheduler/scheduler.clj

- Refactor how we setup autoscale into a new function.
- No functionality change.
This sets us up for doing autoscaling in parallel with launching the prior round.

Refactor how we setup autoscale into a new function.

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updates changelog and version for v1.62.5

Release v1.62.5

---

scheduler/src/cook/scheduler/scheduler.clj

- Refactor `launch-tasks-for-cluster` to handle launching for Fenzo and Kubernetes Scheduler pools. This required some movement of metrics handling and a boolean gate for Fenzo pools.
- Refactors Kubernetes Scheduler pools to use this function for launching, by providing its incomplete match objects (just the metadata) and db transactions.
- Follow-up feedback from #2150

Launch tasks similarly for both Fenzo and K8s Scheduler pools

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updates changelog and version for v1.62.6

Release v1.62.6

---

scheduler/src/cook/kubernetes/compute_cluster.clj
scheduler/src/cook/prometheus_metrics.clj
scheduler/src/cook/rest/api.clj
scheduler/src/cook/scheduler/scheduler.clj
scheduler/test/cook/test/scheduler/scheduler.clj

- Adding any leftover metrics in prometheus.

Prometheus leftover

---

scheduler/src/cook/components.clj
scheduler/src/cook/prometheus_metrics.clj

- Adds ring instrumentation in prometheus.

Adding ring instrumentation in prometheus

---

scheduler/src/cook/kubernetes/api.clj

- Optimizize getting nodename from a node.
Improve performance.

Optimize getting the nodename from a node.

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updates changelog and version for v1.63.0

Release v1.63.0

---

scheduler/CHANGELOG.md
scheduler/project.clj

- Updates changelog and version for v1.63.4

Release v1.63.4
