twosigma/Cook

- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/util.clj
This should begin to reduce the amount of DB storage we use for default params, which could lead to better scan performance for some workloads.
Leif, as resident DB expert, what do you think about this style?
> Elide some job params from db for better compression. Fixes #25

- scheduler/src/cook/mesos/scheduler.clj
It seems that it's possible for reconciliation to cause Cook to keep recieving updates about an instance, and those updates will keep failing, which will kill due to consuming too many resources.
We must investigate under what circumstances we repeatedly try to transact an instance fail update that is repeatedly bailed out of by the transaction function _and_ triggers reconciliation or Mesos status updates (or maybe those are in response to a repeatedly generated `killTask`?).
```
2015-09-22 19:53:29,693 WARN  cook.mesos.scheduler [clojure-agent-send-off-pool-5] - Attempting to kill task 19b52a71-b837-4758-ac3d-41dae28e4050 as instance 17592186045465 with :job.state/completed and :instance.status/unknown should've been put down already
2015-09-22 19:53:29,706 WARN  cook.datomic …
```
> Infinite loop during lost job races

- scheduler/README.asc
- scheduler/docs/configuration.asc
Two changes:
- Clarify on how to build cook with datomic pro
- Document the `:role` configuration option for connecting to mesos master with security/ACL enabled.
> Update the documentation 

- scheduler/src/cook/mesos/monitor.clj
The newly added "ports" resource breaks the mesos monitor code
> Filter out resources to be only cpus and mem in mesos/monitor.clj

- scheduler/src/cook/mesos/scheduler.clj
There is a typo in the metric name for front-of-job-queue-cpus.
> fix the typo in the metric name

- scheduler/project.clj
- scheduler/src/cook/components.clj
It appears that in purging the codebase of voom (5c44eff1a52339176f1b6692639effd4970b8a6f) we lost the automatic Ring metrics.
This adds them back, and additionally puts us back on the upstream published version of metrics-clojure, now that it's been published.
> Add metrics-clojure-ring, move us back to mainline metrics-clojure

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/scheduler.clj
Swap out the kerberos principal which was causing errors for non-kerberized auth environments (issue #123) and instead just pass in a shim principal.
> Create shim principal for access logs

- scheduler/src/cook/mesos/dru.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/dru.clj
When there are many jobs in the queue, the ranking function can take a long time because it must sort all jobs. This PR makes the final sort across all jobs lazy so that the affect of many jobs in the queue is greatly reduced.
> Make sort for rank jobs lazy

- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/scheduler.clj
This commit has the `sort-jobs-by-dru` use an unfiltered db when possible. Throughout most (all) of the code, we use a filtered datomic database which will remove datoms which have a metatransaction status of uncommitted. We do this so that jobs will only be considered valid once they have all been submitted so that we could avoid a case where we try to schedule a partial submission. Unfortunately, using a filtered database is not free, and in some cases can be costly. In the case of ranking jobs, it is very costly. The reason for the cost is that the filter must check every datom to see if it passes. Worse, if the datom doesn't have a metatransaction linked to it, it has to do a more expensive search to confirm that. If we can avoid using the filtered db where possible, both the initial …
> Use unfiltered db when possible for query improvement

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/api.clj
Add endpoints to inspect the running and waiting instances in cook. The waiting jobs are returned sorted.
> Add running and queue endpoints

- scheduler/src/cook/components.clj
These were preventing Cook scheduler from compiling.
> scheduler: Remove stray references to clj-http-async-pool.

- jobclient/pom.xml
Per discussion 
http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete
> Disable java doc checking for java 8+

- scheduler/src/cook/mesos/api.clj
This allows the job name always being persisted into db.
> Set the default job name if user doesn't provide

- scheduler/src/cook/mesos/scheduler.clj
This Mesos status means that the task was incorrectly specified in the
first place.  Cook wasn't handling it at all; we should consider the
task failed in this case.
> scheduler: Handle task-error status updates from Mesos.

- scheduler/project.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/task.clj
- scheduler/test/cook/test/mesos.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/task.clj
This change also enables us to properly support Mesos Roles.
At this time, it depends on a version of Mesomatic with this PR merged in:
pyr/mesomatic#23
Thus, it can't be used without a new version of Mesomatic (or forking Mesomatic); at this stage this PR is for code review purposes only & shouldn't be merged yet.
> REVIEW ONLY: Scheduler: Replace clj-mesos with mesomatic.

- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/task.clj
This fixes the build to the point where the issues can be addressed. There are still these 2 issues: one from Mesosmatic, and the other is when `get-lingering-tasks` had a signature change.
```
ERROR in (test-task-info->mesos-message) (Reflector.java:271)
Uncaught exception, not in assertion.
expected: nil
actual: java.lang.IllegalArgumentException: No matching field found: getAllPorts for class org.apache.mesos.Protos$Ports
at clojure.lang.Reflector.getInstanceField (Reflector.java:271)
clojure.lang.Reflector.invokeNoArgInstanceMember (Reflector.java:315)
mesomatic.types$eval9375$fn__9376.invoke (types.clj:1054)
clojure.lang.MultiFn.invoke (MultiFn.java:229)
mesomatic.types$eval9415$fn__9416.invoke (types.clj:1079)
clojure.lang.MultiFn.invoke (MultiFn.java:229) …
```
> Fix the build, tests still broken

- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/scheduler.clj
[This commit](https://github.com/twosigma/Cook/commit/c356e3dcf1ef6942f72774c9954777ca07d59209) broke backfilling by changing the outputs from sets to vectors. Further down, `contains?` is used on these parameters.
> Backfill broken

- scheduler/src/cook/mesos/scheduler.clj
offer-stash was initialized to nil and was only being reset! to its own
value, @offer-stash - meaning it could never acquire a value other than
nil.
Thus, attempting to put its value back on the channel in the exception
handling block would in turn raise an exception (can't put nil on
channel).  Since this exception was not handled, the thread would die,
and handle-resource-offers! would stop happening, resulting in no offers
to match until Cook was restarted.
I believe the var offers-scheduled contains what @offer-stash USED to
be reset! to, prior to commit a134d1f8776eb1b0627eb74a073bae125bf6d52a.
> scheduler: Fix error when recycling offer-stash.

- scheduler/docs/configuration.asc
- scheduler/docs/scheduler-rest-api.asc
- scheduler/project.clj
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/dru.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/schema.clj
- scheduler/src/cook/mesos/share.clj
- scheduler/src/cook/mesos/task.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/dru.clj
- scheduler/test/cook/test/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/schema.clj
- scheduler/test/cook/test/mesos/share.clj
- scheduler/test/cook/test/mesos/task.clj
This adds support for:
- GPU resources on agents, which will only be accepted if enabled in the
config file
- Scheduling GPU jobs on GPU machines and non-GPU jobs on non-GPU
machines
- Uses DRU & preemption with GPUs as well, but they're considered
independently
- Adds GPUs to the REST API
- If GPUs are enabled and the Mesos version doesn't support them, fails
loudly
> Add GPU support to Cook

- scheduler/project.clj
The previous version of this line was pointing to an ephemeral snapshot
release of Fenzo which is no longer available.
> scheduler: Update Fenzo to newer version.

- scheduler/src/cook/mesos/rebalancer.clj
I noticed this while running simulation tests.
If the rebalancer "changes its mind" during a rebalance - adding a synthetic task and then subsequently removing that one in favor of other synthetic tasks - it will actually try to transact a preemption on the removed synthetic tasks.  Since these synthetic tasks don't have id's, that causes an error.
> scheduler: Don't try to preempt synthetic tasks.

- scheduler/docs/configuration.asc
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
Git hash will still be included.
> scheduler:  Allow mesos framework name to be configured.

- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/schema.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/dru.clj
- scheduler/test/cook/test/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/testutil.clj
The concept of backfilled jobs was to allow Cook to schedule out of
order (specifically, skip the head of the queue) to oppurtunistically
improve utilization. However, this can lead to cases where the job at
the head of the queue is starved and not able to get scheduled. When
this occurs, we rely on the rebalancer to free up space such that the
head of the queue can run. Instances were explicitly marked as
backfilled when Cook scheduled out of order and were then upgraded out
of backfilled status once the jobs ahead of them had been scheduled.
Instances that were marked as backfilled were treated as the first
jobs to be preempted.
This caused a variety of problems:
1. Preempting backfilled jobs first caused unexpected behavior when a
backfilled, high priority job was preempted instead of …
> Remove the distinction of backfilled jobs

- scheduler/docs/groups.md
- scheduler/project.clj
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/constraints.clj
- scheduler/src/cook/mesos/dru.clj
- scheduler/src/cook/mesos/group.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/schema.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/src/cook/util.clj
- scheduler/test/cook/test/jobclient/jobclient.clj
- scheduler/test/cook/test/mesos/constraints.clj
- scheduler/test/cook/test/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/util.clj
- scheduler/test/cook/test/testutil.clj
Multiple code review changes, including better docstrings, many variable name changes, and filtering host->scored-tasks.
Created a new namespace for constraints
Generalized the balanced constraint to any attribute, exposed expected count parameter
Multiple code review changes: made unconstrained filtering in rebalancer simpler and more efficient, improved naming of cotask functions, added host placement explanation to groups.md and other small changes
Made offer cache maximum size and ttl configurable.
Added rebalancer tests for balanced constraint
CR changes: clarifications in group.md, extracted common code from fenzo constraints into shared functions, cotasks are now both unknown and running instances, host attributes now extracted from offers, renamed cotask-getter functions, added …
> Implemented host-placement group constraints

- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
They are still required in the database - if missing from API request, default
values are assigned.
Fixes #268
> scheduler: Make job name and priority optional in API.

- integration/requirements_dev.txt
- scheduler/minimesosFile
Some of the integration tests require two agents in order to pass.
> Adds second mesos agent to minimesosFile

- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
> scheduler: Allow "job" in addition to "jobs" in /retry API

- .gitignore
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/dru.clj
- scheduler/src/cook/mesos/mesos_mock.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/mesos_mock.clj
This PR includes a mock of mesos and a simulator that starts the scheduling aspects of cook to allow back testing and auditing behavior. The mock of mesos allows us to simulate arbitrarily large clusters (until computation or memory limits on the machine running the simulation are reached). The intent is this simulator will be run "faster than real time" so that running over a day or week of historical jobs can be done in minutes and hours.
> Integration test for cook scheduler / rebalancer using mock mesos

- scheduler/Dockerfile
- scheduler/bin/run-docker.sh
This makes building the docker image much faster when you haven't changed `project.clj`.
> Avoids lein deps when project.clj hasn't changed

- scheduler/bin/run-docker.sh
- scheduler/container-config.edn
Without this, cook will attempt to derive `mesos-master-hosts` from `:mesos` `:master`, which in the case of our minimesos setup, is incorrect, and causes:
```bash
2017-04-21 21:16:05,589 INFO  cook.mesos.rebalancer [async-thread-macro-6] - Rebalance cycle starting
2017-04-21 21:16:05,651 ERROR cook.mesos.rebalancer [async-thread-macro-6] - Rebalance failed
java.net.ConnectException: Connection refused
```
> Explicitly configures :mesos :master-hosts

- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
Sometimes, responses from Cook can be quite large (16 MB.) In order to reduce stress on the GC from allocating large objects to store the responses, we can stream them back to the client.
> Stream JSON responses

- simulator/src/main/cook/sim/reporting.clj
- simulator/src/main/cook/sim/travis.clj
Independent changes to declutter diff in cook-executor PR
> Simulator: display additional info in logs

- scheduler/src/cook/mesos/constraints.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/constraints.clj
This is two changes:
1. Cache the list of constraints for a job since getHardConstraints is
called once for each host with available resources
2. Cache the call to needs-gpus? because it is called once for each job
running on each host (for non-gpu hosts)
> Remove redundant calls to constraint functions in matching

- integration/tests/cook/__init__.py
- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/mesos/api.clj
We want to be able to query a particular cook cluster for a set of uuids, where some of them may not belong to that cluster, and get back the data for those that do match. This change allows for that, instead of always returning 404 if any of the uuids is invalid.
> Adds optional flag to allow partial results when querying for jobs

- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/scheduler.clj
processing happens on non-mesos client thread to avoid class loader problems previously encountered.
> scheduler: use agent to ensure order of processing

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/docs/scheduler-rest-api.asc
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/constraints.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/schema.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/constraints.clj
- travis/minimesosFile
This adds the ability to set constraints on individual jobs and provides a way to grow the constraints api in the future. It is inspired by marathon's constraint api: https://mesosphere.github.io/marathon/docs/constraints.html
> Add job constraints

- scheduler/test/cook/test/mesos/util.clj
This test has a race condition, e.g.:
https://travis-ci.org/twosigma/Cook/jobs/242101623#L1147-L1149
I was able to reproduce the race locally. After this fix, I ran this in a `dotimes` 1000 with no fails.
> Fixes race condition in test-read-chan

- scheduler/src/cook/mesos/rebalancer.clj
Before this change, the rebalancer could potentially consider EVERY job in the queue for preemption. This would mean that a rebalance cycle could take many *minutes* and create a lot of garbage realizing all these preemption choices. When rebalancer cycles take minutes it means that the tasks that end up getting preempted are preempted on information from minutes ago and likely the jobs that room was being made for have already been scheduled.
This change limits the list to the total number of preemption choices the rebalancer is willing to make in a given cycle. It is possible that by not limiting the list Cook would preempt jobs not in the reduced list but that would mean Cook was preempting tasks to make room for a job far back in the queue which doesn't seem productive. 
This change …
> Limit rebalancer jobs to consider to max preemptions

- CHANGELOG.md
- integration/tests/cook/test_basic.py
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/util.clj
By chunking by day, we prevent datomic from doing large joins which it apparently is not well optimized for.
> Improve the performance of get-jobs-by-user-and-state

- scheduler/src/cook/mesos/api.clj
It is expected that we aren't going to be able to retrieve the sandbox dir for jobs that were run long enough ago. The logs are filled with these errors that are noise
> Make sandbox dir fetch error debug

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/util.clj
Switching to seek-datoms allows that function to be completely lazy, meaning we hold on to a lot less memory. Switching to seek-datoms also means we can seek to exactly the time point we are interested in and has shown query speed ups of >10x
> Improve the performance of list endpoint

- scheduler/src/cook/mesos/schema.clj
Mesos command executor failed is not transparent to users
> Update reason string to be more useful

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/mesos/api.clj
> Supports querying for jobs with > 0 ports (issue #358)

- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/rebalancer.clj
This change will make it easier for us to understand the choices the rebalancer is making so we can audit it.
> Log what we are preempting and what will run instead

- scheduler/src/cook/mesos/ranker.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/benchmark.clj
- scheduler/test/cook/test/mesos/ranker.clj
This is the start of code to maintain state needed to compute the ranking of jobs. This allows us to incrementally rank jobs instead of re-doing the computation over again. 
This PR provides functions to update a rank-state map and code to compute the ranking of jobs from the rank-state though both need to be cleaned up and tested.
This PR does not include the code to call the functions to update the rank-state. I propose making that a separate PR.
> Incremental update functions for ranking

- integration/bin/run-integration.sh
- scheduler/Dockerfile
- scheduler/bin/run-docker.sh
- scheduler/project.clj
Avoid running `javac` to compile `SimpleAssignmentResult.java`, which is only used for unit tests.
Also added the `--rm` option to our `docker run` scripts to auto-remove the instances on exit. (That way you shouldn't have to manually run `docker rm` to clean up the clutter quite so often.)
Also bumped the `mesosphere/mesos` docker image used as the base for our Cook Scheduler container up to a more recent stable version (we were using a release candidate image before).
> Fix javac issue with Cook scheduler docker container

- scheduler/bin/run-docker.sh
Helps us avoid needing to manually specify a unique framework ID, or
constantly restart minimesos due to framework conflicts while testing.
> Default to timestamp-based framework ID in run-docker script

- .travis.yml
- scheduler/project.clj
- scheduler/test/cook/test/benchmark.clj
Introducing benchmarking in the scheduler testing stage increases that stage to over 11 minutes, while other stages take 8 minutes or less. So moving benchmarking to a separate stage. Also, the benchmarks have no assertions, so moving them to 'allow failures'.
> Move benchmarking to a separate travis build stage

- cli/README.md
- cli/cook/cli.py
- cli/cook/http.py
- cli/cook/subcommands/list.py
- cli/cook/subcommands/show.py
- cli/cook/subcommands/submit.py
- cli/cook/subcommands/wait.py
- cli/cook/util.py
- integration/tests/cook/cli.py
- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/util.py
- the following sub-commands: 
- `submit-group`
- `kill`
- `retry`
- configurable authentication
The reason these things are not here is just to keep this PR relatively small. Once we get this merged, we will work on adding these items as well.
> Adds list to the CLI

- cli/.cs.json
- cli/cook/cli.py
- cli/cook/metrics.py
- cli/cook/subcommands/submit.py
This PR adds support for optionally configuring metrics to be sent via TCP using your line format of choice.
This has been tested both with the StatsD line format and our internal line format.
Example of metrics graphed in Graphite:
> Adds support for (optional) counters to the CLI

- cli/cook/subcommands/submit.py
- cli/setup.py
This has been uploaded to pypi here:
https://pypi.python.org/pypi/cook-client/0.1.0a4
I confirmed that in a fresh virtualenv, you can `pip install cook_client` and then run `cs`.
> Adds packaging info for pypi

- executor/cook/__init__.py
- executor/cook/config.py
- executor/cook/progress.py
- executor/tests/test_config.py
- executor/tests/test_executor.py
- executor/tests/test_progress.py
- integration/tests/cook/test_basic.py
- scheduler/docs/configuration.adoc
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/util.clj
- scheduler/test/cook/test/simulator.clj
Cook executor: Add support for sequence numbers while sending progress status messages.
Cook scheduler: `progress-aggregator` respects the sequence number in-memory while performing local aggregation of progress messages as it is possible for them to arrive out-of-order.
> Order in priority message handling

- executor/bin/check-version.sh
- executor/cook/__main__.py
- executor/cook/_version.py
- executor/setup.py
- scheduler/bin/build-docker-image.sh
- scheduler/bin/run-docker.sh
Ensure cook-executor binary is rebuilt when sources change, and always
copy the newest version when building the scheduler docker image.
> Keep cook-executor binary updated

- scheduler/bin/run-docker.sh
The script broke when I put this comment in the middle of the multi-line docker create command, so I need to move it outside the command.
> Fix run-docker script

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
Adds generic wait_until function, which is now used to implement
wait_for_job and wait_for_exit_code. Also adds some other functions for
repeated idioms in our tests: submit_jobs, cancel_jobs, etc.
> Add new integration test helper functions

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/scheduler.clj
Temporary fix for our tests until we actually fix the race described in issue #515.
> Workaround in tests for max-runtime-exceeded reason race

- executor/cook/__main__.py
- executor/cook/executor.py
- executor/cook/io_helper.py
- executor/cook/progress.py
- executor/tests/test_executor.py
- executor/tests/utils.py
The main change is that we now pipe the output from the subprocess that is launched.
We also wrap the stdout/stderr calls to print in a lock to avoid data races.
Sample output in the `stdout` file:
```
Cook Executor version 0.1.2.dev0
Starting task c8df9002-9a30-4a11-b484-1cc42b83ec1b
progress: 25 Twenty-five percent
progress: 50 Fifty percent
progress: Sixty percent invalid format
progress: 75 Seventy-five percent
progress: Eighty percent invalid format
Command exited with status 0 (pid: 6984)
Executor completed execution of c8df9002-9a30-4a11-b484-1cc42b83ec1b
```
> Add sysouts to get output closer to Mesos' CommandExecutor

- integration/tests/cook/test_basic.py
This patch fixes a bug in the `test_group_kill_simple` integration test where the `slow_job` might be killed before it starts running, which breaks one of the assertions since the test expects both jobs to have one instance.
> Wait for jobs to start before killing in test_group_kill_simple

- integration/travis/scheduler_config.edn
This *might* fix some of the failures we've been seeing in Travis.
> Bump rate limit for Travis tests up to 1M/minute

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- integration/travis/scheduler_config.edn
- scheduler/container-config.edn
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/sandbox.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/sandbox.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- retries sandbox syncing of hosts when the cache entry expires
- removes bad hosts from the pending sandbox sync process
- asserts for `sandbox_directory` and `output_url` in integration tests
> Sandbox sync for pending hosts

- cli/cook/http.py
- cli/cook/version.py
- integration/tests/cook/util.py
Clarifies the origin of some requests in the cook scheduler access logs.
> Add user agent to requests in python scripts

- integration/tests/cook/test_basic.py
This test should finally be working correctly after the fix in #519.
> Remove explicit on test_max_runtime_exceeded

- integration/tests/cook/test_basic.py
The old mesos behavior with `EXECUTOR_UNREGISTERED` is triggered in this test too.
> Allow EXECUTOR_UNREGISTERED status in max_runtime test

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/test_multi_cluster.py
- integration/tests/cook/util.py
- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
This PR introduces `/jobs`. This can be used in two different ways:
- `/jobs/<uuid>` returns a single job
- `/jobs?uuid=<uuid>&uuid=<uuid>&...` returns a list of jobs
Future PRs will add `/instances` and `/groups`.
> Adds /jobs resource for retrieving jobs

- executor/cook/_version.py
- executor/cook/progress.py
- executor/tests/test_executor.py
- executor/tests/test_progress.py
- executor/tests/utils.py
Example message in the logs:
```
root: DEBUG: Unable to decode line b'\x16npb\x14\x9c<%\x9c3^\xf3\xb1F\xcai\xcd\xdd\x8c_G\xc2\x19\xd2,H\xc9\xe9\x86\x8f\xe2\xe2!1\xfe\xe8yP@\x83\xf0\xbe\xdc\x041\xaaW\xdc\x1e\xe9W\xcb\x1c\xc7\xc4+x\xc4\x9b\xb4\x835D\xa0\x1f\xc7\xc6c,\xfb\xe6\xeb\xba5x\xed\x81Nv\x1a\xa4-"\xe5\x94D\x98R\xd8\x84\xb7\x01\x1f\x8b\x83H\xe3\r\x9b&\x10\x93\x8dJh\xf5\xf5x\xfd\xce\xf2\xe0\xe0\x95\xc0\x9d\xae\xfe\xed\xaf@\xb0\x00\xeb\xc0\xb8>\x8fL\x90\xbb\xd0\xb5\x14(t\x80\xb1\x0eH\x96\x98\x0c\x06*\xd4\r\x8b}@\x8fl\xea\x03\xab\x06v\x8a\xa5\xc7\x17\xf4j\x80j)\xd6\xa6.!\xf6\xd7\xc3\xca\xf4D\x1e6\xc7\xbb\x1b\xb5\xdfm\xc2a\xeb\x07\xf6\xa0\x02w\xce\xe8\x12>\xd0\xd9;\xb3\xd2L\x91+ew\xfb[[\x08c}y\xe5\x16\x12\x87\xc8T\x08i\x9c\x83\rw\x93\x9aK9\xd32\x0e\xb1\x08*\x86\xa9\x0f\xe6\x01\xcf\x04\x1b\ …
```
> supports presence of binary data while processing file for progress messages

- executor/cook/__main__.py
- executor/cook/config.py
- executor/tests/test_config.py
Example logs:
```
...
2017-12-01 16:42:50,168 INFO Memory usage will be logged every 3600 secs
...
2017-12-01 16:42:50,169 INFO Executor Memory usage: 14612.0 kB
2017-12-01 16:42:50,172 INFO MesosExecutorDriver is starting...
...
2017-12-01 16:42:50,242 INFO Executor Memory usage: 15092.0 kB
2017-12-01 16:42:50,248 INFO Executor exiting with code 1
```
> logs memory usage of the executor at fixed intervals

- executor/cook/__main__.py
- executor/cook/executor.py
- executor/cook/progress.py
- executor/tests/test_executor.py
- executor/tests/test_progress.py
- skips processing of intervening progress reports when task has completed
- triggers termination of progress trackers when process completes execution
- makes cook executor exit non-zero only when interrupted or handling exception
Running commands that generate lots of output (e.g. `for i in ``seq 1 10000000``; do echo "progress: 5 five percent" ; done`) can cause significant delays in the executor completion. This is inconvenient as it holds up the Mesos agent resources trying to extract the progress message even after the actual command has run to completion.
On my mac this is noticed to be around 
- 110 seconds for processing 1 million progress lines, vs 
- 36 seconds for processing 1 million lines that do not satisfy the progress regex, vs 
- 24 seconds for tailing 1 million lines. …
> Cook executor progress message processing early termination

- executor/cook/executor.py
- executor/cook/subprocess.py
- executor/requirements.txt
- executor/setup.py
- executor/tests/test_executor.py
- executor/tests/test_subprocess.py
- refactors the process management logic to cook/subprocess.py 
- adds support for killing process trees in the executor (uses [psutil](https://github.com/giampaolo/psutil)) using breadth-first ordering and `SIGSTOP` signals before retrieving child processes 
We want to align our kill logic with the Mesos [`CommandExecutor`](https://github.com/apache/mesos/blob/master/src/launcher/executor.cpp#L856)
> Mimic Mesos CommandExecutor kill logic of killing process tree

- executor/cook/__main__.py
- fixes unit calculation for reporting memory usage
The `resource.getrusage` returns the results in different units on Mac vs Linux. This PR addresses that discrepancy. 
Relevant article: http://fa.bianp.net/blog/2013/different-ways-to-get-memory-consumption-or-lessons-learned-from-memory_profiler/
It notes using `resource` to be the fastest method though sometimes inaccurate in overestimating the value.
> Fixes units discrepancy while reporting memory usage

- executor/cook/__init__.py
- executor/cook/__main__.py
- executor/cook/config.py
- executor/cook/executor.py
- executor/cook/io_helper.py
- executor/cook/subprocess.py
- executor/tests/test_config.py
- executor/tests/test_executor.py
- executor/tests/test_subprocess.py
- removes helper methods and threads for stdout/stderr tracking
- uses stdout=sys.stdout and stderr=sys.stderr for subprocess arguments
-- this helps with testability as otherwise the subprocess ends up writing on the console due to stdout/stderr file descriptors
-- I have manually tested that using the file handles does not slow down the stdout syncing when compared to the mesos command executor
- launches a separate thread to perform task killing on stop_signal
- uses timed [`wait()`](https://docs.python.org/3.5/library/subprocess.html#subprocess.Popen.wait) to await process termination on SIGTERM
- uses `wait()` for process termination either normally or via SIGKILL
We want to relieve ourselves from having to deal with buffering and memory issues of piping stdout and stderr from the …
> Removes needs for stdout and stderr tracker threads

- cli/cook/querying.py
- integration/tests/cook/test_cli.py
- Strips trailing slash from configured clusters (e.g. `http://localhost:12321/`) when parsing an entity ref URL and matching to determine the target cluster
- Adds an integration test to confirm the behavior
If the user has a cluster configured with a trailing slash, they need to be able to match against that cluster when passing an entity ref URL as input.
> Fixes entity ref parsing when configured cluster has trailing /

- integration/tests/cook/util.py
Increase default timeout for the `wait_for_exit_code` utility function to 1 minute.
The previous default of 2 seconds was too short, causing flaky tests.
> Increase default exit code wait for tests to 1 min

- cli/cook/subcommands/kill.py
- cli/cook/version.py
- Fixes grammar of error message you get when there is 1 failure during a `cs kill`
To make the grammar correct.
New error message when there is a single failure:
```bash
$ cs kill 6533d1bf-fa89-4ab1-ad90-f6266bc76901
Failed to kill job 6533d1bf-fa89-4ab1-ad90-f6266bc76901 on dev0.
There was 1 kill failure.
```
> Fixes grammar when there is 1 cs kill failure

- scheduler/src/cook/mesos/api.clj
- Fix auth-check on group operations
- Simplify data-flow of context data by caching it in the `malformed?` handler
- Filter out unauthorized groups (in addition to missing groups) when using `partial` flag
The authorization check for group operations was broken, meaning anyone could kill anyone else's groups.
> Fix auth check on group endpoint

- integration/tests/cook/cli.py
- integration/tests/cook/util.py
- The integration tests will check if the `COOK_CLI_COMMAND` environment variable is set, and use its value as the CLI command to test against (if not set, it will default to simply `cs`)
To allow for testing versions of the CLI other than whatever `cs` happens to resolve to.
> Allows for specifying the CLI command to use in integration tests

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/util.py
- Chooses the EXECUTOR_PROGRESS_OUTPUT_FILE_ENV dynamically in `test_progress_update_submit` and `test_show_progress_message_custom_progress_file`
Allows the test respect the `EXECUTOR_PROGRESS_OUTPUT_FILE_ENV` variable value when configured in the scheduler
> Refactor test_progress_update_submit and test_show_progress_message_custom_progress_file

- integration/bin/single-test.sh
- integration/tests/cook/util.py
- Fewer CPUs and less RAM requested for default job spec used by our integration tests.
- Disable nosetest multiprocessing when using the `single-test.sh` test launcher script.
I think I get fewer timeout errors with *cpus=0.1*, probably because Mesos can schedule more jobs simultaneously. I think `0.1` is actually a more accurate estimation of the default job's CPU usage (it's not particularly compute intensive). Disabling multiprocessing with the single-test script also makes it easier to kill a job that *is* timing out (only need one <kbd>Ctrl</kbd>+<kbd>C</kbd> instead of three).
> Fewer resources for default integration test job

- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- `test_submit_with_command_prefix`: explicitly use a config file with no command-prefix
- `temp_config_file`: use the `COOK_SESSION_MODULE` environment variable if it's set
- `test_submit_raw_multiple`: respect the configured command-prefix
- `test_submit_raw`: respect the configured command-prefix
- `test_retries`: look for the 'Retrying' log message to count the retries
- `test_complex_commands`: respect the configured command-prefix
- `test_double_dash_for_end_of_options`: respect the configured command-prefix
- `test_tail_follow`: use `wait_for_instance` instead of `wait_for_job(..., 'running')`
So that the CLI tests can be run in multiple environments without flaking.
> Makes several CLI tests more reliable

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/api.clj
This is what the Cook /settings endpoint's JSON response looks like now:
`{...,"authorization-middleware":"cook.components$fn__30710$fnk30707_positional__30711$one_user_middleware__30712@19910f02",...}`
This is what the Cook /settings endpoint's JSON response looks like after this patch:
`{...,"authorization-middleware":"OneUserAuthMiddleware",...}`
This both makes the settings more readable, and makes it easier to check which auth-scheme we're using during integration testing. I'm planning to use this feature to enable certain multi-user tests only when using BasicAuth or Kerberos.
> User-friendly JSON values for auth-middleware

- cli/cook/util.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- changing `is_valid_uuid` to no longer check if the string representation of the parsed UUID is equal to the input string
- adding an integration test for a UUID that exposes this: `019c34c3-13b3-b370-01a5-d1ecc9071249`
The UUID above, and others, parse as valid UUIDs, but for some reason have a different string representation:
```bash
>>> uuid_str = '019c34c3-13b3-b370-01a5-d1ecc9071249'
>>> import uuid
>>> uuid_obj = uuid.UUID(uuid_str, version=4)
>>> str(uuid_obj)
'019c34c3-13b3-4370-81a5-d1ecc9071249'
>>> str(uuid_obj) == uuid_str
False
```
At the end of the day, all we care is that Cook Scheduler accepts these UUIDs, and it does.
> Softens the UUID validity check

- integration/tests/cook/test_cli.py
All changes are to `test_list_by_state`:
- Changing the long-running job to sleep for 300 seconds instead of 120
- Adding a `finally` block to kill the long-running job and the waiting job
- Refactoring to make it more readable
The `waiting+running` query near the end of the test can fail if the long-running job is no longer running by the time that query is made.
> Makes test_list_by_state more reliable

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/api.clj
Add unauthenticated `/info` endpoint that includes:
- Cook version
- Cook build commit hash
- Cook scheduler instance start time
- Current authentication scheme
Sample JSON response:
```javascript
{
"authorization-scheme": "one-user",
"commit": "dev",
"start-time": "2017-12-15T01:22:12.956Z",
"version": "1.8.4-SNAPSHOT"
}
```
Having the authentication scheme queryable on an unauthenticated endpoint will be helpful for determining the current authentication scheme when performing setup for our multi-user integration tests. The other information is helpful for checking the status of an update deployment.
> Add /info endpoint (unauthenticated)

- cli/cook/querying.py
- cli/cook/subcommands/kill.py
- cli/cook/subcommands/ls.py
- cli/cook/subcommands/show.py
- cli/cook/subcommands/ssh.py
- cli/cook/subcommands/tail.py
- cli/cook/subcommands/wait.py
- cli/cook/version.py
- integration/bin/single-test.sh
- integration/tests/cook/test_cli_multi_cook.py
- integration/tests/cook/util.py
- `parse_entity_refs` now returns a second value, which is the list of only the clusters of interest
- `query_with_stdin_support` now returns the same second value
- sub-commands use the clusters of interest in downstream functions instead of all configured clusters
The issue that exposed this is that if a user passes an entity ref URL with the wrong base cluster URL, the "No matching data found" message was claiming that no data was found in all configured clusters, when in reality only the clusters from the provided URLs were queried.
> Filters the clusters of interest from the provided entity refs

- executor/cook/config.py
- executor/cook/executor.py
- executor/cook/progress.py
- executor/tests/test_executor.py
- executor/tests/test_progress.py
- make `max_message_length` config only affect length of progress messages
- refactoring: make `send_message` expect a dictionary instead of a string
It simplifies the code to make the max message length directly apply to the progress message length. Since the length check only applies to the progress messages, we are still backward compatible in terms of consumption of the config.
> makes message length config responsible only for progress messages

- executor/cook/_version.py
- executor/cook/executor.py
- executor/cook/progress.py
- executor/cook/util.py
- executor/tests/test_executor.py
- executor/tests/test_progress.py
- executor/tests/utils.py
- narrows OSError handler to only trigger task exit only for out of memory OSErrors
- adds exception handling logic to send_message
There are a few error classes (e.g. `socker.error`) that extend `OSError` and are currently incorrectly being treated as out of memory errors. This PR fixes this bug.
In addition, we are adding exception handling logic to sending of messages to correctly treat network error as transient errors and allow the executor to chug along.
> Cook Executor:  narrows OSError handler to only trigger task exit only for out of memory

- jobclient/src/main/java/com/twosigma/cook/jobclient/Executor.java
- jobclient/src/main/java/com/twosigma/cook/jobclient/Instance.java
- jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/src/test/java/com/twosigma/cook/jobclient/InstanceTest.java
- jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java
- adds support for configuring the executor field on a job and populating the executor field on an instance
This will enable the `JobClient` to specify the executor to use while submitting/loading a job. Additionally, it also allows displaying the executor used in an instance.
> Job Client: adds support for configuring the executor field on a job and populating the executor field on an instance

- cli/cook/querying.py
- cli/cook/util.py
- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- groups UUIDs into batches of at most 100 when querying
- modifies 2 integration tests (`show`, `wait`) to query for 200 jobs each
We discovered a bug where querying for too many UUIDs in the same request was failing due to hitting the limit of the query string length. This change allows us to ask for as many UUIDs as needed, but in batches.
> Adds batching to queries made from cs

- scheduler/src/cook/components.clj
Fix error caused by trying to attach meta-data to the Kerberos middlewar *Var* instead of the *Fn*.
Clojure doesn't magically dereference Vars for you when calling `with-meta` like it does when you try to call them like a function.
> Deref Kerberos middleware fn var before adding meta-data

- cli/cook/subcommands/kill.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- batches kill requests coming from `cs` to avoid hitting the query string length limit
Now that you can pipe from `cs jobs` to `cs kill`, it's possible that users will want to, for example, kill 1000 running jobs with something like:
```bash
$ cs jobs --all --user root --name test01 --limit 1000 -1 | cs kill
```
If we don't batch the kill requests, we end up constructing a query string that is too long.
> Batches kill requests from cs

- integration/Dockerfile
- integration/bin/run-integration.sh
Removes unused docker support within the integration test docker image
Since we don't use docker within the integration tests docker image (we probably did at some point, but we don't anymore), deleting these docker-support-specific items from the integration docker image setup significantly simplifies the build process when using docker to build and run the integration tests.
> Simplify the integration tests docker image

- travis/minimesos
- travis/minimesosFile
Requires using a custom-patched minimesos docker image until minimesos
version 0.14 is released, which fixes a NPE bug.
- Disable Marathon in the Travis minimesosFile.
- Use custom-patched minimesos-cli image to fix NPE when Marathon is disabled.
Disabling Marathon should speed up our integration tests a bit, and use fewer resources in the restricted Travis VM environment.
> Disable Marathon in Travis tests

- scheduler/src/cook/mesos/schema.clj
- scheduler/test/cook/test/mesos/schema.clj
- treat `mesos-executor-terminated` as mea-culpa failures with a failure limit of 3
It is possible that the executor command configured on a Mesos agent is invalid as it has not been deployed there yet. This change allows us to tolerate such failures on potentially multiple hosts before treating the job as failed. In addition, since our current implementation requires subsequent instances to use the Mesos executor, we account for avoiding repeated failures (on potentially the same host) due to missing deployments.
> CS: Treats :mesos-executor-terminated as mea-culpa failures

- executor/cook/progress.py
- jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java
- adds support for configuring progress output and progress regex on a Job
Allow users of the `JobClient` to set the progress output file and regex String on a per Job basis.
> Job Client: adds support for configuring progress output and progress regex on a Job

- integration/tests/cook/cli.py
- Manually create and attach a TTY to `stdin` for `cs` CLI integration tests
The `cs` command will not behave as expected if `stdin` isn't attached to a TTY by default. This causes several tests to fail when running our integration suite with `pytest`.
> Manually attach TTY for CLI tests

- integration/tests/cook/test_cli.py
- renames `test_show_interesting_uuid` to `test_show_non_v4_uuid`
- makes the test pass if the UUID under test actually corresponds to a job
If the UUID under test corresponds to a real job, we still want the test to pass.
> Makes test_show_non_v4_uuid more reliable

- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- making several tests submit jobs with the name of the job being the name of the test
- making tweaks to several tests to make them more reliable and/or faster to complete
To reduce flakiness and increase our ability to troubleshoot it.
> Makes several CLI tests more reliable / faster

- integration/setup.cfg
Use thread-based timeouts by default in pytest by setting that option in `integration/setup.cfg`
It seems that most Linux systems don't allow us to run pytest with parallel testing enabled if using the default (signal) timeout method.
> Use thread-based timeouts by default in pytest cfg

- integration/tests/cook/util.py
Allow manually setting the Mesos URL used in our integration tests via the `COOK_MESOS_LEADER_URL` environment variable.
I'm setting this manually on my laptop as a workaround for running some test locally that need to talk directly to Mesos, but can't access Mesos via the default docker IP address.
> Allow setting COOK_MESOS_LEADER_URL env var for integration tests

- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
- Fixes a type error in the group-retry-allowed logic.
- Adds unit tests for the `/retry` endpoint using groups.
Group retries currently only work for admins. That's obviously not the intended behavior.
> Fix group retry allow logic

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/mesos/api.clj
Add the required `reason` query-string parameter to the Swagger annotations on the quota and share `DELETE` endpoints.
The required parameter should be documented, and we'd prefer a 400 (malformed) error over a 500 (internal server exception) error.
> Add required "reason" param to swagger for user limit delete ops

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/constraints.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/scheduler.clj
This change has two commits:
1. Reverts the commit removing fenzo group constraints
2. Adds explicit caching for each group's running cotasks (for rebalancing) and running cotask ids (for matching)
Both of these cases don't necessarily need a `core.cache` cache since they have a fixed number of elements, but I think it's more appropriate as an API than a map or something else.
> Re-enable group constraints

- integration/travis/run_integration.sh
- travis/show_executor_logs.sh
- travis/show_scheduler_logs.sh
- extracting the code for dumping the cook scheduler logs into a new `show_scheduler_logs.sh` script
- changing `integration/travis/run_integration.sh` to only dump scheduler logs, instead of all sandbox logs
When we have test failures, dumping all of the logs currently takes a really long time (> 30 minutes), and the actual cook scheduler log files get truncated due to the 4MB output limit on Travis.
> Stops dumping sandbox logs when there are test failures

- scheduler/CHANGELOG.md
- scheduler/project.clj
- Bump version to 1.9.1-SNAPSHOT
- Update change log and project version for v1.9.0 release
Cook Scheduler release
>  Cook Scheduler version 1.9.0 release

- scheduler/src/cook/mesos/api.clj
- fixing a few lines of whitespace in `api.clj`
To get more consistent formatting.
> Fixes some whitespace in api.clj

- cli/cook/subcommands/usage.py
- integration/tests/cook/test_cli.py
- removing the overall cluster utilization from `cs usage`
Fetching the metrics from Mesos can be very slow:
https://issues.apache.org/jira/browse/MESOS-4740
```bash
$ cs usage --user root
dev0
Share: No CPU Limit, No Memory Limit, No GPU Limit
Usage: 0.9 CPU, 144 MB Memory
Applications:
- cook-scheduler-cli
Usage: 0.6 CPU, 96 MB Memory
Job Groups:
- [ungrouped]
Usage: 0.3 CPU, 48 MB Memory
Jobs: 3
- foo (b910938b-732c-4636-b852-1e49499f99bd)
Usage: 0.3 CPU, 48 MB Memory
Jobs: 3
- 29881152-a851-4412-a655-9951343f9872
Usage: 0.3 CPU, 48 MB Memory
Job Groups:
- qux (28a7898e-92ef-4464-be79-57a52b93f696)
Usage: 0.3 CPU, 48 MB Memory
Jobs: 3
```
> Removes overall cluster utilization from cs usage

- scheduler/bin/run-docker.sh
- Remove the `-v` (verbose) setting from `run-docker.sh`
I accidentally copied this flag over from the Travis run-scheduler script. While it doesn't break anything, it's kind of annoying to have the whole script contents dumped to the terminal every time I run the script.
> Disable bash verbose mode in run-docker.sh

- integration/tests/cook/test_basic.py
- adding `test_submit_with_no_name`, which asserts that you can submit a job with no `name` field, and the scheduler will accept it and auto-populate the name to `cookjob`
We want to ensure that clients that may be submitting name-less jobs will continue to be able to do so.
> Adds integration test for submitting job with no name

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/api.clj
- adding `status` as an optional field on job submission
- adding an integration test to confirm that it works
The Java job client used to send status on job submission. We want to allow this for backwards compatibility.
> Allows status field on job submit for backwards compatibility

- integration/README.md
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
Refactor to support Kerberos authentication in multi-user integration tests.
This allows us to run our automated integration tests on Kerberos-enabled clusters.
> Add Kerberos support for multi-user integration tests

- integration/tests/cook/test_cli.py
- kills the job that is otherwise forever-waiting in `test_ssh_no_instances`
To avoid leaving behind a running job after running the integration tests.
> Kills waiting job in test_ssh_no_instances

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/test_cli_multi_cluster.py
- integration/tests/cook/test_impersonation.py
- integration/tests/cook/test_master_slave.py
- integration/tests/cook/test_multi_cluster.py
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- integration/travis/scheduler_travis_config.edn
- scheduler/container-config.edn
- scheduler/docs/scheduler-rest-api.adoc
- scheduler/src/cook/authorization.clj
- scheduler/src/cook/components.clj
- scheduler/src/cook/impersonation.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/spnego.clj
- scheduler/src/cook/util.clj
- scheduler/test/cook/test/authorization.clj
- scheduler/test/cook/test/impersonation.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/testutil.clj
Add support for explicitly-authorized users to impersonate other users (i.e., execute commands on another user's behalf). The set of actions that can be impersonated is also restricted.
Services built on top of cook can use this feature to integrate more seamlessly while still providing transparency to the end-user.
<del>This is a work in progress. This PR currently only contains the changes made to the scheduler. I need pytest support (#666) merged, along with some other changes, before I can get the integration tests running correctly in Travis. However, I see no reason to delay feedback on the actual implementation in the scheduler just because the feature is blocked on the integration infrastructure.</del>
The pytest and multi-user-test support is all merged, so this should be good to …
> User Impersonation

- .travis.yml
- integration/travis/prepare_integration.sh
- integration/travis/run_integration.sh
- travis/build_cook_executor.sh
- travis/install_mesos.sh
- Expand the run matrix to make what each job does explicit rather than having a level of indirection through the environment settings.
- Use faster `sudo: false` job instances where possible. (Requires the expanded run matrix.)
- Cache Mesos packages to avoid registering the mesosphere repository on most runs.
- Use the pre-installed Python v3.6.3 runtime (from the updated Travis images) rather than downloading and installing our own copy of the same runtime.
1. Since `sudo: false` is significantly faster (container vs vm), we should use it where possible.
2. We avoid installing Mesos on the jobs that don't use it.
3. Caching the Mesos `.deb` files on the jobs where we *do* use the library still speeds things up a bit, and avoids some failures we've seen semi-regularly with `apt-get`.
4. …
> Refactor .travis.yml to use faster infrastructure options

- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/quota.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/quota.clj
If a single job requires more resources than the user's entire quota, then reject the job.
It seems better to reject an unschedulable job at submission time, rather than letting the user submit a job that can never be scheduled (assuming the user's quota doesn't change).
This is particularly useful in scenarios where an organization has multiple Cook clusters, but the user only has quota on some of those clusters. Currently, a user could submit a bunch of jobs to a cluster where they have no quota, and the jobs just sit there forever. After this change, all jobs would be rejected on any clusters where the user has no quota.
> Reject submitted jobs that exceed user's quota

- scheduler/CHANGELOG.md
- scheduler/project.clj
- Bump version to 1.10.1-SNAPSHOT
- Update change log and project version for v1.10.0 release
Cook Scheduler release, including the user-impersonation feature.
> Cook Scheduler version 1.10.0 release

- integration/tests/cook/test_impersonation.py
- Add default timeout to impersonation tests (same as all the other test classes)
- Add the multi-user mark to the class since it does user switching
We should have a common mark on all tests that do user switching so that it's easier to selectively run these (switching them on or off).
> Mark impersonation tests with multi-user and default timeout

- scheduler/project.clj
- adding `^:displace` to the cheshire and fenzo `:dependencies`
- adding a new profile, `:oss` (activated in `:default`)
- moving the datomic-free and mesomatic `:dependencies` to `:oss`
The `:oss` profile allows Cook to be built with a more appropriate set of dependencies for a specific environment than the ones it defines (by using `lein with-profile -oss ...`). For example, one could drop in the datomic-pro library instead of the datomic-free library by creating a `profiles.clj` file that defines a profile which pulls in datomic-pro. Similarly, one could use an older version of the mesomatic library in environments that require it.
> Refactors :dependencies for easier replacement via profiles

- cli/cook/subcommands/usage.py
- cli/cook/version.py
- removing the request to `/settings` from `cs usage`
The request was there in order to get the mesos master when we were retrieving overall cluster utilization. Since we're no longer including that information, we should remove this as well.
> Removes superfluous /settings request from cs usage

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- integration/travis/scheduler_travis_config.edn
- scheduler/container-config.edn
- scheduler/docs/configuration.adoc
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/sandbox.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/sandbox.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/simulator.clj
- scheduler/test/cook/test/testutil.clj
- This reverts commit f2b5847 enabling the sandbox syncing for non-cook-executor instances
The PR is split into two commits. The first commit reverts a previous commit that disabled the syncer. The second commit handles merge conflicts and adds metrics.
We would like timely sandbox directory updates for tasks that are not executed via the cook executor. This can significantly save the load time on the list pages as they do not trigger the sandbox syncing logic. Additionally, saving the sandbox directory into datomic means once the directory is available, it is consistently always rendered instead of relying on the availability of the data from the Mesos agent state.
> CS: Revert "disable triggering syncing agent sandbox entries into datomic

- executor/README.md
- executor/setup.cfg
- executor/setup.py
- executor/travis/run_tests.sh
- executor/travis/setup.sh
Move the Cook Executor from nose to pytest.
Mainly for consistency, but we're also hoping this will help us debug #678.
Closes #699.
> Use pytest for executor tests

- executor/cook/_version.py
- executor/cook/subprocess.py
-  handles NoSuchProcess thrown by `psutil`.Process (instead of `ProcessLookupError`)
- It correctly catches the exception thrown by the `psutil` library and avoids an unexpected error while trying to terminate a task.
> Handles NoSuchProcess thrown by psutil.Process

- jobclient/src/main/java/com/twosigma/cook/jobclient/constraint/Constraint.java
Add JSONException to JobClient Constraint interface.
@WenboZhao asked for the exception annotations on this method in the concrete class, and it looks like we need it in the interface as well.
> Add JSONException to JobClient Constraint interface

- integration/tests/cook/test_basic.py
Add the `docker` pytest mark to docker-related integration tests.
Allows us to filter using `pytest -m docker` or `pytest -m 'not docker'` to run or exclude tests using docker.
> Add docker mark to docker-related integration tests

- executor/tests/test_executor.py
Add the `xfail` mark to the test_manage_task_terminated executor test. 
This test is failing regularly, and we're not sure why. See #678.
> Mark test_manage_task_terminated executor test as flaky

- executor/travis/setup.sh
Install dependencies for Cook Executor tests into user's home directory.
The deps aren't being cached by Travis right now because they're being installed globally rather than locally.
> Use local pip install for executor deps in Travis

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
- Do not encode output from /rawscheduler POST as JSON
Fix a backwards compatibility change from #316
> Fix string encoding on rawscheduler post

- integration/README.md
- integration/tests/cook/conftest.py
- integration/tests/cook/util.py
Reworks how tests users are generated across xdist workers so that there aren't user collisions when restricted to a limited number of test users with Kerberos.
This lets us run all of the tests together even when using Kerberos, rather than having to run the multi-user tests separately so that they could be run sequentially.
> Enable parallel multi-user integration tests with Kerberos

- scheduler/src/cook/mesos/api.clj
Lift the "start-time" timestamp out of the handler-construction function.
The timestamp was being re-evaluated to `now` on each request.
Fixes #711.
> Lift start-up-time out of the /info handler function

- scheduler/docs/faq.md
- scheduler/src/cook/mesos/task.clj
- scheduler/test/cook/test/mesos/task.clj
- Makes the job resources (cpus, gpus and mem) available as environment variables to the Mesos task
- Given these environment variables, jobs can decide how much memory and threads they can allocate at runtime.
> cs: provides env variables that contains the resources requested by the job

- scheduler/Dockerfile
- scheduler/bin/run-docker.sh
- scheduler/bin/run-local.sh
- scheduler/config.edn
- renaming `container-config.edn` to `config.edn`; we don't only use it when running in a container
- introducing `COOK_ONE_USER_AUTH` so that the user name can be specified at runtime
- allowing `MESOS_NATIVE_JAVA_LIBRARY` to be overriden at runtime
- setting `COOK_EXECUTOR_PORTION=1` in `run-local.sh`
These changes were mostly needed in order to run Cook Scheduler against a real Mesos (as opposed to minimesos) on Ubuntu.
> Improves configuration for running against a real Mesos

- scheduler/src/cook/components.clj
- printing the full cause trace when there is an error on startup
To make startup errors (e.g. a bogus configuration) easier to identify and correct.
> Improves error handling on startup

- integration/tests/cook/test_multi_user.py
Always delete all jobs created by a multi-user integration test, including the default (trivial) jobs.
Fixes a bug in multi-user integration tests where a quota test running directly before the usage test may throw off the observed usage.
> Clean up jobs submitted by quota tests

- scheduler/src/cook/mesos/monitor.clj
- scheduler/src/cook/mesos/util.clj
- using `util/get-pending-job-ents` instead of using the metatransaction-filtered `db`
- adding `util/get-running-job-ents` and using it for running jobs
Running queries using the metatransaction-filtered `db` is very slow.
> Converts pending jobs query from using metatransaction to commit latch

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/sandbox.clj
- scheduler/test/cook/test/mesos/sandbox.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- Move the logic to query datomic for presence of sandbox directories into a single thread
On large clusters, the sandbox syncer can spin up many threads (in the order of hundreds) that trigger datomic queries. Datomic has a read concurrency setting which causes these queries to start becoming a performance concern if many threads make read queries that end up hitting backing storage. As a result, the sandbox syncer starts performing poorly as well as affecting the performance of other read queries in the cook scheduler. With the single reader thread version for the syncer, we can minimize the effect we have on datomic read performance.
[Datomic Peer properties](https://docs.datomic.com/on-prem/system-properties.html#peer-properties)
> CS: Ensures the task filters for the sandbox syncer occur on a single thread

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/sandbox.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/sandbox.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- Avoid using datomic queries to filter entries received from the host
- Instead 'remember' the tasks which requested sandbox directory lookup and use them in the filter
We want to avoid making datomic queries where we can to avoid introducing performance issues.
> CS: runs the sandbox syncer without the need for datomic reads for task filtering

- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/util.clj
- Error handling in the `job-ent->map` function
- Usages of `job-ent->map` now handle nil return values
If `job-ent->map` fails it can end up preventing jobs from being scheduled as the ranker has not ranked all queued jobs.
> CS: ensures scheduling continues even if we are unable to convert a job entity into a map

- integration/requirements.txt
- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/task_stats.clj
- scheduler/src/cook/scratch.clj
- adding new namespace, `task-stats`, for querying tasks by status and time range, and then generating statistics (run time, cpu time, and mem time overall, by reason, and by user and reason)
- adding new admin-only endpoint, `/stats/instances`, that exposes the above stats
- adding a new scractch function, `populate-dummy-data`, that can be used to generate dummy instances for use in testing
We want to be able to analyze the cpu time and memory time we are spending on, for example, successful vs. failed instances.
```bash
$ curl -s 'localhost:12321/stats/instances?status=failed&start=2018-02-01&end=2018-02-28' | jq                                                                                                                                       
{
"by-reason": {
"Command exited …
```
> Adds endpoint for instance stats by status

- scheduler/docs/configuration.adoc
- scheduler/docs/optimizer.md
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/optimizer.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/src/cook/util.clj
- scheduler/test/cook/test/mesos/optimizer.clj
- scheduler/test/cook/test/simulator.clj
The PR introduces a new component into Cook, the optimizer, that is intended to take longer, more global views of scheduling.
This introduces the interface that we can then build off of.
> Initial interface for optimizer component

- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/constraints.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/constraints.clj
- scheduler/test/cook/test/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- Introduces `rebalancer-reservation-atom` to reserve hosts for jobs which preempted several other jobs
- Reserves hosts after each rebalance cycle
- Releases reservations when all jobs reserving the host have been scheduled
It's possible when preempting multiple tasks to get a new offer which only represents part of the total resources prevented. Then, smaller, lower-priority jobs could be scheduled on this offer which delays scheduling for the actual job the rebalancer was trying to launch.
> Support reserving hosts from the rebalancer

- scheduler/src/cook/mesos/scheduler.clj
- introducing new histograms by failure reason for run time, cpu time, and mem time
- updating the histograms when a task fails
We want to enable better visibility into the amount of time and resources spent on various failures, e.g. "preempted by rebalancer".
> Adds histograms by failure reason for run/cpu/mem time

- scheduler/simulator_files/example-trace.json
- scheduler/test/cook/test/simulator.clj
A bunch of small improvement to the simulator. It is based on top of the optimizer commit. Improvements include:
-  Support for not running the rebalancer every cycle
- Allowing the datomic url to be configurable so that 
- Add support for groups and expected runtime on tasks
- Periodically force a full gc
These changes allow simulating a wider range of cases.
> Simulator improvements

- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/datomic.clj
- scheduler/src/cook/impersonation.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/scratch.clj
- scheduler/src/cook/util.clj
- scheduler/test/cook/test/components.clj
- scheduler/test/cook/test/config.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/simulator.clj
- `lazy-load-var` was defined twice (once in `cook.components`, again in `cook.util`), consolidating
- moving all config-related code from `cook.components` to the new `cook.config`
- deleting some dead code
For readability / organization. Having all of the config code in one place makes it easier to read the code.
> Refactors config code into config namespace

- scheduler/src/cook/mesos/rebalancer.clj
- log when the rebalance was a no-op
- minor refactoring to sort keys and remove unused values
Helps us quickly identify why a rebalance iteration was a no-op.
> cs: adds logging for the iteration where the rebalance was a no-op

- scheduler/src/cook/mesos/api.clj
- adds the job creation rate metric
This lets us view the rate at which jobs are being submitted into the cluster (in addition to running and pending jobs).
> cs: adds the job creation rate metric

- scheduler/src/cook/mesos.clj
- uses cond-> instead of merge and when
Improved readbility. This refactoring helped me clearly identify the arguments to `mesomatic.scheduler/scheduler-driver`
> cs: refactor: uses cond-> instead of merge and when

- scheduler/docs/configuration.adoc
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/task.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/task.clj
- scheduler/test/cook/test/simulator.clj
- this sets the user that Cook will override and set as the user to run tasks on Mesos with
Allows us to mimic submitting jobs from many users.
> cs: adds support for Mesos run-as-user

- executor/tests/test_subprocess.py
- integration/tests/cook/test_multi_user.py
- scheduler/src/cook/mesos/util.clj
- New query functions
- 
- 
Makes API query performance for waiting/running jobs for a user in a time window go from O(#waiting/running jobs in entire system) to O(# jobs that user submitted during the time window)
Makes simple 'cs jobs' go 3x-10x faster (in staging environment)
> New query functions

- cli/cook/mesos.py
- cli/cook/subcommands/cat.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- adding `mesos.download_file` for calling the Mesos `files/download` endpoint
- changing `cat` to use `mesos.download_file`
- adding an integration test for `cat`ing a binary file
Sometimes you just need to `cat` a binary file. 
The Mesos `files/read` endpoint [assumes UTF-8 encoding of file contents](https://issues.apache.org/jira/browse/MESOS-8103).
> Fixes support for cs cat on a binary file

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/api.clj
- checking for `(not (t/after? end-time start-time))` on `/stats/instances`
- adding an integration test case for it
Currently you get a 500 and an unhelpful error message.
> Cleanly handles invalid time range on /stats/instances

- scheduler/src/cook/mesos/scheduler.clj
- adding counters for the total cpu, mem, and run time by failure reason
- changing the units for the by-reason metrics from milliseconds to seconds (for all) and MB to GB (for mem)
In addition to the existing histograms, we want to enable monitoring of the total amount of resources spent on various failures. 
As for the unit changes, it's rare for a job to use less than 1GB or take less than 1 second in the wild, which means that the new units make it easier to reason about the metrics. The changes also avoid the risk of overflowing the new counters, since they continually increase until a leadership change occurs. Without the unit changes, each memory time counter can accommodate ~14 petabyte-weeks before overflowing. With the unit changes, each memory time counter can accomodate ~14 …
> Adds counters for total cpu/mem/run times by failure reason

- scheduler/src/cook/mesos/scheduler.clj
- Change UUID generation for tasks to be more temporal.
- 
- 
- 
Increases the hit rate and the locality for storage of these datomic ID's.
> Use d/squuid to derive task ID's do that they're more tightly clustered.

- scheduler/src/cook/mesos/util.clj
Revert most of "New query functions (#732)"
The new query functions do very badly for long time ranges. Revert temporarily
and rework the patch with a hybrid of old and new query.
Keep the time out changes in the original patch.
> Revert most of "New query functions (#732)"

- scheduler/project.clj
Upgrade to 17.0. This shows up in a lein repl. Outside of a lein repl,
you may or may not get a newer version based on how you handle
classpath construction.
- 
- 
-
> Guava 16.0 is incompatable with datomic cassandra bridge.

- scheduler/project.clj
Switch to G1GC and turn on string deduplication. 
Remove deprecated JDK option
- In a test with a 500k jobs in queue, there were 92M strings in memory, with the char arrays accounting for a third of the heap.
- We have been using G1GC internally for a while, so expect that change to be safe.
> Change JVM options. remove MaxPermSize and add +UseStringDeduplication

- executor/tests/test_subprocess.py
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/util.clj
- adding the ability to list jobs on `/jobs`
- `/jobs` will not filter out custom executor jobs
We want to give users and tools the option of including custom executor jobs when listing (while maintaining backwards compatibility).
> Adds support for including custom executor jobs in /jobs

- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/testutil.clj
- When starting `monitor-tx-report-queue`, first query for any running instances for completed jobs and attempt to kill them
Some instances may have been "missed" during the leadership change and will still be running when the new leader takes over and never killed.
> Kill all running tasks for completed jobs

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/mesos/api.clj
- adding call to `wrap-seq` to properly handle `/jobs` queries with a single state
- adding an integration test to verify
Currently if you pass a single state query param to `/jobs`, you get an error.
> Fixes bug with single-state /jobs requests

- executor/tests/conftest.py
- please see https://github.com/twosigma/Cook/issues/749
- Loads pymesos module in conftest.py to avoid main thread errors
To get more consistent builds
> ce: ensures the pymesos module is loaded in the setup process

- scheduler/src/cook/mesos/api.clj
-  Put a metric on the actual response generation time for the `/list` API call
- We don't actually metric this user-visible time.
> Lets capture the time it takes to get a list endpoint out.

- scheduler/src/cook/mesos/api.clj
> Revert "Lets capture the time it takes to get a list endpoint out."

- scheduler/test/cook/test/mesos/util.clj
- Add some unit tests for named-filter-fn == nil as well as non-null.
- 
- 
- We test it == (constantly true), but name-filter-str->name-filter-fn only sets it to a regexp matcher closure or nil. 
- This exercises the special case nil in the query logic which wouldn't be exercised with the 'constantly true' existing implementation.
> Expand test coverage with name-filter-fn.

- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/testutil.clj
Vastly improved query functions. I tested the new git-active-jobs-by-use-and-state on a few thousand production queries and it was identical each time. 
- get-active-jobs-by-user-and-state is rewritten on top of seek-datums and is vastly faster, I see up p50's 5x-100x faster. p95's are 2x-5x faster.
- get-completed-jobs-by-user has had small tweaks made to improve it; removing reflection and minimizing datomic queries.
- Collect a histogram of metrics of time-to-search, as a function of the time range being searched.
- Much greater performance.
> New query functions (take 2)

- scheduler/Dockerfile
- scheduler/bin/run-docker.sh
- scheduler/datomic/datomic_transactor.properties
- scheduler/docker/run-cook.sh
- exposing the ports that datomic uses from the docker container
- setting the `alt-host` property in the datomic properties file
So that we can connect to the datomic running inside docker from the host machine, in order to run (for example) scripts that seed data for testing.
> Allows for connecting to datomic in docker from host

- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/testutil.clj
This reverts commit a2e57079a046b9322946c07ee77da1941fd7619a.
- Revert the change
- 
- 
For an unknown reason, it makes production queries much slower.
> Revert "New query functions (take 2) (#771)"

- integration/tests/cook/test_cli.py
- replacing `cli.wait` with `util.wait` in `test_cat_large_file_no_newlines`
We've seen this test fail sporadically on the "wait until completed" step, and when it does, we don't get much information out of `cs wait`. Since the point of this test is not to make sure `cs wait` works, let's replace it with the more debuggable `util.wait`.
> Makes test_cat_large_file_no_newlines more debuggable

- scheduler/test/cook/test/mesos/api.clj
If the computation takes 0ms, then before=after, and the filter
before <= X < after never matches any job.
- 
- 
- 
- Fix flaky unit test
> Fix flaky unit test

- cli/cook/subcommands/submit.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- adding `--gpus` flag to `cs submit`
- adding an integration test for `--gpus`
This allows users to submit jobs with gpus using `cs`. See issue #793 for more context.
> Adds support for submitting jobs with gpus

- integration/tests/cook/test_basic.py
- integration/travis/run_integration.sh
- integration/travis/scheduler_travis_config.edn
- scheduler/Dockerfile
- scheduler/bin/run-docker.sh
- scheduler/bin/run-local.sh
- scheduler/config.edn
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/testutil.clj
- Add support for scheduler to listen on a separate port for SSL connections
Some clients might want to have a secure connection to the scheduler
> Add SSL support to scheduler

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- switching from 1 to 2 attempts in the instance stats test jobs
- making `wait_for_running_instance` look for any running instance, instead of just the first one
We've seen these tests fail because the jobs fail due to Mesos. For example:
```bash
2018-04-06 17:14:09,884 INFO  cook.mesos.scheduler [clojure-agent-send-pool-0] - Mesos status is: #mesomatic.types.TaskStatus{:task-id #mesomatic.types.TaskID{:value 3564101f-2aef-4074-8ace-4aaa88d6e484}, :state :task-error, :message Task uses more resources mem(cook):256; cpus(cook):0; cpus(*):1 than available ports(cook):[32002-33000]; mem(cook):3072; disk(cook):10000; ports(*):[31000-32000]; disk(*):10000; cpus(*):4; mem(*):4096, :source :source-master, :reason :reason-task-invalid, :data #object[com.google.protobuf.LiteralByteString …
```
> Makes instance stats tests more reliable

- scheduler/api-only-config.edn
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- adding `:api-only?` as a config field
- when `:api-only?` is turned on, and the zookeeper configuration is turned off, cook will not participate in scheduling, and will only accept api requests
We would like to leverage api-only nodes in order to run performance tests that evaluate upcoming releases without the risk of disrupting "live" clusters.
> Introduces api-only mode

- scheduler/src/cook/mesos/monitor.clj
- setting the counters in `monitor.clj` to 0 instead of removing them
When using singlestat panels in Grafana, the `current` function uses the last non-null value from the series. As a result, the panels can show, for example, cpus and memory in use when the user in question actually has nothing running. Explicitly setting the counters to 0 resolves this.
> Sets monitor metrics to 0 instead of removing them

- scheduler/bin/run-docker.sh
- Set COOK_KEYSTORE_PATH in run-docker.sh
Fixes running via docker
> Set COOK_KEYSTORE_PATH in run-docker.sh

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/test_multi_user.py
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/util.clj
- adding `pools` sub-map to `/usage`, which contains usage info for all pools, when the pool is not explicitly provided
We decided, as explained in issue #755, that it makes sense to default to providing the information for all pools, instead of just for the default pool.
> Provides /usage sub-map with all pools in the default case

- jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java
- jobclient/src/test/java/com/twosigma/cook/jobclient/JobClientTest.java
- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
- adds support for handling transaction timeouts during job submit
If we know that jobs have been created successfully despite reporting a transaction timeout, we should respond with a success.
```
DEBUG [main]: Response String for submitting jobs{...} is {"error":"Exception occurred while creating job - :db.error/transaction-timeout Transaction timed out."}
WARN  [main]: POST experienced transaction timeout via uri http://127.0.0.1:12321/rawscheduler
INFO  [main]: Sleeping 10000ms to allow transaction opportunity to complete
INFO  [main]: Verifying if all the jobs were created despite the transaction timeout message
INFO  [main]: All 100 jobs were created despite the transaction timeout message
```
```
DEBUG [main]: Response String for submitting jobs{...} is {"error":"Exception occurred …
```
> jc: adds support for handling transaction timeouts during job submit

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_multi_user.py
- Adds a new environment variable, COOK_ALLOWED_ORIGIN, to set the origin used in the CORS integration tests
- Conditionally check for the pools field on usage tests
- Fix SSL test when SSL is not configured
For testing production environments, you may need to use different values than the ones configured in the tests.
Resolves #817
> Fix integration tests

- integration/tests/cook/mesos.py
- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- logging the job status before each `docker inspect`
- logging the job status in the `finally` block, right before killing the job
- logging the contents of all files in the root of the instance's sandbox, e.g.:
```bash
2018-04-19 15:23:36,837 [DEBUG] http://172.17.0.7:5051 "GET /files/download?path=%2Fvar%2Flib%2Fmesos%2Fagent-2972150625%2Fslaves%2Fad2f8ac9-3643-49f2-be8b-0786c22eaa78-S0%2Fframeworks%2Fcook-framework-1524152436%2Fexecutors%2Fd1af2ac7-a642-4c3b-b61a-668ff0830880%2Fruns%2F5cbb9ce3-3f7e-4a36-8e09-b57532388ac4%2Fstderr HTTP/1.1" 200 2267
2018-04-19 15:23:36,838 [INFO] I0419 20:23:36.269697 21616 logging.cpp:199] Logging to STDERR
I0419 20:23:36.270844 21616 process.cpp:1067] libprocess is initialized on 172.17.0.7:34095 with 8 worker threads
I0419 20:23:36.271612 21616 …
```
> Adds more logging to test_docker_port_mapping

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- integration/travis/run_integration.sh
- integration/travis/scheduler_travis_config.edn
- scheduler/bin/run-docker.sh
- scheduler/datomic/data/seed_pools.clj
- scheduler/docker/run-cook.sh
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/pool.clj
- scheduler/test/cook/test/mesos/pool.clj
- moving the seeding of pools to before starting cook scheduler, so that they're already there at startup
- making the pool-seeding setup the database schema
- adding guards on cook scheduler startup against:
- pools in the database, but no default pool configured
- the configured default pool does not match any pool in the database
We want to prevent the situation where there are pools in the database, but we don't have a valid configuration for which of those pools is the default. Resolves #813.
> Guards against invalid default pool configuration

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- logging the complete group and member jobs json in `group_submit_retry`
- increasing the sleep from 10 to 120 seconds in `test_group_failed_only_change_retries_all_active`
We've seen `test_group_failed_only_change_retries_all_active` fail with:
```bash
...
2018-04-23 21:29:20,889 [DEBUG] http://localhost:12321 "GET /group?uuid=00807c9e-ecd5-4229-865b-49eff5512cb8&detailed=true HTTP/1.1" 200 None
2018-04-23 21:29:20,897 [DEBUG] Currently {'running': 0, 'waiting': 5} jobs in group 00807c9e-ecd5-4229-865b-49eff5512cb8
2018-04-23 21:29:20,897 [DEBUG] wait_until condition not yet met, retrying...
2018-04-23 21:29:21,910 [DEBUG] http://localhost:12321 "GET /group?uuid=00807c9e-ecd5-4229-865b-49eff5512cb8&detailed=true HTTP/1.1" 200 None
2018-04-23 21:29:21,911 [DEBUG] Currently {'running': 0, …
```
> Adds debugging info to group_submit_retry

- cli/cook/subcommands/show.py
- cli/cook/subcommands/submit.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- adding `--pool` / `-P` to `cs submit`
- adding the pool to the `cs show` output
We want to allow specifying the pool to submit to, and viewing it, from `cs`.
> Adds pool to cs submit, show

- integration/tests/cook/test_cli.py
- `util.pools` -> `util.all_pools`
The function was renamed and this test did not get updated.
> Corrects function reference (pools -> all_pools)

- executor/setup.cfg
- disables parallelism in cook executor unit tests
With parallel tests, it is possible that interleavings of method calls cause tests to fail, e.g. by `mkdir` failing as file already exists:
```
____________________ ExecutorTest.test_executor_launch_task ____________________
[gw1] linux -- Python 3.6.3 /opt/python/3.6.3/bin/python3.6
self = <tests.test_executor.ExecutorTest testMethod=test_executor_launch_task>
def test_executor_launch_task(self):
task_id = tu.get_random_task_id()
>       stdout_name = tu.ensure_directory('build/stdout.{}'.format(task_id))
tests/test_executor.py:747: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
output_filename = 'build/stdout.393667'
def ensure_directory(output_filename):
""""Ensures that the directory that contains …
```
> disables parallelism in cook executor unit tests

- integration/tests/cook/mesos.py
- integration/tests/cook/test_basic.py
- adding tighter exception handling to `dump_sandbox_files`
- dumping all sandbox files in the `finally` block of `memory_limit_exceeded_helper`
We've seen test failures where the job that is supposed to exceed its memory and get killed doesn't get killed within the timeout we expect. We want to have more information in order to track down the root cause(s).
> Adds debugging info to the memory-limit tests

- integration/tests/cook/test_basic.py
- instead of waiting for the job to complete, simply wait for an instance to appear
We've seen this test fail because the job doesn't complete within the timeout, but the instance does show the correct number of ports, which is all we really care about in this particular test.
> Makes test_ports more reliable

- integration/tests/cook/test_basic.py
- scheduler/src/cook/datomic.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- adding `datomic/transact`, which requires a handler function for transaction timeouts
- calling `datomic/transact` from `launch-matched-tasks!` and logging the matches that are in question when the transaction times out
- adding a unit test
To have better logs if/when this situation occurs in the wild. We've seen it happen in test environments.
> Improves logging when Datomic task transactions time out

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/schema.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/util.clj
- Only put job in waiting state if there are still attempts remaining
- Do not allow setting retries to less than attempts consumed
Prevents jobs getting into a bad state, where they have negative attempts remaining.
> Fix bugs in /retry endpoint

- integration/travis/run_integration.sh
- travis/gdrive_upload
- travis/upload_logs.sh
Upload logs when the integration tests fail in Travis-CI.
We need the logs for debugging failures, but there are too many to simply dump them on stdout. (Travis has a hard limit on the length of your job output.)
> Travis log uploads

- integration/tests/cook/test_cli.py
- integration/tests/cook/util.py
- logging job details and sandbox files in `group_submit_kill_retry`
We've seen test failures like this:
```bash
=================================== FAILURES ===================================
__________________ CookTest.test_group_change_killed_retries ___________________
[gw2] linux -- Python 3.6.3 /opt/python/3.6.3/bin/python3.6
self = <tests.cook.test_basic.CookTest testMethod=test_group_change_killed_retries>
def test_group_change_killed_retries(self):
jobs = util.group_submit_kill_retry(self.cook_url, retry_failed_jobs_only=False)
for job in jobs:
>           self.assertNotEqual('failed', job['state'], f'Job details: {json.dumps(job, sort_keys=True)}')
E           AssertionError: 'failed' == 'failed' : Job details: {"command": "sleep 1", "constraints": [], "cpus": 1.0, …
```
> Adds debugging info to group_submit_kill_retry

- integration/tests/cook/mesos.py
- integration/tests/cook/test_basic.py
- asserting that each job actually succeeded
- dumping the sandbox logs in the `finally` block
We've seen this test fail with:
```bash
def test_instance_stats_success(self):
name = str(uuid.uuid4())
job_uuid_1, resp = util.submit_job(self.cook_url, command='exit 0', name=name, cpus=0.1, mem=32)
self.assertEqual(resp.status_code, 201, msg=resp.content)
job_uuid_2, resp = util.submit_job(self.cook_url, command='sleep 1', name=name, cpus=0.2, mem=64)
self.assertEqual(resp.status_code, 201, msg=resp.content)
job_uuid_3, resp = util.submit_job(self.cook_url, command='sleep 2', name=name, cpus=0.4, mem=128)
self.assertEqual(resp.status_code, 201, msg=resp.content)
job_uuids = [job_uuid_1, job_uuid_2, job_uuid_3]
try:
util.wait_for_jobs(self.cook_url, job_uuids, 'completed')
instances = …
```
> Adds debugging info to test_instance_stats_success

- integration/tests/cook/test_basic.py
- Just check failed instances, not all instances
Sometimes, the second to last instance can still be "unknown" when the test triggers, causing it to fail
> Fix for flaky mea culpa test

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
- Return a 409 (Conflict) when a write to /retry does not retry the job or change the max-retries
Reduce user confusion around /retry requests which don't affect the job.
> Return 409 (Conflict) when call to /retry is a no-op

- integration/tests/cook/test_basic.py
- moving the assertion that status == success to after the `wait_for_job`
Otherwise, there's a race between the job finishing and the assertion running.
> Fixes race in test_list_jobs_by_completion_state_with_jobs_endpoint

- cli/cook/subcommands/tail.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- allowing the user to not specify a path, in which case `stdout` is used
It's nice when running, for example, `cs tail -f <uuid>`, to not have to specify the path.
> Defaults tail path to stdout

- cli/cook/subcommands/jobs.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- changing the message from `No jobs found in CLUSTER.` to `No running / waiting jobs for USER found in CLUSTER.`
```bash
$ cs jobs --success
No successful jobs for dpo found in dev0.
$ cs jobs --failed                                                                                                                                                                                                                  
No failed jobs for dpo found in dev0.
$ cs jobs --running --waiting --all                                                                                                                                                                                                 
No waiting / running / completed jobs for dpo found in dev0.
$ cs jobs --running --waiting
No running / waiting jobs …
```
> Adds states and user to 'no jobs found' message

- travis/upload_logs.sh
- adding `--all` to the `docker ps` that is responsible for uploading the Mesos master logs
We've seen cases where the Mesos master seems to crash, and we want to be able to inspect its logs in these cases.
> Uploads Mesos master logs even when container stopped

- travis/install_mesos.sh
Fix the `apt-get` commands in our Mesos install script.
Cached installs of Mesos are no longer working because the cached debian packages now have conflicts with the default packages in the default travis-ci debian image.
> Fix Travis-CI apt-get cached installation

- integration/travis/run_integration.sh
- invoking `upload_logs.sh` in the case of Cook Scheduler failing to start up
To have more troubleshooting information in these cases.
> Uploads logs when Cook fails to start

- scheduler/docs/configuration.adoc
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos/constraints.clj
- scheduler/test/cook/test/mesos/constraints.clj
- scheduler/test/cook/test/testutil.clj
- Adds support for a new "estimated completion" constraint
Some long-running jobs are scheduled on cloud spot VMs which are expected to be short-lived, leading to the jobs losing work and being rescheduled on different VMs. This constraint uses the `expected-runtime` of the job as a baseline as well as a configured age for each host to determine whether the job is expected to run to completion on the host before scheduling.
> Add estimated-completion-constraint

- cli/cook/querying.py
- cli/cook/version.py
- integration/requirements.txt
- integration/tests/cook/test_cli.py
- avoiding throwing when `sys.stdin.isatty()` returns  `False` if there is nothing to actually be read from `stdin`
Inside Jupyter notebooks, `sys.stdin.isatty()` returns `False`, but that doesn't mean something is actually available to read from `stdin`. Therefore, we need to be more precise about when we display the `You cannot supply entity references both as arguments and from stdin` error.
Before:
After:
> Fixes cs show inside Jupyter notebooks

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/api.clj
- Adds a "pools" sub-map with the pool-specific limits in the quota and share response if the pool parameter is not specified.
Provide a simple way for a user to learn about their share or quota across several pools.
> Add "pools" submap to quota and share responses

- integration/tests/cook/test_basic.py
- adding a second attempt to the jobs that we assume will succeed
We've seen this test fail because one of the presumed-to-succeed jobs actually fails, and we want to be more tolerant to this.
> Makes test_list_jobs_by_completion_state more resilient

- integration/tests/cook/test_impersonation.py
- removing unused `itertools` import
- wrapping overly long line
- removing unused local variable
To keep things clean.
> Minor cleanup in impersonation tests

- cli/cook/exceptions.py
- cli/cook/mesos.py
- cli/cook/querying.py
- cli/cook/subcommands/tail.py
- cli/cook/version.py
- cli/setup.py
- executor/tests/test_executor.py
- integration/tests/cook/test_cli.py
- travis/upload_logs.sh
- adding `--wait` flag to `cs tail`
To allow waiting until the job is running and the file being tailed is available when running, for example, `cs tail -f ...` on a pending job.
> Adds optional waiting to cs tail

- scheduler/CHANGELOG.md
- scheduler/project.clj
To release the task reconciliation fix.
> Releases Cook Scheduler v1.17.2

- integration/tests/cook/test_multi_user.py
- scheduler/src/cook/mesos/api.clj
- improving the error message returned when a user is not authorized to kill a job
We would like to expose this error in `cs`, and we want it to be as clear as possible.
> Improves job-kill authorization error message

- scheduler/src/cook/mesos/api.clj
- `dissoc`ing the `:command` field from jobs when logging the submission
Commands in the wild can be very long, and there is very little value in being able to view the command in the log file, since we can view it by querying Datomic.
> Removes command from the 'Submitting jobs' log

- integration/tests/cook/mesos.py
- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/test_impersonation.py
- integration/tests/cook/test_master_slave.py
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- if `COOK_TEST_DOCKER_IMAGE` is set, use it in `util.minimal_job`
- if `COOK_TEST_SKIP_SANDBOX_DUMP` is set, don't attempt to dump sandbox contents
- in several tests, switch from checking if the cook executor is configured to checking if the cook executor was actually used before assuming that the exit code is present
- introducing `util.has_ephemeral_hosts` which returns `True` if either `COOK_TEST_EPHEMERAL_HOSTS` is set, or if the estimated completion constraint is configured
- in several tests, if the cluster under test has ephemeral hosts, then bail out instead of using `HOSTNAME` `EQUALS` constraints
- if `COOK_TEST_DEFAULT_TIMEOUT_MS` is set, use it instead of the default-default timeout of 2 minutes
We would like to be able to run our integration tests using docker containers …
> Adds support for running test jobs with docker

- scheduler/src/cook/authorization.clj
- scheduler/test/cook/test/authorization.clj
- adding `open-auth-no-job-killing`, an authorization function that allows anyone to do anything except kill jobs
For testing purposes only. Specifically, to test failed authorization on job kills.
> Adds a test authorization function that blocks job kills

- README.md
- adding the Slack sign-up badge to the top-level README
So that people can easily find our Slack and ask questions / provide feedback.
> Adds Slack badge to README

- integration/tests/cook/util.py
- instead of assuming that the 0th instance will be the one with the `output_url`, checking if *any* instance has an `output_url`
Tests that use this helper function will fail in cases where the 0th instance encountered an error, e.g. `Agent removed`.
> Makes wait_for_output_url more robust

- travis/upload_logs.sh
- adding the `mesos-slave` and `mesos-fetcher` logs to the logs tarball on failure
To have more information when troubleshooting test failures.
> Uploads minimesos agent logs on failures

- integration/tests/cook/test_basic.py
- instead of asserting exactly 2 instances, asserting at least 2 instances
There can be mea culpa failures that result in more instances, e.g. `Invalid Mesos offer`.
> Makes test_group_failed_only_change_retries_all_failed more reliable

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/src/cook/mesos/api.clj
- adding the container fields to the response when retrieving a job
- adding an integration test for this
So that the container fields can be inspected after submitting a job.
> Adds container fields when retrieving a job

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
- adding `reason_mea_culpa` (true/false) to the instance json
Currently, users have to manually check whether each failure type is considered *mea culpa* using the `/failure_reasons` endpoint.
> Adds reason_mea_culpa to instance json

- .travis.yml
- integration/tests/cook/util.py
- integration/travis/run_integration.sh
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos/pool.clj
- scheduler/test/cook/test/config.clj
- scheduler/test/cook/test/mesos/pool.clj
- adding `--pools={on/off}` to `run_integration.sh`
- adding a build to the travis job that runs with `--pools=off`
We want to ensure that changes we make for pools don't break environments that don't have pools.
> Adds travis build with pools turned off

- cli/cook/cli.py
- Change the way `--version` is handled to use `argparse`'s `action='version'` mechanism
This allows `cs --version` to bypass the subparser's requirement that a subparser be provided. I still don't know why that is necessary. See https://stackoverflow.com/questions/8521612/argparse-optional-subparser-for-version. A longer discussion is in https://bugs.python.org/issue9253, which leads me to believe that subparsers should not be required in 3.3+, so I don't really understand this, but this at least fixes the `--version` case.
> use action='version' in --version parser

- integration/tests/cook/test_basic.py
- instead of asserting exactly 1 instance, assert at least 1 instance
It's possible for there to be an initial, failed instance (e.g. `Invalid task`), followed by the expected, successful instance.
> Makes test_group_failed_only_change_retries_all_success more reliable

- integration/tests/cook/util.py
- if `COOK_TEST_DERIVE_MESOS_HOST` is set, deriving a Mesos host by parsing the `mesos-master` field from `/settings`
It's common for environments to have ZK and Mesos masters on the same hosts, and this change allows our tests to take advantage of this for such environments. Without this change, the test invoker has to provide the URL of the current Mesos leader via `COOK_MESOS_LEADER_URL`, which is inconvenient.
> Allows for deriving Mesos host from mesos-master config

- scheduler/src/cook/cors.clj
- scheduler/test/cook/test/cors.clj
- Adds support for `x-forwarded-proto` header for validating CORS requests
Support configurations where Cook could be running behind a reverse proxy.
> Add support for x-forwarded-proto in CORS requests

- README.md
- fixing the link to the changelog from the README
We moved the changelog a while back and didn't correct this link.
> Fixes changelog link in README

- integration/tests/cook/test_basic.py
- adding a retry to the "slow" job
We've seen this test fail due to the "slow" job getting a transient failure, e.g. `Invalid task`.
> Makes test_group_kill_simple more reliable

- integration/tests/cook/test_cli.py
- using `cli.command()` instead of hard-coding `"cs"` in `test_show_from_jupyter`
Otherwise, the test can fail in cases where a custom `COOK_CLI_COMMAND` is provided.
> Makes test_show_from_jupyter use COOK_CLI_COMMAND

- integration/bin/run-integration.sh
- integration/tests/cook/test_multi_user.py
- Fix preemption test to run multiple low priority jobs
Some environments might have task constraints that prevent a single low priority job from filling a machine.
> Fix preemption test to run with lower task constraints

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
- Only create one commit latch per batch of jobs
Reduce unnecessary entity creation
> Make one commit latch per job submission batch

- scheduler/src/cook/mesos/pool.clj
- Use `nil-pool` instead of a new random UUID as the default
Save calling `(UUID/randomUUID)` unnecessarily. Also add a comment explaining why this is the default.
> Use `nil-pool` instead of a new random UUID

- integration/tests/cook/test_multi_user.py
- integration/travis/run_integration.sh
- Run preemption test serially
Reduce flakiness by lowering contention on mesos for tests which have specific resource demands.
> Run preemption test serially

- jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java
- jobclient/src/test/java/com/twosigma/cook/jobclient/JobClientTest.java
- Make temporal UUID code in our JobClient API that can be used by our customers.
- Investigation found that random ID's could be a bottleneck in job submission.
- Using temporal UUID's would let us increase the job submission rate by 10x-30x, to 1000-3000 jobs/second, if used for commitlatch and by client code.
- This includes code that customers can call that makes appropriate UUID's.
> Add UUID generator to JobClient.

- integration/bin/run-integration.sh
- integration/tests/cook/test_basic.py
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/data_locality.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/schema.clj
- scheduler/test/cook/test/config.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/data_locality.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/testutil.clj
- Adds a new fitness calculator incorporating data locality
We want to support integrating Cook Scheduler with a service which will compute the cost of running jobs on different machines based on the effects of data locality. Once we have the service integrated, we could use this fitness calculator to enforce the scheduling constraints.
> Add data local fitness calculator

- jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
Changes proposed in this PR
-  Make Job.java use new temporal ID by default.
Why are we making these changes?
-    Investigation found that random ID's could be a bottleneck in job submission.
-    Using temporal UUID's would let us increase the job submission rate by 10x-30x, to 1000-3000 jobs/second, if used for commitlatch and by client code.
-    This makes the default fast.
> Make Job.java use the temporal ID by default.

- scheduler/src/cook/mesos/sandbox.clj
- scheduler/test/cook/test/mesos/sandbox.clj
- generalizes the sandbox aggregator functions (in preparation for exit-code)
We would like to batch `exit-code` datomic writes and reuse the sandbox aggregator logic to achieve this.
> generalizes the sandbox aggregator functions

- jobclient/src/main/java/com/twosigma/cook/jobclient/Group.java
Changes proposed in this PR
-    Make Group.java use new temporal ID by default.
Why are we making these changes?
-    Investigation found that random ID's could be a bottleneck in job submission.
-    Using temporal UUID's would let us increase the job submission rate by 10x-30x, to 1000-3000 jobs/second, if used for commitlatch and by client code.
-    This makes the default fast.
> Make Group.java use temporal ID by default.

- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/scheduler.clj
- Use the datomic temporal UUID in two spots in the cook scheduler, the task_id and commit latch.
- Investigation found that random ID's could be a bottleneck in job submission.
- Using temporal UUID's would let us increase the job submission rate by 10x-30x, to 1000-3000 jobs/second, if used for commitlatch and by client code.
- This includes the cook scheduler parts of the change.
- I'm changing the task ID UUID on general principals. We know from earlier information that random UUID's are expensive, so remove an extra one.
> Update cook API to use temporally clustered UUID's.

- integration/tests/cook/cli.py
- integration/tests/cook/test_basic.py
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/benchmark.clj
- scheduler/test/cook/test/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/simulator.clj
- scheduler/test/cook/test/testutil.clj
- adding some debugging info to `test_preemption`
- renaming the `offer-cache` to the `agent-attributes-cache`
- removing the TTL from the `agent-attributes-cache`
The cache formerly known as `offer-cache` isn't actually caching offers. It's caching agent attributes. When it cached offers, it made sense for there to be a TTL, because offers have a limited lifetime. Now that it only caches agent attributes, it's better for the agent attributes to not get evicted only because time has passed. We observed cases where preemption should have occurred, but did not occur, simply because the agent attributes in question had been evicted.
> Removes TTL from agent attributes cache

- integration/tests/cook/test_multi_user.py
- making `test_preemption` rely on the quota constraint rather than the hostname-equals constraint
We've seen odd behavior with minimesos where sometimes the "reserved" (i.e. `role = "*"`) resources aren't offered, and sometimes they are. When they aren't offered, then we think we have more space to fill on the agent than we can actually fill, which was making this test flake.
> Makes test_preemption not rely on filling an agent

- integration/tests/cook/test_basic.py
- renaming `test_balanced_host_constraint` to `test_balanced_host_constraint_can_place`
- removing `xfail` from it
The rename is to allow for running using `pytest -k ...` and not having to also run `test_balanced_host_constraint_cannot_place`. The removal of `xfail` is because the test now passes.
> Un-marks balanced host constraint test as xfail

- integration/tests/cook/test_basic.py
- removing `xfail` from `test_balanced_host_constraint_cannot_place`
The test passes consistently now.
> Un-marks test_balanced_host_constraint_cannot_place as xfail

- integration/tests/cook/test_basic.py
- removing `xfail` from `test_hostname_equals_job_constraint`
This test is now passing.
> Un-marks test_hostname_equals_job_constraint as xfail

- integration/tests/cook/test_basic.py
- removing `xfail` from `test_unique_host_constraint`
This test is now passing.
> Un-marks test_unique_host_constraint as xfail

- scheduler/bin/run-docker.sh
- using the `minimesos` from the `/travis` directory instead of assuming the user has one on the path
We already have a `minimesos` in the repo, so it's nice to not make the caller have their own.
> Uses the minimesos from /travis

- scheduler/project.clj
Update our dependency on Mesomatic to use a JAR with a non-snapshot version.
Leiningen doesn't like snapshots in dependencies of non-snapshot project builds.
Closes #942.
> Remove snapshot dependency on Mesomatic

- scheduler/docs/configuration.adoc
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/sandbox.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/simulator.clj
- adds exit-code-syncer to handle a high rate of incoming exit-code messages in a graceful manner
We would like to aggregate sending exit code datomic updates for tasks to avoid potential load issues based on our previous experience with the sandbox syncer.
> Adds exit-code-syncer to handle a high rate of incoming exit-code messages in a graceful manner

- README.md
- switching from `1.`, `2.`, `3.` to all `1.` in the quickstart
- recommending using the `minimesos` from `/travis` instead of installing your own
The numbering change is for easier editing of the list. The `minimesos` change is to encourage developers to use the bundled script instead of having to install their own.
> Corrects README instructions regarding minimesos

- spark/README.md
Add basic documentation of the extra options added in our Cook Spark patch.
Undocumented options are not very user friendly.
> Add docs for extra options in patched Spark for Cook

- scheduler/bin/run-local.sh
- scheduler/bin/start-datomic.sh
- Don't use docker in start-datomic.sh
Docker isn't required for datomic, so make it easier for people who prefer not to use it.
> Don't use docker in start-datomic.sh

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- adding a log with the number of total, running, and waiting jobs
To make failures easier to track down.
> Adds more logging to test_unique_host_constraint

- .gitignore
- Have .gitignore ignore *.orig files
- 
- 
Reduce clutter in git-gui.
> Update .gitignore to ignore *.orig files.

- scheduler/project.clj
- Remove this option
- 
- 
- This option is obsolete in JDK8 and above. It suppresses an error message that occurs on many lein commands.
> Remove -XX:MaxPermSize, obsolete in JDK8 and above.

- .travis.yml
- scheduler/src/cook/mesos/scheduler.clj
- turning on `--auth=http-basic` for the travis run without pools
- fixing a bug in quota-checking when running without pools
The travis change allows multi-user tests (e.g. `test_preemption`) to run in the no-pools build. The bug went unnoticed because these tests were previously not running on that build.
> Fixes quota bug when not using pools

- integration/tests/cook/test_impersonation.py
- integration/tests/cook/util.py
Don't follow the redirect on the `/queue` endpoint in the `test_self_impersonate` integration test.
The redirect was causing problems with Kerberose clients.
> Don't follow redirects on /queue admin self-impersonation test

- integration/tests/cook/reasons.py
- integration/tests/cook/test_basic.py
- allowing for the "waiting job" to become running in `test_unique_host_constraint`
In some environments, new Mesos agents can come online during the time that we wait for the unscheduled job reason to update. If this happens, our "waiting job" can switch to running, and we should allow for this in the test.
>  Makes test_unique_host_constraint more reliable

- integration/tests/cook/test_multi_user.py
- asserting that there is at least 1 active pool in `test_preemption_for_pools`
To ensure that the `for` loop below is not a no-op.
> Asserts that there is at least 1 active pool

- scheduler/project.clj
- Use the two sigma patched version of clj-http
This adds support for SPNEGO authentication
> Use twosigma clj-http

- integration/tests/cook/reasons.py
- integration/tests/cook/test_basic.py
- allowing for the case where the "waiting job" becomes running while we wait for the unscheduled jobs reason
In some environments, new Mesos agents can become available during the time we're waiting for the unscheduled jobs reason. When this happens, we want to allow for the "waiting job" to become running.
> Makes test_balanced_host_constraint_cannot_place more reliable

- integration/tests/cook/test_basic.py
- making the command in `test_list_jobs_by_pool` be `sleep 600` instead of `sleep 300`
To ensure that the job is still in the running state throughout the entirety of the test.
> Changes sleep 300 to 600 in test_list_jobs_by_pool

- integration/tests/cook/test_basic.py
- adding logging to `test_instance_stats_failed`
We've seen this test fail on occasion, and these logs should help determine why.
> Adds logging to test_instance_stats_failed

- integration/tests/cook/util.py
- introducing `COOK_TEST_DEFAULT_TEST_TIMEOUT_SECS`, which lets you override the default test timeout
In some environments, we need to allow some tests to run for longer than 10 minutes.
> Allows overriding the default test timeout with an environment variable

- scheduler/project.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/heartbeat.clj
- scheduler/src/cook/mesos/mesos_mock.clj
- scheduler/src/cook/mesos/monitor.clj
- scheduler/src/cook/mesos/sandbox.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/mesos_mock.clj
- scheduler/test/cook/test/mesos/util.clj
- upgrades clj-time to `0.12.0`
- deletes unused generate-intervals function
- adds time-seq helper function to bypass overflow issues from `periodic-seq`
- replaces uses of `periodic/periodic-seq` with `util/time-seq`
`periodic-seq` exhibits integer overflows when the scheduler runs for a long time.
> `periodic-seq` overflow bug

- integration/tests/cook/util.py
- removing the assumption that the `cook-pool` attribute is present on Mesos agents
We don't want consuming tests to fail simply because agents don't have this attribute set.
> Removes assumption that cook-pool attribute is present

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- Skips the data local constraint test when the fitness calculator is disabled
The test will fail in an environment where the data local fitness calculator is not enabled, because the constraint is not enforced.
> Skip data local constraint test when fitness calculator is disabled

- integration/tests/cook/util.py
- introducing `COOK_TEST_DEFAULT_WAIT_INTERVAL_MS`, which allows for overriding the default wait interval (i.e. time between attempts) used by most of the `wait_*` functions
In some environments, it's useful to allow the total timeout to be quite high (e.g. 8 minutes), in which case checking the condition once per second can cause the test logs to get way too huge. In these cases, it's also nice to allow for a longer wait between checks.
> Allows for overriding wait interval with environment variable

- .travis.yml
- Trigger Travis-CI on branches with the `build/` prefix.
This makes it easier for developers to trigger Travis-CI on branches in their personal GitHub forks of the Cook Scheduler project.
> Trigger Travis-CI on branches with "build/" prefix

- scheduler/src/cook/mesos/scheduler.clj
- Add some additional logging around the number of considerable jobs in matching
Increased visibility into how aggressively we're penalizing fenzo for failing to match the highest priority job.
> Additional logging around matching

- integration/tests/cook/test_basic.py
- integration/travis/scheduler_travis_config.edn
- scheduler/config.edn
- scheduler/src/cook/mesos/data_locality.clj
- Attempt to remove stale dataset costs even when there are no new updates
This fixes a bug where the stale dataset costs would sit in the cache indefinitely after there were no more waiting jobs.
> Remove stale datasets when not updating

- scheduler/src/cook/mesos/unscheduled.clj
- scheduler/test/cook/test/mesos/unscheduled.clj
- Use metatransaction for loading jobs in a user's queue for unscheduled_jobs
Fixes a bug where users would see enqueued, uncommitted jobs in unscheduled_jobs.
> Use metatransaction for loading unscheduled_jobs

- .travis.yml
- integration/travis/run_integration.sh
- Use `name: ...` instead of `env: NAME=...` to name our Travis jobs.
- Capture integration tests' stdout/stderr in a log file when running in Travis.
The main motivation of this change is that we don't currently get the console output in our Travis log dumps. If we restart a failed job, we still have the rest of the dump, but we lose console, which makes debugging more difficult. Having the console output for the integration test runner improves the log dumps by making them more stand-alone.
And the `name` thing just looks nicer.
> Capture output from pytest when running integration tests

- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- integration/travis/scheduler_travis_config.edn
- scheduler/config.edn
- scheduler/docs/configuration.adoc
- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/rate_limit.clj
- scheduler/src/cook/rate_limit/generic.clj
- scheduler/src/cook/rate_limit/token_bucket_filter.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/monitor.clj
- scheduler/test/cook/test/rate_limit/generic.clj
- scheduler/test/cook/test/rate_limit/token_bucket_filter.clj
- scheduler/test/cook/test/testutil.clj
- Token Bucket Filter core --- the rate limit accounting code.
- This will be integrated into the job submission path in a future PR.
- We have existing rate limits, but those only rate limit HTTP request rate. 
- We want context-aware rate limits that look based on the costs of processing a request. E.g., 100 HTTP requests each inserting one job versus each inserting 300 jobs. 
- More importantly, we want to allow bursting to a higher limit -- production can have 10k jobs inserted in 30 seconds. Ergo the use of a TBF.
- This gives us the foundation for implementing those controls.
> New Token Bucket Filter and Rate Limit core code.

- scheduler/src/cook/mesos/scheduler.clj
For the task throughput metrics:
- moving from statically defined metrics to dynamically fetching the metrics by title
- adding pool name to the end of the title
This is the first in a series of changes that will add pool name to the metrics where it makes sense to be able to break down the data by pool.
> Adds pool to task throughput metrics

- integration/tests/cook/test_multi_user.py
- Use `user.name` instead of a hardcoded name
- Use a single list of jobs to kill to prevent undefined variable errors
Makes the integration test pass internally
> Fix rate limit integration test

- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/test/cook/test/mesos/rebalancer.clj
- Uses the pool name in rebalancer metrics
This will allow us to track rebalancer metrics across different pools
> Use pool name in rebalancer metrics

- jobclient/pom.xml
Update JobClient dependency Apache HttpClient to v4.5.5.
A customer has a conflict with the old version, and asked us to upgrade.
> Update JobClient dependency Apache HttpClient to v4.5.5

- scheduler/src/cook/mesos/api.clj
- Adds the pool name to the "jobs created" metric
Allows for more accurately tracking across pools
> Add pool name to jobs created metric

- cli/cook/subcommands/jobs.py
- cli/cook/version.py
- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/util.py
- adding `--pool` to `cs jobs`, allowing the user to list jobs for a specific pool
- adding an integration test
In environments with multiple pools, users may want to view their jobs by pool as opposed to all together.
> Allows filtering by pool for cs jobs

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/config.edn
- scheduler/src/cook/mesos/api.clj
- Supports specifying the header `X-Cook-Pool` to provide the pool parameter on pool-specific requests.
This will make it easier to migrate clusters onto the pool model, by replacing a cluster with a proxy which forwards requests to a different cluster with the `X-Cook-Pool` header set.
> Use x-cook-pool header when no pool param is provided

- .travis.yml
- cli/cook/subcommands/submit.py
- cli/cook/version.py
- integration/tests/cook/test_cli.py
- adding `--docker-image` / `-i` flag to `cs submit`, which allows user to pass the name of a docker image
To allow for submitting docker jobs using `cs`.
> Adds support to cs for submitting docker jobs

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/monitor.clj
- scheduler/src/cook/mesos/rebalancer.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- scheduler/test/cook/test/simulator.clj
- clarifies contents of variable by renaming from pool to pool-name
Variable names should clarify their contents (e.g. pool vs the name of the pool) when possible to do so. This improves readability and can also avoid bugs.
> clarifies contents of variable by renaming from pool to pool-name

- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/sandbox.clj
- scheduler/test/cook/test/simulator.clj
- disables sandbox syncer when unprocessed-host->task-ids-atom is missing (e.g. during simulation)
- avoids killing node when ZK connection is lost while running simulations
We would like long-running simulations to execute without superfluous ERROR logs as well as abrupt terminations due to lost ZK connections.
> Simulator fixes

- integration/requirements.txt
- updating `numpy` to `1.15.3`
- updating `requests` to `2.20.0`
The `numpy` change is to correct issues we've seen when running `pip install` in Conda environments. 
The `requests` change is to address a security vulnerability: 
https://github.com/twosigma/Cook/network/alert/integration/requirements.txt/requests/open
> Updates requests and numpy versions for tests

- jobclient/src/main/java/com/twosigma/cook/jobclient/Job.java
- jobclient/src/test/java/com/twosigma/cook/jobclient/JobTest.java
- Adding support for pools to the Java Client library
To be able to leverage pools in Spark job submissions.
> Support for cook-pools in the job client

- jobclient/pom.xml
- jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java
- jobclient/src/main/java/com/twosigma/cook/jobclient/auth/spnego/BasicSPNegoSchemeFactory.java
- Allow users to set a custom `AuthSchemeProvider` when building a new `JobClient`.
- Add a static `build` method to `BasicSPNegoSchemeFactory`, which lets us handle all of the `SPNegoSchemeFactory` construction logic for the JobClient in one place.
- Define and document a new static constant flag `USE_CANONICAL_HOSTNAME`.
- Add commented-out `USE_CANONICAL_HOSTNAME` parameter in all `SPNegoScheme`-related constructor invocations as todo items for the future upgrade.
Allowing users to set a custom `AuthSchemeProvider` when building a new `JobClient` lets users manually configure their SPNego auth correctly when they use newer versions of the Apache HttpClient. This is a workaround until we can reasonably assume all JobClient users are able to upgrade to the newer Apache HttpClient …
> JobClient with custom HttpClient

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- using `util.hosts_to_consider` to avoid using agents assigned to a pool different from the one we're submitting on
- adding some logs
- fixing the `kill_jobs` call (`'dict_values' object does not support indexing`)
So that we can start running this test again.
> Makes test_hostname_equals_job_constraint work with pools

- integration/tests/cook/test_basic.py
- adding a call to `util.wait_for_exit_code` before assuming the exit code is populated
This function can fail if the exit code is not yet populated on the instance.
> Makes memory_limit_exceeded_helper more reliable

- integration/tests/cook/test_basic.py
- adding `skipUnless(util.is_cook_executor_in_use(), ...)` to two tests that assume the cook executor is in use
It's possible for clusters to have the cook executor configured, and still not in use (e.g. when running with docker).
> Skips cook executor tests when cook executor is not in use

- integration/tests/cook/test_basic.py
- changing the existing early `return` to a `pytest.skip` call
- adding a skip when there are 0 hosts to consider
In clusters that dynamically scale up agents in response to demand, this test can encounter the state where there are currently no running agents to consider. In this scenario, we'd rather simply skip the test.
> Skips test_balanced_host_constraint_cannot_place when there are no agents to consider

- scheduler/src/cook/rate_limit.clj
- scheduler/src/cook/rate_limit/generic.clj
- scheduler/src/cook/rate_limit/token_bucket_filter.clj
- scheduler/test/cook/test/rate_limit/generic.clj
- Enhance rate limit API to support fetching the number of tokens.
- 
- 
To prepare for the followup PR where we use the fetched token count to avoid 'going too far into debt'
> Enhance rate limit API to support fetching the number of tokens.

- integration/bin/run-data-local-server.sh
- integration/bin/run-integration.sh
- integration/src/data_locality/Dockerfile
- integration/travis/run_integration.sh
- scheduler/bin/run-docker.sh
- scheduler/bin/run-local.sh
- Change the data locality service port from 5000 to 35847
5000 may be used by other services running locally. Use a different,
random port, e.g., 35847 instead to reduce the risk of conflicts.
(I had a conflict with a system program on my laptop that had to be uninstalled temporarily.)
> Change the data locality service port from 5000 to 35847

- scheduler/src/cook/mesos/api.clj
- Wrap all of the default exception handlers with additional logging
Several of the exception types don't log at all, and the default logger doesn't log the request so it's hard to associate the log with the request that caused it.
> Add additional logging on exceptions

- cli/cook/subcommands/jobs.py
- When listing running jobs only, change the default lookback hours to 7 days
The default behavior of only showing the last 6 hours of running jobs can be confusing for users.
> Increase default lookback for listing running jobs with cs

- integration/travis/prepare_integration.sh
- Uninstall the CLI before installing the integration test requirements.
Occasionally, we'll have issues that appear to be related to caching the CLI source between runs of the travis build. Hopefully, this will prevent that from happening.
> Explicitly uninstall CLI to fix caching issues

- scheduler/src/cook/cache.clj
- scheduler/src/cook/mesos/data_locality.clj
- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/cache.clj
- scheduler/test/cook/test/mesos/util.clj
- Refactor the guava cache code into its own toplevel namespace
- Add an explicit :cache-expires-at value to the value dictionary for explicit expiration semantics
- 
- This refactor makes sense.
- The new :cache-expires-at will be used in the future plugin PR.
> Cache refactor and add explicit expiration.

- cli/cook/colors.py
- cli/cook/format.py
- cli/cook/progress.py
- cli/cook/querying.py
- cli/cook/subcommands/config.py
- cli/cook/subcommands/jobs.py
- cli/cook/subcommands/kill.py
- cli/cook/subcommands/ls.py
- cli/cook/subcommands/ssh.py
- cli/cook/subcommands/submit.py
- cli/cook/subcommands/usage.py
- cli/cook/terminal.py
- cli/cook/util.py
- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- switching from using the `blessed` library to simply rolling our own terminal colors, etc.
We are running into issues with `blessed` when using `pyinstaller`. Also, we simply don't use much of the functionality provided by `blessed`, so it's nice to get rid of the dependency.
> Removes blessed

- integration/tests/cook/test_basic.py
- marking `test_group_failed_only_change_retries_all_active` as `xfail`
We've seen this test fail because one of the 5 jobs fails with `Invalid task`. Here's an example:
https://travis-ci.org/twosigma/Cook/jobs/467034340#L1465
> Marks test_group_failed_only_change_retries_all_active as xfail

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- introducing `COOK_TEST_BALANCED_CONSTRAINT_NUM_HOSTS`, which allows the user to set the number of hosts used in `test_balanced_host_constraint_can_place`
- adding logging in `util.__get` when an unexpected status code comes back
In environments which dynamically provision Mesos agents, expecting 30 hosts to come up within the test timeout is not always realistic. The environment variable allows users to tone down this expectation. The logging is just for easier troubleshooting.
> Allows number of hosts to be set with an environment variable

- jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java
- jobclient/src/main/java/com/twosigma/cook/jobclient/JobClientException.java
- scheduler/project.clj
- Adds an HTTP response code field to JobClientException
It can be useful for users to differentiate between different failures (for instance, rate limited vs invalid request)
> Add http response code to JobClientException

- integration/README.md
- integration/tests/cook/test_basic.py
- changing assumption of exactly 1 instance to at least 1 instance
- using the last instance instead of the first
- adding a log of the chosen instance
- removing `skipUnless(util.continuous_integration(), ...)` from 3 memory limit tests
There can be more than 1 instance, for example, due to a mea-culpa failure like `Invalid Mesos offer`. We want to assert on the last of these instances. As for removing the `skipUnless`, these tests run reliably in my local environment, and I think it's good for devs to be running these.
> Improves memory limit tests

- integration/tests/cook/util.py
- logging the entire group json in `group_some_job_started`
- changing the command to `sleep 600` in `group_submit_kill_retry`
There is a race in `group_submit_kill_retry` between the retry and checking if any of the jobs is running. If in between those two, all of the jobs in the group start and complete, then the test fails. The `sleep 600` should avoid this race.
> Makes group_submit_kill_retry more reliable

- cli/cook/http.py
- fixes typo in `cluser`
Fixes typo in code and error.
```
Traceback (most recent call last):
File "cook/__main__.py", line 18, in main
File "cook/cli.py", line 97, in run
File "cook/subcommands/jobs.py", line 170, in jobs
File "cook/subcommands/jobs.py", line 62, in query
File "cook/querying.py", line 160, in query_across_clusters
File "concurrent/futures/_base.py", line 425, in result
File "concurrent/futures/_base.py", line 384, in __get_result
File "concurrent/futures/thread.py", line 57, in run
File "cook/subcommands/jobs.py", line 42, in list_jobs_on_cluster
File "cook/http.py", line 108, in make_data_request
```
> fixes typo in `cluser`

- jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java
- jobclient/src/test/java/com/twosigma/cook/jobclient/JobClientTest.java
- Adds a delete endpoint for the java jobclient
People may use a separate URL for creating and deleting jobs (i.e. `jobs` vs `rawscheduler`)
> Add setDeleteEndpoint

- integration/Dockerfile
- scheduler/Dockerfile
We don't need to copy the integration test directory (and the virtualenv). We can also have docker cache the transactor untar.
- Some things to reduce docker generation overhead.
- 
-
> Clean up DockerFile

- cli/cook/cli.py
- cli/cook/plugins.py
- cli/cook/subcommands/ls.py
- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- adding `plugins` package, which supports config-based plugins
- adding a plugin hook in the `ls` subcommand for retrieving the entries
- adding an integration test for plugging in a dummy `ls` retrieval function
We want to support runtime extensions to the base `cs` subcommands so that environment-specific plugins can be easily configured. For example, some environments may want to specify a different mechanism for browsing files in the sandbox.
> Adds plugin mechanism to CLI

- scheduler/src/cook/mesos/task.clj
- scheduler/test/cook/test/mesos/task.clj
- When cook executor's `retry-limit` is set to 0, don't fallback to the mesos executor
Once Cook Executor is stable in production, it can be jarring for users to fall back. This allows disabling that behavior.
> Allow setting cook executor retry-limit to 0 to disable fallback

- integration/tests/cook/test_basic.py
- scheduler/bin/run-local.sh
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/constraints.clj
- scheduler/src/cook/mesos/data_locality.clj
- scheduler/test/cook/test/mesos/constraints.clj
- scheduler/test/cook/test/mesos/data_locality.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- Adds support for a "suitable" flag on data local service responses
This allows more granular control of the scheduling by the data local service.
> Add support for suitable flag to data local service

- scheduler/project.clj
- Make the MAVEN path overridable.
- 
- 
- Gives more build flexibility.
> Tweak project.clj

- cli/README.md
- cli/cook/cli.py
- cli/cook/configuration.py
- cli/cook/subcommands/config.py
- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- Introduces a central `.cs.json` file for the cs command
We want to have a default `.cs.json` configuration file for all users. This allows users to roll out updates to their configurations (for instance, adding a new cluster) by only updating the default `.cs.json` file rather than the `.cs.json` file of all their end users.
> Introduce a 'central' .cs.json for cs command.

- jobclient/pom.xml
- jobclient/src/main/java/com/twosigma/cook/jobclient/auth/spnego/BasicSPNegoSchemeFactory.java
- scheduler/project.clj
- Upgrades JobClient dependence of Apache HttpClient to v4.5.5
- Release JobClient v0.4.2
We want this newer version of the Apache HttpClient.
The changes to constructor calls using `USE_CANONICAL_HOSTNAME` are for better Kerberos compatibility, and were previously explained in #1013.
Please **rebase and merge** when resolving this PR, since we want to preserve the separate release commit.
> Feature/jobclient httpclient 4.5.5

- cli/README.md
- cli/cook/http.py
- cli/cook/mesos.py
- cli/cook/subcommands/cat.py
- cli/cook/subcommands/ls.py
- cli/cook/subcommands/tail.py
- integration/tests/cook/cli.py
- integration/tests/cook/mesos.py
- integration/tests/cook/test_cli.py
- Adding a HEAD request to the http requests.
- Adding a plugin hook in the `cat` and `tail` subcommands for printing out files
- Adding integration tests for plugging in dummy `cat` and `tail` plugin functions
We want to add runtime support extensions to the `cat` and `tail` subcommands to complement the plugins provided by the `ls` subcommand already. The added HEAD request may be used by plugins to quickly verify they can run successfully, defaulting otherwise to the base command.
> Adding plugins for cat and tail

- integration/tests/cook/test_basic.py
- scheduler/src/cook/mesos/task.clj
- scheduler/test/cook/test/mesos/task.clj
- adding `COOK_INSTANCE_UUID` with the instance UUID to the task environment
- updating/adding tests for it
So that tasks can make use of their Cook Scheduler instance UUID.
> Adds COOK_INSTANCE_UUID to the task environment

- scheduler/src/cook/mesos/api.clj
- scheduler/test/cook/test/mesos/api.clj
- Add additional logging to API operations which write or delete data
Improve our ability to debug the results of the operations after the fact.
> Add additional logging to API operations

- integration/tests/cook/cli.py
- Adding an environment variable to load plugin json to integration tests.
This change allows us to run the integration tests using our internal plugins by specifying the plugins in an environment variable.
> Adding option to load plugins to tests

- integration/tests/cook/test_cli.py
- using `65535` instead of `99999` in 2 tests to avoid `Port out of range` errors
- explicitly configuring a blank command prefix in `test_submit_with_command_prefix`
In some environments, these tests can fail without the above fixes.
> Fixes 3 CLI integration tests

- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- Updating the conditions of some of the unit tests so they interact with internal plugins better.
- Adding a flag to test_base_config_file so it won't try to create a base `.cs.json` file in a directory it may not have write privileges.
These changes will make the integration tests more robust, especially when testing against plugins.
> Updating tests for plugins

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- Use `pytest.skip` instead of `return`
- Add extra skip case for when the executor retry limit is too high
- Add extra skip case for when the executor retry limit is 0
`pytest.skip` is clearer than `return` (which implies the test passed) and the current test will fail under some configurations.
> Fix logic in test_no_cook_executor_on_subsequent_instances

- scheduler/src/cook/plugins/util.clj
Existing code runs incorrectly if the plugin you're resolvign is defined
in the importing namespace.
- Change from use to require.
- 
-
> Plugin resolution fix

- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/plugins/definitions.clj
- scheduler/src/cook/plugins/pool.clj
- scheduler/test/cook/test/mesos/mesos_mock.clj
- scheduler/test/cook/test/plugins/pool.clj
- scheduler/test/cook/test/testutil.clj
- Adds a plugin to support selecting the pool for an offer 
Some environments may want to use different logic for selecting the appropriate pool for an offer.
> Add plugin for pool selection

- integration/tests/cook/test_cli.py
- Mark the "tail large file" tests xfail
Several flaky builds on our internal Jenkins.
> Mark tail large file tests xfail

- integration/tests/cook/test_cli.py
- Mark some tests `xfail` which failed during a cron run
Improve build reliability.
> Mark tests which failed during cron runs xfail

- executor/cook/config.py
- executor/cook/executor.py
- executor/requirements.txt
- executor/setup.py
- executor/tests/test_config.py
- executor/tests/test_executor.py
- Add support for mesos executor checkpointing to Cook Executor
When supported by the agent, this allows the executor to reregister after an agent restarts.
> Add checkpointing support to Cook Executor

- scheduler/src/cook/mesos/util.clj
- scheduler/test/cook/test/mesos/util.clj
- A java.util.Date is the wrong type. Make it JodaTime so that the cleaner works correctly.
- 
-
> Make the auto clean uncommitted be a jodatime to match clojure.

- executor/cook/_version.py
- executor/cook/executor.py
- executor/tests/test_executor.py
- Only launch one thread on disconnect until reregistered is called.
It's wasteful to create the extra threads, and it pollutes the logs.
> Don't launch multiple reconnect threads if disconnected is called many times

- integration/tests/cook/test_cli.py
- removing an error message assertion from `test_cat_basic`
We've seen Mesos sometimes return non-404 for files that don't exist, so we should be less strict here about the error message we get for a non-existent file.
> Makes test_cat_basic more reliable

- executor/cook/__main__.py
- executor/cook/config.py
- executor/cook/executor.py
- executor/tests/test_config.py
- executor/tests/test_executor.py
- Report MESOS_DIRECTORY to cook as the sandbox location instead of MESOS_SANDBOX. This is the root filesystem path instead of the path in the container
- Explicitly write executor.log in the MESOS_SANDBOX, not the current working directory
These make cook executor behave better when in a container.
> Change cook executor to be more container-friendly

- executor/cook/config.py
- executor/cook/executor.py
- executor/tests/test_config.py
- executor/tests/test_executor.py
- executor/tests/utils.py
- integration/tests/cook/test_basic.py
- Add support for specifying a list of environment variables to clear in cook executor with `EXECUTOR_RESET_VARS`
Some environment variables may be set as part of starting the cook executor itself, which we would prefer not to propagate to the child process. This environment variable allows setting a list of environment variables to clear.
> Add support for EXECUTOR_RESET_VARS

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- using the attribute name configured in the pool-selection plugin if present
Without this change, environments that use an attribute name other than `cook-pool` will see test failures.
> Uses pool-selection plugin config to determine pool attribute

- jobclient/pom.xml
- jobclient/src/main/java/com/twosigma/cook/jobclient/Instance.java
- scheduler/project.clj
- scheduler/test/cook/test/jobclient/jobclient.clj
- Adds `getReasonMeaCulpa()` to jobclient `Instance`
- Release jobclient version 0.5.0 with the changes
This allows users to see if an instance failed for a mea culpa reason
Please rebase when merging.
> Add reason_mea_culpa to jobclient Instance

- scheduler/docs/scheduler-rest-api.adoc
- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/plugins/definitions.clj
- scheduler/src/cook/plugins/file.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/mesos/api.clj
- Adds a new field, `file_url`, on job instances and a plugin definition to generate a file url for an instance.
The Mesos file API can be cumbersome and is Mesos-specific. This allows us to migrate to a simpler API which could be implemented for another scheduler, like k8s.
> Add file_url to job instances

- integration/tests/cook/test_pools.py
- integration/tests/cook/util.py
- Use pool selection attribute in `slave_pool`
Fixes the `test_pool_scheduling` integration test in environments where the pool selection plugin is used.
> Use pool selection attribute in slave_pool

- executor/cook/__main__.py
- executor/cook/_version.py
- Has the executor listen for `SIGUSR1` to print stack traces to stderr
Allows debugging executors while running.
Example output:
```Thread 0x0000700007ac7000 (most recent call first):
File "threading.py", line 295 in wait
File "threading.py", line 551 in wait
File "cook/executor.py", line 175 in process_stop_signal
File "threading.py", line 864 in run
File "threading.py", line 916 in _bootstrap_inner
File "threading.py", line 884 in _bootstrap
Thread 0x00007000075c4000 (most recent call first):
File "cook/progress.py", line 211 in tail
File "cook/progress.py", line 279 in retrieve_progress_states
File "cook/progress.py", line 349 in track_progress
File "threading.py", line 864 in run
File "threading.py", line 916 in _bootstrap_inner
File "threading.py", line 884 in _bootstrap
Thread …
```
> Add a SIGUSR1 handler to print thread stack traces

- scheduler/src/cook/mesos/monitor.clj
- scheduler/test/cook/test/mesos/monitor.clj
- Cast new metric values to `long` instead of `int`
It's possible for the value to be larger than an int, and it is supported by the underlying metric library so we should handle it cleanly.
> Use long instead of int for metric values

- scheduler/src/cook/cache.clj
- Do the cache lookup inside of a lock
- 
- 
Without this, we can have multiple outstanding requests for the same
key, possibly hitting a backend multiple times.
lookup-cache-with-expiration! has the fix already.
> Limit the number of outstanding lookup-key! requests.

- .travis.yml
- executor/cook/executor.py
- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/util.py
- integration/travis/run_integration.sh
- scheduler/bin/submit-docker.sh
- scheduler/src/cook/mesos/task.clj
- scheduler/test/cook/test/mesos/task.clj
- Allow jobs to run in a docker container using Cook Executor
This will allow jobs using containers to utilize executor-specific features like exit code and progress.
> Allow running cook executor in docker containers

- integration/tests/cook/util.py
- Add a new environment variable, `COOK_MAP_CONTAINER_VOLUME` to disable the integration test volume created for the cook executor
If the executor is built into the docker image, you don't want to create the volume mapping.
> Add COOK_MAP_CONTAINER_VOLUME

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/mesos/api.clj
- scheduler/src/cook/mesos/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/mesos/api.clj
- scheduler/test/cook/test/mesos/scheduler.clj
- Thread the compute-cluster name through Fenzo from the offer, instead of getting it via the global.
- 
- 
This ensures that the compute cluster is attached to the offer, an enabling refactor for supporting more than one cluster. Now we know to whom to send the response.
> Thread compute cluster through Fenzo

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- Rename `COOK_MAP_CONTAINER_VOLUME` to `COOK_NO_CONTAINER_VOLUME` which is more clear
- Explicitly pass `executor` in two tests which were relying on portion
Makes the tests more reliable in environments where the cook executor portion is low.
> Fix executor argument in some tests

- integration/tests/cook/test_basic.py
- Log instances when tests fail
Makes test failures easier to debug.
> Log instances on test failure

- integration/tests/cook/util.py
- Don't automatically add a docker volume if the executor path is relative
Mesos won't be able to create the container.
> Don't set docker volume if executor path is relative

- scheduler/src/cook/config.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/benchmark.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Limit the number of over-quota jobs output by ranking
This can cause performance issues downstream in a situation where there are relatively few runnable jobs, but many jobs that are over quota in the global queue.
After change:
```
lein test cook.test.benchmark
============ rank-jobs timing ============
Evaluation count : 6 in 6 samples of 1 calls.
Execution time mean : 842.769115 ms
Execution time std-deviation : 32.152188 ms
Execution time lower quantile : 819.166167 ms ( 2.5%)
Execution time upper quantile : 892.687703 ms (97.5%)
Overhead used : 1.849735 ns
Found 1 outliers in 6 samples (16.6667 %)
low-severe	 1 (16.6667 %)
Variance from outliers : 13.8889 % Variance is moderately inflated by outliers
============ rank-jobs minus offensive-job-filter timing ============
Evaluation …
```
> Limit ranked jobs

- executor/setup.py
- Add a python 3 classifier to the executor setup.py
The executor requires python3, so make this clear to potential users.
https://test.pypi.org/project/cook-executor/
> Add python 3 classifier

- integration/tests/cook/test_multi_user.py
- scheduler/src/cook/mesos.clj
- Pass `compute-cluster` instead of `driver` to rebalancer
- Fix integration test to detect issue
Currently, the rebalancer thinks it killed things but doesn't actually terminate them. Fix the bug, and fix the test to detect this in the future.
> Fix rebalancer

- integration/tests/cook/test_basic.py
- Fix call to `unittest.skip`
Correctly skips the test when default volumes are not configured.
> Call self.skipTest instead of unittest.skip

- scheduler/src/cook/components.clj
- scheduler/src/cook/config.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/mesos/task.clj
- scheduler/test/cook/test/rest/api.clj
- scheduler/test/cook/test/zz_simulator.clj
- Removes framework id from components
- Adds support for guessing framework id in responses when feasible
In kubernetes, there won't be a framework id.
> Remove framework id from components

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/rebalancer.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Remove `cc/get-mesos-driver-hack` and replace with `cc/kill-task` and `cc/decline-offer`
Last remaining refactor for compute cluster API
> Remove get-mesos-driver-hack

- scheduler/java/com/twosigma/cook/kubernetes/WatchHelper.java
- scheduler/project.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/schema.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/schema.clj
- Adds Kubernetes compute cluster
- Allows marking instances as succeeded without transitioning to running.
Part of adding Kubernetes support.
The instance change is something that could happen in Mesos (for instance, if you missed the task running message and found the task had succeeded during reconciliation) but is more likely in Kubernetes. I think it's a reasonable change to make for both.
> Add Kubernetes Compute Cluster

- scheduler/src/cook/rest/api.clj
- Propagate job entities instead of job UUID's when assembling /list API responses. This avoids finding job entities, mapping them to job UUID's, then looking up jobs from their UUID in the /list path.
- 
- 
This is a tech-debt/cleanup. Note that this isn't cleaning up the /jobs endpoint. That code would need more restructuring to fix (it propagates UUID's within the liberator context between the list and the explicit-uuid sub-endpoints).
> Optimize the job fetching code to not round-trip to UUID.

- integration/tests/conftest.py
- adding the `run-description` field
To allow for a description of what the run is doing/testing.
> Adds run-description to test metrics collection

- scheduler/src/cook/config.clj
- Under some circumstances, Cook can fail to launch without logging anything. At least in this case, make it not fail silently.
- 
- 
- Failing silently with no error shown is irritating to debug.
> Make Cook not fail silently on startup on some startup errors.

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- These state atoms are compute-cluster specific. Move them within the compute cluster.
- 
- 
- These state atoms are compute-cluster specific, so can't be global.
> Light refactor to move things into KubernetesComputeCluster

- integration/tests/cook/test_basic.py
- integration/travis/scheduler_travis_config.edn
- scheduler/config.edn
- scheduler/src/cook/rest/api.clj
- Adds a new configuration parameter to configure maximum command length
Prevents users from submitting arbitrarily long commands.
> Add maximum command length configuration parameter

- scheduler/config-k8s.edn
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/mesos/mesos_compute_cluster.clj
- scheduler/test/cook/test/rest/api.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Refactor `handle-status-update` to remove sandbox syncing and lingering task killer
- Invoke handle status update from Kubernetes controller
We need to write Kubernetes state back to Datomic.
> Write Kubernetes state back to Datomic

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/zz_simulator.clj
- Refactor scheduler/compute cluster offer interface
This allows a more natural integration for Kubernetes than the channel-based approach.
> Improve Kubernetes fenzo integration

- .travis.yml
- Runs integration tests on kubernetes_integration PRs
This is a production-ish branch, so let's run tests while we're working on the Kubernetes integration.
> Run travis builds on kubernetes_integration

- scheduler/src/cook/rebalancer.clj
- scheduler/test/cook/test/rebalancer.clj
- Only consider jobs for rebalancing that will be within a user's quota
Currently, it's possible to preempt jobs running as another user when the candidate job cannot launch due to the user being out of quota.
> Check quota while rebalancing

- scheduler/README-k8s.adoc
- scheduler/config-k8s.edn
- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/task.clj
- scheduler/src/cook/tools.clj
- Initialize the kubernetes expected state from the datomic-stored instance state
- Its been minimally tested by launching a job, killing cook, and then resuming cook.
- Several todo's have been added.
So that cook will reinitialize and resume from a shutdown.
> Initialize kubernetes expected state from datomic

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- scheduler/src/cook/kubernetes/controller.clj
- Disable some integration tests on kubernetes/minikube
- Fix bug in state machine
The remainder of the non-cli tests pass on Kubernetes, so we can get a build pipeline.
> Get integration tests passing for Kubernetes

- scheduler/README-k8s.md
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Support configurable namespaces for Kubernetes pods
- Support per-user pod namespaces
In some environments it is desirable to have per-user Kubernetes namespaces, but we want to keep "single namespace" support for local development.
> Add support for configurable namespaces

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- Fix more errors with referencing `mesos_url` on Kubernetes
- Make `util.max_cpus()` callable on both Mesos and Kubernetes
Improves integration test coverage of Kubernetes scheduler.
> Make max_cpus platform independent

- scheduler/src/cook/kubernetes/compute_cluster.clj
- Increase the timeout
- 
- 
Avoid a lot of log spam
> Increase kubernetes timeout from 10 seconds to 120 seconds.

- integration/tests/cook/test_cli.py
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Label pods if they're cook job pods.
- Ignore those pods for cook's kubernetes state management.
- 
This enables soon-to-be-added state scanners which means that we get retries and a proper startup for kubernetes support.
> Label pods if they're cook job pods.

- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- Uses `COOK_DEFAULT_JOB_CPUS` in the preemption tests
Makes test perform better in environments where `COOK_DEFAULT_JOB_CPUS` has been reduced.
> Use COOK_DEFAULT_JOB_CPUS in preemption tests

- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Counts the starting pods against node utilization when computing offers on kubernetes
Fixes race where resources could be double-booked.
> Count starting pods against offers

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/test/testutil.clj
- We should be scheduling against `allocatable` instead of `capacity`
Because `capacity` does not reflect the actual resources available for scheduling.
> Use allocatable instead of capacity

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Scan and reprocess all of the task states on startup and on an interval.
- 
- 
- Cook more correctly recovers after a restart. It can also retry failed kubernetes now.
> State scanner on startup and on an interval.

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Uses MB for memory when interfacing with Kubernetes instead of MiB
The Cook API, Mesos, and Fenzo all assume MB. We need to be consistent between them.
> Use MB for memory instead of MiB

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/kubernetes/controller.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Use `{:namespace namespace :name name}` for map keys
Names are not unique globally.
> Use namespaced pod names for map keys

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- Remove more direct uses of `mesos_url`
Makes more tests compatible with Kubernetes.
> Remove more uses of mesos_url

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/bin/run-local-kubernetes.sh
- scheduler/src/cook/mesos/task.clj
- scheduler/test/cook/test/mesos/task.clj
- Add `COOK_INSTANCE_NUM` environment variable
This replaces existing custom-executor-specific functionality
> Add COOK_INSTANCE_NUM environment variable

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Use the compute cluster name in Kubernetes cook pod label
Makes it less likely for cook clusters to stomp on each other.
> Use compute-cluster-name in kuberentes pod label

- scheduler/Dockerfile
- scheduler/project.clj
- Reduces the amount we put on top of the existing image by about 140mb.
- 
- 
Smaller dockers build faster and waste less space locally.
> Reduce scheduler docker image size; cuts docker image growth by 15%

- cli/cook/subcommands/submit.py
- integration/tests/cook/cli.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/util.py
- Make cs generate temporal UUID's when it submits jobs to cook.
- 
- 
Random UUID's can be 30x much more expensive to manage.
> Write and switch cs cli to use temporal UUID's.

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- Use `/slaves` instead of `/state.json` for retrieving slaves
The `/slaves` endpoint is much faster.
> Use /slaves instead of state.json

- .gitignore
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- adding the pool name to several logs in `scheduler.clj`
To make troubleshooting scheduling issues easier in multi-pool environments.
> Adds pool name to several log messages

- integration/tests/cook/test_basic.py
- scheduler/src/cook/kubernetes/api.clj
- Add support for volumes in Kubernetes jobs
- Fix default volume test to support running on a remote host
Improves our Kubernetes API coverage.
> Support volumes in kubernetes

- integration/.gitignore
- integration/requirements.txt
- integration/setup.cfg
- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/test_pools.py
- integration/tests/cook/util.py
1. logging the unscheduled info when we're waiting for a job to have instances
1. moving several tests to `test_multi_user.py` and adding `with self.user_factory.admin()` for admin-only requests
1. avoiding usage of the `cook` executor when HTTP basic auth is in use
1. The added logging is to help troubleshoot failures in `test_pool_scheduling` (or any other test that uses `wait_for_running_instance`).
1. The multi-user moves are needed because otherwise these tests assume that they are being run as an administrator, which is not always the case, especially in developer environments running with HTTP basic auth.
1. There were a few tests that assumed that the `cook` executor could be used successfully just because it was configured. In reality, it needs to be configured **and** basic auth …
> Adds logging and other test improvements

- integration/tests/cook/test_basic.py
- scheduler/config-k8s.edn
- scheduler/src/cook/config.clj
- scheduler/src/cook/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/api.clj
- Use uuids to for Kubernetes volume names  
- Add support for disallowed container mount paths
UUIDs are guaranteed to pass the Kubernetes name validation regex.
Disallowing container paths allows blocking paths that may be added elsewhere in Kubernetes (for instance, in an admission controller.)
> Improvements to k8s volumes

- integration/tests/cook/test_basic.py
- Fix `test_default_container_volumes` to check for RW mode
The test requires a volume mounted in RW mode.
> Check for RW mode in test_default_container_volumes

- executor/setup.py
- integration/tests/cook/util.py
- Don't cache the kerberos authentication token between usages of a user object 
- While a user object is active, refresh the kerberos auth token every 60 seconds
This prevents the ticket from expiring and causing spurious test failures.
> Periodically reset kerberos auth token

- integration/tests/cook/test_basic.py
- scheduler/config-k8s.edn
- scheduler/config.edn
- scheduler/src/cook/config.clj
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- Add support for whitelisting docker parameters
Not all docker parameters will be supported by kuberenetes, so adding an explicit whitelist
> Add docker parameter validation

- integration/tests/cook/test_basic.py
- Mark `test_cook_instance_num` xfail
Flaky travis builds (https://travis-ci.org/twosigma/Cook/jobs/594639302)
> Mark test_cook_instance_num xfail

- scheduler/src/cook/scheduler/scheduler.clj
- adding logging of `enforcing-job-launch-rate-limit?`
Without this, operators looking at logs are easily misled into thinking that jobs are being rate limited when they actually aren't.
> Logs whether or not rate limiting is enforced

- integration/tests/cook/test_basic.py
- Use valid docker parameters in `test_docker_fields`
Test is currently broken due to parameter validation.
> Fix test_docker_fields

- .travis.yml
- integration/setup.cfg
- integration/tests/conftest.py
- integration/tests/cook/test_cli.py
- removing the basic auth and cook executor builds from the travis run
- adding `--durations=25` to the pytest config
- changing iterations from 20 to 10 in `test_tail_large_file`
We have equivalent test runs internally, and removing these from travis will free up precious travis workers.
`test_tail_large_file` is often the longest-running test in the pipeline, and it probably doesn't need to be so extreme to be valuable.
> Removes 2 builds from travis run

- cli/cook/subcommands/submit.py
- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- scheduler/src/cook/rest/api.clj
- increase max job priority to 2^24
Some users need priority over 100 (e.g. IDs used as a priority that fit in a 2^24 namespace)
> increase max priority to 16,000,000

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_pools.py
- integration/tests/cook/util.py
- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/test/testutil.clj
- scheduler/test/cook/test/kubernetes/api.clj
- scheduler/test/cook/test/kubernetes/compute_cluster.clj
- Support multiple pools with kubernetes, using taints and tolerations.
To make this feature work in kubernetes as well as the existing mesos support.
> Pool support

- integration/tests/cook/test_basic.py
- scheduler/src/cook/config.clj
- scheduler/src/cook/rest/api.clj
- scheduler/test/cook/test/rest/api.clj
- Add a `max-ports` config to task constraints
Allows administrators to set a maximum number of ports per job.
> Add max-ports to task constraints

- integration/tests/cook/test_cli.py
- marking `test_tail_default_path` with `xfail`
We've seen this test be flaky in some environments.
> Marks test_tail_default_path as xfail

- integration/tests/cook/test_cli.py
- integration/tests/cook/util.py
- introducing `COOK_TEST_DISALLOW_POOLS_REGEX`, which allows you to disallow testing against particular pools
In some environments, you may not want to test against certain pools.
> Supports disallowing certain pools for integration tests

- integration/tests/cook/test_basic.py
- making the `sleep` match the timeout for the test
- adding some logging in the pool loops
Without the `sleep` adjustment, if the other jobs take a long time to get scheduled, the `sleep` jobs can complete, which makes the listing assertion fail.
> Makes test_list_jobs_by_pool more reliable

- integration/tests/cook/test_basic.py
- checking for any successful instance, instead of the 0th one
Jobs can retry, and we really just need to make sure that the job eventually succeeds.
> Makes test_basic_docker_job more reliable

- scheduler/src/cook/kubernetes/api.clj
- adding the pod name to the error log when the pod submission fails
It's common to search our logs for the task id (which is the pod name), and this will make the error logs show up for these searches.
> Adds pod name and namespace to submit error log

- scheduler/src/cook/mesos.clj
- scheduler/src/cook/rebalancer.clj
- scheduler/src/cook/task.clj
- Refactor rebalancer to not use global compute cluster
Intermediate step to supporting multiple compute clusters.
> Refactor rebalancer to not use global compute cluster

- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Refactor handle-resource-offers-refactor to not use global compute-cluster
Intermediate step to supporting multiple compute clusters.
> Refactor handle-resource-offers to not use global compute-cluster

- scheduler/src/cook/mesos/heartbeat.clj
- get rid of "dropped heartbeat from task" errors, make them debug level 
not needed, too much log spam
> get rid of "dropped heartbeat from task" errors

- scheduler/src/cook/mesos.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/mesos/mesos_compute_cluster.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Refactor fenzo initialization to not use global compute cluster.
- Discovered some dead code and deleted it
Prepare for supporting multiple compute clusters
> Refactor fenzo initialization to not use global compute cluster.

- integration/tests/cook/test_basic.py
(specifically `test_job_environment_cook_job_and_instance_and_group_uuid`)
- stops assuming a single successful job instance
Jobs can fail and retry. None of our test should assume the 0th instance is successful.
> Makes environment variable test more reliable

- integration/tests/cook/test_basic.py
- making the job sleep time a function of the default wait interval
In environments with a long wait interval, the job can complete before the test detects that it's running.
> Makes test_cancel_instance more reliable

- integration/tests/cook/test_cli.py
- marking `test_cat_large_file_no_newlines` as `xfail`
We've seen this test fail in some environments.
> Marks test_cat_large_file_no_newlines as xfail

- scheduler/src/cook/kubernetes/compute_cluster.clj
- splitting the log into two, one for capacity and one for consumption
- adding the compute cluster name to the log lines
The split is for readability, and the compute cluster name is because multi-compute-cluster support is coming, so we'll want to know which compute cluster the logs are for.
> Improves capacity and consumption logs

- scheduler/src/cook/kubernetes/api.clj
- We weren't actually updating our node dictionary when membership changed, so would miss k8s node changes.
So we can see new nodes when they occur.
> Fix Kubernetes Node Watch

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/scheduler/scheduler.clj
- Refactor cancelled task killer to remove global compute-cluster
Prepare for multiple compute cluster support
> Refactor cancelled task killer to remove global compute-cluster

- scheduler/src/cook/components.clj
- scheduler/src/cook/mesos.clj
- logging the zookeeper connection string on startup
- logging the leader path
Better debugging.
> Logs the zookeeper connection string, leader path

- integration/tests/cook/test_basic.py
- scheduler/src/cook/rest/api.clj
- adding the leader URL to the `/info` endpoint
It's nice to be able to ask who the current leader is.
> Adds leader URL to /info

- scheduler/src/cook/mesos.clj
- removing "mesos" from the leadership logs
The leadership has nothing to do with mesos, and having "mesos" in the logs is particularly confusing when running against k8s.
> Removes 'mesos' from leadership logs

- integration/tests/cook/test_cli.py
- marking `test_tail_zero_byte_file` as `xfail`
We've seen this test fail in certain environments.
> Marks `test_tail_zero_byte_file` as `xfail`

- scheduler/src/cook/mesos.clj
- scheduler/src/cook/scheduler/scheduler.clj
- scheduler/test/cook/test/scheduler/scheduler.clj
- Refactor lingering tasks killer to not use global compute cluster
Prepare for multiple compute cluster support
> Refactor lingering tasks killer to not use global compute cluster

- scheduler/src/cook/mesos.clj
- scheduler/src/cook/scheduler/scheduler.clj
- Refactor straggler handler to not use global compute cluster
Prepare for supporting multiple compute clusters
> Refactor straggler handler to not use global compute cluster

- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- fixing two invocations of `decline-offers-safe` to pass it the compute cluster instead of the driver
These calls are currently broken.
> Fixes bug in declining offers

- integration/tests/cook/test_basic.py
- allowing the test to pass when the jobs complete
We don't actually care for the purpose of this test whether the jobs are still running or not, we just need them to have an instance.
> Makes test_balanced_host_constraint_can_place more reliable

- integration/tests/cook/test_multi_user.py
- making the assertions in `test_instance_stats_running` less strict
We can't guarantee that all 3 of the test instances will remain running for the duration of the test. For example, an instance might get killed with "Agent removed".
> Makes test_instance_stats_running more reliable

- integration/tests/cook/test_basic.py
- changing the `sleep` amount to be a function of `util.DEFAULT_WAIT_INTERVAL_MS`
If the wait interval is set to something high enough, like 8 seconds, then it becomes more likely for all the jobs in the group to move from waiting to completed in between intervals, in which case `util.wait_until(group_query, util.group_some_job_started)` will never succeed.
> Makes test_group_change_retries more reliable

- scheduler/src/cook/kubernetes/api.clj
- Move the code that relaunches the watcher to the finally block so it always runs.
Without this change, we'd not restart the watch on a clean exit of the watcher, and we'd cease watching for node changes.
> Bug fix: We want to restart the k8s node watch even on a clean exit.

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- Better contextual logging on startup.
With multiple compute clusters, have the log indicate each one as it starts up.
> Better logging about startup/initializing.

- scheduler/src/cook/scheduler/scheduler.clj
- Log as we filter out jobs from being considered
- Make it easier to determine where and why we cease to consider jobs for scheduling
> Improve logging as we filter jobs from being considered.

- scheduler/src/cook/kubernetes/api.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- Improve the logging about filtering out nodes at the kubernetes level
Make it easier to determine why we're not logging on certain nodes.
> More logging on nodes being filtered

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/config.edn
- scheduler/docs/configuration.adoc
- scheduler/src/cook/components.clj
- scheduler/src/cook/plugins/adjustment.clj
- scheduler/src/cook/plugins/definitions.clj
- scheduler/src/cook/plugins/demo_plugin.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/test/testutil.clj
- introducing the `JobAdjuster` plugin
- adding a "demo" implementation that simply adds a label
- adding a test that verifies the "demo" implementation actually modifies the job
We want to allow plugins that can, for example, modify the pool on job submissions.
This PR sets up the plumbing for the plugin, and a future PR will introduce the real implementation, which will modify the pool on job submission based on configuration.
> Allows adjusting jobs on submission via plugin

- integration/tests/cook/test_cli.py
- reducing the iterations from 18 to 10 for this test
This test is consistently one of the longest-running in the suite, and it doesn't need to be so long to be useful.
> Makes test_tail_large_file_no_newlines take less time

- integration/tests/cook/test_basic.py
- integration/tests/cook/test_cli.py
- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- adding checks to `test_output_url` to actually confirm that the API works as expected
We are going to be supporting the same API in the k8s world, so we want our tests to make sure it works.
> Tests the output_url API

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- adding `util.timeout_interval_minutes`
- making the test timeout for `test_max_runtime_exceeded` be a function of the timeout interval
Otherwise, it's possible for the test to timeout before the timeout loop has a chance to mark the job as having exceeded its max runtime.
> Increases timeout for `test_max_runtime_exceeded`

- integration/tests/conftest.py
- when the result of calling the test not known, set the result to `uncompleted`
We've seen this happen in two cases:
1. When a test times out
1. When we reach the pytest max failures threshold and the run is aborted but there were tests in flight
> Records test metrics when tests don't complete

- scheduler/.dockerignore
- scheduler/Dockerfile
- Improve docker image generation.
Copying just the subdirs lets us avoid bringing in log files and datomic storage allowing both smaller images and less image churn. E.g., if we relaunch without changing anything, we won't have to rebuild the image!
> Docker image generation improvements

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/scheduler/scheduler.clj
- Change lingering task and straggler handler to use the wrapper.
There are cases, in particular, lingering tasks, stragglers, or cancelled tasks where the task might
outlive the compute cluster it was member of. When this occurs, the looked up compute cluster
is nil and trying to kill via it would cause an NPE. Switch them to using this wrapper function.
> Move some handlers from a compute-cluster/kill to compute-cluster/kill-task-if-possible.

- executor/Dockerfile.build
- Hardcode an earlier python image into the executor build
We do testing in minimesos, which is unmaintained and 2 years old.
Our cook-executor docker image is based on python. As of 6 days ago,
its been updated. It now requires a version of glibc that is too new
and unsupported in minimesos's images. Temporary fix to force a specific
python image.
> Workaround bug in running with minimesos.

- integration/tests/cook/test_basic.py
- integration/tests/cook/util.py
- scheduler/bin/run-local-kubernetes.sh
- scheduler/config-k8s.edn
- scheduler/src/cook/components.clj
- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/kubernetes/compute_cluster.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/rest/api.clj
- scheduler/src/cook/tools.clj
- scheduler/test/cook/test/zz_simulator.clj
- Iterate over all of the compute clusters in the config.edn and initialize them.
- Initial support and testing for multiple kubernetes compute clusters.
> Support multiple kubernetes compute clusters

- scheduler/bin/help-delete-temporary-clusters
- scheduler/bin/help-make-cluster
- scheduler/bin/make-gke-test-cluster
- scheduler/bin/make-gke-test-clusters
- scheduler/bin/run-local-kubernetes.sh
- scheduler/config-k8s.edn
- adding project arg to `help-delete-temporary-clusters`
- adding `--project` to all `glcoud` invocations
- adding a comment with prerequisites to the `make-` scripts
- removing the data local server from the k8s config
The GKE setup script changes are so that the scripts respect the project passed in at the top level.
The data local server removal is because we don't run with the data local server configured in any environment, so there's no need to configure it here.
> Tweaks GKE setup scripts

- scheduler/.dockerignore
- Ignore a jar when building docker images.
The cook jar is built within the docker image, so there's no need to copy
the for-local-invocation cook jar into the docker image. It just bloats it.
> Additional file to .dockerignore.

- scheduler/project.clj
- Remove a long-dead dependency
This dependency has been dead since 2016 when federation was removed. Its serialization code.
> Remove long-dead dependency.

- integration/tests/cook/test_multi_user.py
- integration/tests/cook/util.py
- retrying inside the test to avoid failures from delays
- allowing callers to specify not to log the request body when submitting jobs
Timing issues can cause this test fail, e.g. a delay between the bucket-emptying requests and the request that's expected to fail can cause it not to fail. So, we'll retry this a few times.
Avoiding logging the request body makes viewing the logs for this test much nicer, because you don't get a huge JSON blob from the large job submissions.
> Makes `test_rate_limit_while_creating_job` more reliable

- integration/travis/run_integration.sh
- scheduler/api-only-config.edn
- scheduler/bin/help-make-cluster
- scheduler/config.edn
- scheduler/datomic/data/seed_k8s_pools.clj
- scheduler/datomic/data/seed_pools.clj
- scheduler/minimesosFile
- travis/minimesosFile
- Rename all existing pools mesos-*
- Create k8s-* pools
Intermediate result so that we can test with mesos and kubernetes within the same configuration.
> Refactor cook so that we generate both k8s and mesos pool names.

- integration/tests/cook/test_basic.py
Making the following tests work when there are multiple instances:
- `test_job_environment_cook_job_and_instance_and_group_uuid`
- `test_max_runtime_exceeded`
- `test_group_kill_simple`
We should never assume a single instance in our tests. It's not uncommon for instances to fail due to e.g. `Agent removed`.
> Makes three tests more reliable

- integration/tests/cook/test_basic.py
- allowing for the job to go to completed instead of running due to e.g. `Invalid Mesos offer`
The job can fail instead of run, and we want to allow for that case in the test.
> Improves `test_change_retries_deprecated_post`

- integration/tests/cook/test_basic.py
- making the test timeout be a function of the scheduler's timeout interval
Even though the test is marked `xfail`, if it times out, the test run is considered a failure. So we want this test to run to completion.
> Increases timeout for test_straggler_handling

- scheduler/bin/help-delete-temporary-clusters
- scheduler/bin/help-make-cluster
- adding autoscaling to the node pools
- making the cluster deletes happen in parallel
We want to support testing with GKE autoscaling.
The parallel deletes is because the deletes take a long time.
> Adds autoscaling to test clusters

- scheduler/src/cook/kubernetes/api.clj
- using `get-pod-namespaced-key` for `handle-watch-updates`
- deleting the now-unused `get-pod-name`
This was a bug; the pod watch code was expecting to be using the namespaced key and was not for pod watch updates, resulting in e.g.:
```
2019-11-15 22:11:13,453 ERROR cook.kubernetes.controller [pool-4-thread-1] - Unexpected state:  [:expected/running :missing] for pod 5dcf7623-080e-4995-983a-a0faa52994ac
```
> Fixes key function used in pod watch

- integration/tests/cook/util.py
- making the `for` loop actually check all instances until it finds a running one
- returning the running instance instead of the 0th one
The function is broken and is causing at least one test that relies on it (`test_instance_stats_running`) to be flaky.
> Fixes bugs in `util.wait_for_running_instance`

- scheduler/src/cook/kubernetes/controller.clj
- making the log at the top of `process` more clear
So that you can tell from the log what each part of the log means without having to look at the code.
```
2019-11-18 21:40:52,700 INFO  cook.kubernetes.controller [pool-4-thread-5] - In compute cluster gke-2 , processing pod 5dd36440-8652-42ab-a816-b0a47752b831 ; expected: {:expected-state :expected/completed} , existing: {:synthesized-state {:state :pod/succeeded, :exit 0, :reason Completed}}
2019-11-18 21:40:52,787 INFO  cook.kubernetes.controller [pool-4-thread-5] - In compute cluster gke-2 , processing pod 5dd36440-8652-42ab-a816-b0a47752b831 ; expected: {:expected-state :expected/completed} , existing: {:synthesized-state {:state :missing, :reason Pod was explicitly deleted}}
2019-11-18 21:40:52,787 INFO  cook.kubernetes.controller …
```
> Makes `process` log more clear

- integration/tests/cook/test_basic.py
- allowing the job to go straight to completed instead of having to pass through running
We've seen the max-runtime killer fall in between checks for running, in which case the test never observes the running state and the wait times out.
> Makes test_max_runtime_exceeded more reliable

- integration/tests/cook/test_basic.py
- checking that the compute cluster in use is the expected one
We want to ensure that when we set the compute cluster test mode, jobs are actually getting sent to that compute cluster type.
> Asserts that the expected compute cluster type is being used

- integration/tests/cook/test_multi_user.py
- changing the job commands from `sleep 300` to `sleep {util.DEFAULT_TEST_TIMEOUT_SECS}`
We need to guarantee that the jobs will be running for the duration of the test. We've seen cases where one of the jobs runs and completes before the test is complete, which causes the test to fail.
> Makes test_instance_stats_supports_epoch_time_params more reliable

- integration/tests/cook/test_basic.py
See comments inline with changes.
See comments inline with changes.
> Makes several tests more reliable

- scheduler/src/cook/compute_cluster.clj
- scheduler/src/cook/mesos.clj
- scheduler/src/cook/mesos/mesos_compute_cluster.clj
- scheduler/src/cook/rebalancer.clj
- scheduler/src/cook/scheduler/scheduler.clj
-  Wrap most ComputeCluster API calls in a try-catch. everything in a try-catch.
- launch-tasks is done in PR#1322
- 
We don't want a single compute cluster failing to take down all of cook.
> Make our compute cluster code more robust between compute clusters.

- scheduler/src/cook/quota.clj
- improves time to build `user->quota-fn` by aggregating queries (gives around **4X** improvement in my tests)
- improves time to build user->quota-fn by aggregating count quota query (gives another **3X to 5X** improvement in my tests)
`create-user->quota-fn` (used in `rank-jobs`) makes lots of individual queries against datomic to build the `user->quota-cache`. Improve the execution time of `create-user->quota-fn` ends up improving the time spent ranking jobs.
> improves time to build user->quota-fn by aggregating queries
